### ISSUE TITLE
error: Duplicate File when building

### ISSUE THREAD

**Issue by tcpickard94** [onfido/onfido-android-sdk#1]
I am building a react-native app and including your sdk through gradle. When I add the required url `https://dl.bintray.com/onfido/maven` and dependency `com.onfido.sdk.capture:onfido-capture-sdk:+` to my gradle files and try to build I get the error:

```
Unknown source file : TestOnfido/android/app/build/intermediates/res/merged/debug/mipmap-hdpi-v4/ic_launcher.png: error: Duplicate file.
Unknown source file : TestOnfido/android/app/build/intermediates/res/merged/debug/mipmap-hdpi/ic_launcher.png: Original is here. The version qualifier may be implied.

:app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'Library/Android/sdk/build-tools/23.0.1/aapt'' finished with non-zero exit value 1
```

Having done some research it appears this error may be caused by a dependency adding it's own `ic_launcher.png`.

**Comment by rfreitas** [comment]
Hi,

Sorry for the (really) late response.
Could you try to our latest release candidate `0.5.0-rc.1` and let us know if you still see the same problem?
If you do, we can find a way to override the manifest until we put in a proper fix (which should not be too hard)

**Comment by AshleyRudland** [comment]
@rfreitas Thanks for the reply. Unfortunately this still doesn't work. Could you remove ic_launcher.png from the package and redeploy a new version?

Step to repeat (if you want to test before deploying):
1. `react-native init TestOnfidoAndroid`
2. cd TestOnfidoAndroid
3. Add `compile "com.onfido.sdk.capture:onfido-capture-sdk:0.5.0-rc.1"` to `android/app/build.gradle` under dependencies (near line 132)
4. Add `url "https://dl.bintray.com/onfido/maven"` to `android/build.gradle`
5. Connect Android device to your machine or Start Android VM
6. Run `react-native run-android`
7. Comment out references to Onfido in gradle files and run `react-native run-android` again and you will see the build now works

**Comment by rfreitas** [comment]
Hey @AshleyRudland ,

We have a fix in place, we will include it on the next release.

In the meantime I can give you a compiled `aar` file, which you can include directly in order to continue with your testing. Would that be good?

**Comment by AshleyRudland** [comment]
@rfreitas awesome thank you! 

Perfect, I'm assuming I can simply add a path to the `aar` file instead of `compile "com.onfido.sdk.capture:onfido-capture-sdk:0.5.0-rc.1"` in the `bundle.gradle`? 

Add a link on here or send across to ashley.rudland@circularwave.co.uk please. Thanks again!

**Comment by AshleyRudland** [comment]
@rfreitas These build issues have now been resolved with this new version. Thanks a lot! Please close the issue. Just a quick q - `userExited` on `OnfidoResultListener` now requires `ExitCode`, which namespace/package is this from?

**Comment by rfreitas** [comment]
`import com.onfido.android.sdk.capture.ExitCode;`

is the IDE not giving you this import automatically?

**Comment by AshleyRudland** [comment]
No problemo, I found it. Thanks.
