### ISSUE TITLE
OkHttp 3 and restricted API in Android 11

### ISSUE THREAD

**Issue by fgsguedes** [onfido/onfido-android-sdk#100]
In Android 11 some APIs used by OkHttp 3 will be marked as restricted and crash the app is still in use.

As of Onfido Android SDK version 5.5.0, the dependency in OkHttp is version 3.3.0, which will be affected by this behaviour change.

Recommended approach is to use latest OkHttp, which is 4.4.0 as of right now.
And versions 3.12.9 and 3.14.7 were released to back port Android 11 support to 3.x version.

More info can be found here:
https://publicobject.com/2020/02/25/okhttp-restricted-apis/

**Comment by burakeregar** [comment]
Hi, thanks for reporting. 

This is in our backlog. We will update here once it's released.

**Comment by burakeregar** [comment]
Version 7.0.0 has been released now. Please see https://github.com/onfido/onfido-android-sdk/releases/tag/7.0.0
