### ISSUE TITLE
Customising button corners or style

### ISSUE THREAD

**Issue by gunhansancar** [onfido/onfido-android-sdk#102]
#### What was the expected behaviour?
I want to be able to set corner radius for the buttons or setting a style to the buttons that are being used in the SDK views.
#### What happened instead?
There is no way to set it as of yet
#### Version info:
5.5.0
- `onfido-capture-sdk` version: 5.5.0

Also refer to
https://github.com/onfido/onfido-android-sdk/issues/51

**Comment by ramprasad-parajuli** [comment]
Hi @gunhansancar, Thank you for your message. We currently do not support customizing the shape and size of the buttons. We will be looking into allowing the customization in Q2 2020.

**Comment by jamesjara** [comment]
This applies to iOS as well?

**Comment by mdesjardins** [comment]
Any updates on this? We would also like this feature!

**Comment by burakeregar** [comment]
The ability to customize the button border radius, through the onfidoButtonCornerRadius dimension resource has been added with [version 9.3.0](https://github.com/onfido/onfido-android-sdk/releases/tag/9.3.0).
