### ISSUE TITLE
Appcompt support for OnFido library

### ISSUE THREAD

**Issue by nikhilk99** [onfido/onfido-android-sdk#105]

**Comment by gokhanaliccii** [comment]
@nikhilk99 sorry, I couldn't get your point. Could you please clarify the problem?

Do you get an error when you integrate the [latest Onfido android SDK](https://github.com/onfido/onfido-android-sdk/releases/tag/5.5.0) in your SDK?

**Comment by nikhilk99** [comment]
@gokhanaliccii ,

I'm working on **AppCompt** supported the android project. Also, We don't have any plan for androidX (JetPack libraries) migration due to multiple internal dependencies issues.

I have tried to integrate Onfido android SDK in the current AppCompt project but it didn't work.

### Following is my build.gradle:
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'

    implementation 'com.onfido.sdk.capture:onfido-capture-sdk:5.6.0'
    implementation ('com.google.android.gms:play-services-base:17.1.0') {
        exclude group: 'com.android.support' // Add this line only
    }

### Compile-time error 
ERROR: This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
The following AndroidX dependencies are detected: androidx.versionedparcelable:versionedparcelable:1.0.0, androidx.fragment:fragment:1.0.0, androidx.slidingpanelayout:slidingpanelayout:1.0.0, androidx.core:core:1.0.0, androidx.customview:customview:1.0.0, androidx.swiperefreshlayout:swiperefreshlayout:1.0.0, androidx.interpolator:interpolator:1.0.0, androidx.loader:loader:1.0.0, androidx.drawerlayout:drawerlayout:1.0.0, androidx.viewpager:viewpager:1.0.0, androidx.collection:collection:1.0.0, androidx.localbroadcastmanager:localbroadcastmanager:1.0.0, androidx.lifecycle:lifecycle-common:2.0.0, androidx.arch.core:core-common:2.0.0, androidx.annotation:annotation:1.0.0, androidx.legacy:legacy-support-core-ui:1.0.0, androidx.lifecycle:lifecycle-livedata:2.0.0, androidx.lifecycle:lifecycle-viewmodel:2.0.0, androidx.lifecycle:lifecycle-livedata-core:2.0.0, androidx.arch.core:core-runtime:2.0.0, androidx.legacy:legacy-support-core-utils:1.0.0, androidx.documentfile:documentfile:1.0.0, androidx.cursoradapter:cursoradapter:1.0.0, androidx.lifecycle:lifecycle-runtime:2.0.0, androidx.coordinatorlayout:coordinatorlayout:1.0.0, androidx.asynclayoutinflater:asynclayoutinflater:1.0.0, androidx.print:print:1.0.0



_Thanks in advance._

Hope this is helpful to understand the problem statement.

**Comment by gokhanaliccii** [comment]
@nikhilk99 We use `appcompat-v7` library in our SDK we don't use `androidx`. 

I've checked our depency graph whether we have implicit `androidx` dependency but I didn't see
You could check our depency graph:

+--- project :onfido-api-client
|    +--- com.squareup.okhttp3:okhttp:3.12.8
|    |    \--- com.squareup.okio:okio:1.15.0
|    +--- com.squareup.okhttp3:logging-interceptor:3.12.8
|    |    \--- com.squareup.okhttp3:okhttp:3.12.8 (*)
|    +--- com.squareup.retrofit2:retrofit:2.6.4
|    |    \--- com.squareup.okhttp3:okhttp:3.12.0 -> 3.12.8 (*)
|    +--- com.squareup.retrofit2:converter-gson:2.6.4
|    |    +--- com.squareup.retrofit2:retrofit:2.6.4 (*)
|    |    \--- com.google.code.gson:gson:2.8.5
|    +--- com.squareup.retrofit2:adapter-rxjava2:2.6.4
|    |    +--- com.squareup.retrofit2:retrofit:2.6.4 (*)
|    |    \--- io.reactivex.rxjava2:rxjava:2.0.0 -> 2.2.6
|    |         \--- org.reactivestreams:reactive-streams:1.0.2
|    \--- com.google.code.gson:gson:2.6.2 -> 2.8.5
+--- com.android.support:appcompat-v7:27.1.0
|    +--- com.android.support:support-annotations:27.1.0
|    +--- com.android.support:support-core-utils:27.1.0
|    |    +--- com.android.support:support-annotations:27.1.0
|    |    \--- com.android.support:support-compat:27.1.0
|    |         +--- com.android.support:support-annotations:27.1.0
|    |         \--- android.arch.lifecycle:runtime:1.1.0
|    |              +--- android.arch.lifecycle:common:1.1.0
|    |              \--- android.arch.core:common:1.1.0
|    +--- com.android.support:support-fragment:27.1.0
|    |    +--- com.android.support:support-compat:27.1.0 (*)
|    |    +--- com.android.support:support-core-ui:27.1.0
|    |    |    +--- com.android.support:support-annotations:27.1.0
|    |    |    +--- com.android.support:support-compat:27.1.0 (*)
|    |    |    \--- com.android.support:support-core-utils:27.1.0 (*)
|    |    +--- com.android.support:support-core-utils:27.1.0 (*)
|    |    +--- com.android.support:support-annotations:27.1.0
|    |    +--- android.arch.lifecycle:livedata-core:1.1.0
|    |    |    +--- android.arch.lifecycle:common:1.1.0
|    |    |    +--- android.arch.core:common:1.1.0
|    |    |    \--- android.arch.core:runtime:1.1.0
|    |    |         \--- android.arch.core:common:1.1.0
|    |    \--- android.arch.lifecycle:viewmodel:1.1.0
|    +--- com.android.support:support-vector-drawable:27.1.0
|    |    +--- com.android.support:support-annotations:27.1.0
|    |    \--- com.android.support:support-compat:27.1.0 (*)
|    \--- com.android.support:animated-vector-drawable:27.1.0
|         +--- com.android.support:support-vector-drawable:27.1.0 (*)
|         \--- com.android.support:support-core-ui:27.1.0 (*)
+--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50
|    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50
|    \--- org.jetbrains:annotations:13.0
+--- org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.50
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 (*)
+--- com.android.support:design:27.1.0
|    +--- com.android.support:support-v4:27.1.0
|    |    +--- com.android.support:support-compat:27.1.0 (*)
|    |    +--- com.android.support:support-media-compat:27.1.0
|    |    |    +--- com.android.support:support-annotations:27.1.0
|    |    |    \--- com.android.support:support-compat:27.1.0 (*)
|    |    +--- com.android.support:support-core-utils:27.1.0 (*)
|    |    +--- com.android.support:support-core-ui:27.1.0 (*)
|    |    \--- com.android.support:support-fragment:27.1.0 (*)
|    +--- com.android.support:appcompat-v7:27.1.0 (*)
|    +--- com.android.support:recyclerview-v7:27.1.0
|    |    +--- com.android.support:support-annotations:27.1.0
|    |    +--- com.android.support:support-compat:27.1.0 (*)
|    |    \--- com.android.support:support-core-ui:27.1.0 (*)
|    \--- com.android.support:transition:27.1.0
|         +--- com.android.support:support-annotations:27.1.0
|         \--- com.android.support:support-compat:27.1.0 (*)
+--- io.reactivex.rxjava2:rxandroid:2.1.1
|    \--- io.reactivex.rxjava2:rxjava:2.2.6 (*)
+--- com.google.firebase:firebase-ml-vision:20.0.0
|    +--- com.google.android.gms:play-services-auth-base:16.0.0
|    |    +--- com.google.android.gms:play-services-base:16.0.1
|    |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|    |    |    \--- com.google.android.gms:play-services-tasks:16.0.1
|    |    |         \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|    |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    +--- com.google.android.gms:play-services-base:16.0.1 (*)
|    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    +--- com.google.android.gms:play-services-vision:17.0.2
|    |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
|    |    +--- com.google.android.gms:play-services-basement:16.1.0
|    |    \--- com.google.android.gms:play-services-vision-common:[17.0.2] -> 17.0.2
|    |         +--- com.google.android.gms:play-services-base:16.0.1 (*)
|    |         +--- com.google.android.gms:play-services-basement:16.1.0
|    |         +--- com.google.android.gms:play-services-clearcut:16.0.0
|    |         |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
|    |         |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|    |         |    +--- com.google.android.gms:play-services-phenotype:16.0.0
|    |         |    |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
|    |         |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|    |         |    |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    |         |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    |         +--- com.google.android.gms:play-services-flags:16.0.1
|    |         |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
|    |         |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|    |         \--- com.google.android.gms:play-services-phenotype:16.0.0 (*)
|    +--- com.google.android.gms:play-services-vision-common:17.0.2 (*)
|    +--- com.google.android.gms:play-services-vision-image-label:17.0.2
|    |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
|    |    +--- com.google.android.gms:play-services-basement:16.1.0
|    |    \--- com.google.android.gms:play-services-vision-common:[17.0.2] -> 17.0.2 (*)
|    +--- com.google.firebase:firebase-common:17.0.0
|    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|    |    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|    |    \--- com.google.auto.value:auto-value-annotations:1.6.3
|    \--- com.google.firebase:firebase-ml-common:[19.0.0] -> 19.0.0
|         +--- com.google.android.gms:play-services-base:16.0.1 (*)
|         +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|         +--- com.google.android.gms:play-services-clearcut:16.0.0 (*)
|         +--- com.google.android.gms:play-services-phenotype:16.0.0 (*)
|         +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|         +--- com.google.firebase:firebase-common:17.0.0 (*)
|         \--- com.google.firebase:firebase-iid:18.0.0
|              +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|              +--- com.google.android.gms:play-services-stats:16.0.1
|              |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
|              +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
|              +--- com.google.firebase:firebase-common:17.0.0 (*)
|              \--- com.google.firebase:firebase-iid-interop:16.0.1
|                   +--- com.google.android.gms:play-services-base:16.0.1 (*)
|                   \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
+--- junit:junit:4.12
|    \--- org.hamcrest:hamcrest-core:1.3
+--- org.junit.platform:junit-platform-runner:1.1.0
|    +--- org.apiguardian:apiguardian-api:1.0.0
|    +--- org.junit.platform:junit-platform-launcher:1.1.0
|    |    +--- org.apiguardian:apiguardian-api:1.0.0
|    |    \--- org.junit.platform:junit-platform-engine:1.1.0
|    |         +--- org.apiguardian:apiguardian-api:1.0.0
|    |         +--- org.junit.platform:junit-platform-commons:1.1.0
|    |         |    \--- org.apiguardian:apiguardian-api:1.0.0
|    |         \--- org.opentest4j:opentest4j:1.0.0
|    +--- org.junit.platform:junit-platform-suite-api:1.1.0
|    |    +--- org.apiguardian:apiguardian-api:1.0.0
|    |    \--- org.junit.platform:junit-platform-commons:1.1.0 (*)
|    \--- junit:junit:4.12 (*)
+--- org.mockito:mockito-core:2.28.2
|    +--- net.bytebuddy:byte-buddy:1.9.10
|    +--- net.bytebuddy:byte-buddy-agent:1.9.10
|    \--- org.objenesis:objenesis:2.6
+--- org.jetbrains.kotlin:kotlin-test-junit:1.3.50
|    \--- junit:junit:4.12 (*)
+--- com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0
|    \--- org.mockito:mockito-core:2.23.0 -> 2.28.2 (*)
+--- org.jetbrains.spek:spek-api:1.1.5
+--- org.jetbrains.spek:spek-junit-platform-engine:1.1.5
|    \--- org.jetbrains.spek:spek-api:1.1.5
+--- org.json:json:20140107
+--- org.skyscreamer:jsonassert:1.4.0
|    \--- com.vaadin.external.google:android-json:0.0.20131108.vaadin1
\--- org.jetbrains.kotlin:kotlin-reflect:1.3.50
     \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 (*)

**Comment by nikhilk99** [comment]
@gokhanaliccii  But at my end, it looks like following:

\--- com.onfido.sdk.capture:onfido-capture-sdk-core:5.6.0
     +--- com.onfido.api.client:onfido-api-client:5.6.0
     |    +--- com.squareup.okhttp3:okhttp:3.12.8
     |    |    \--- com.squareup.okio:okio:1.15.0
     |    +--- com.squareup.okhttp3:logging-interceptor:3.12.8
     |    |    \--- com.squareup.okhttp3:okhttp:3.12.8 (*)
     |    +--- com.squareup.retrofit2:retrofit:2.6.4
     |    |    \--- com.squareup.okhttp3:okhttp:3.12.0 -> 3.12.8 (*)
     |    +--- com.squareup.retrofit2:converter-gson:2.6.4
     |    |    +--- com.squareup.retrofit2:retrofit:2.6.4 (*)
     |    |    \--- com.google.code.gson:gson:2.8.5
     |    +--- com.squareup.retrofit2:adapter-rxjava2:2.6.4
     |    |    +--- com.squareup.retrofit2:retrofit:2.6.4 (*)
     |    |    \--- io.reactivex.rxjava2:rxjava:2.0.0 -> 2.2.6
     |    |         \--- org.reactivestreams:reactive-streams:1.0.2
     |    \--- com.google.code.gson:gson:2.6.2 -> 2.8.5
     +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50
     |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50
     |    \--- org.jetbrains:annotations:13.0
     +--- org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.50
     |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 (*)
     +--- io.reactivex.rxjava2:rxandroid:2.1.1
     |    \--- io.reactivex.rxjava2:rxjava:2.2.6 (*)
     +--- com.google.firebase:firebase-ml-vision:20.0.0
     |    +--- com.google.android.gms:play-services-auth-base:16.0.0
     |    |    +--- com.google.android.gms:play-services-base:16.0.1
     |    |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0
     |    |    |    |    \--- androidx.legacy:legacy-support-v4:1.0.0
     |    |    |    |         +--- androidx.core:core:1.0.0
     |    |    |    |         |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    +--- androidx.collection:collection:1.0.0
     |    |    |    |         |    |    \--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0
     |    |    |    |         |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0
     |    |    |    |         |    |    |    \--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    +--- androidx.arch.core:core-common:2.0.0
     |    |    |    |         |    |    |    \--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    \--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    \--- androidx.versionedparcelable:versionedparcelable:1.0.0
     |    |    |    |         |         +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |         \--- androidx.collection:collection:1.0.0 (*)
     |    |    |    |         +--- androidx.media:media:1.0.0
     |    |    |    |         |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    +--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    \--- androidx.versionedparcelable:versionedparcelable:1.0.0 (*)
     |    |    |    |         +--- androidx.legacy:legacy-support-core-utils:1.0.0
     |    |    |    |         |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    +--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    +--- androidx.documentfile:documentfile:1.0.0
     |    |    |    |         |    |    \--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    +--- androidx.loader:loader:1.0.0
     |    |    |    |         |    |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    +--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    |    +--- androidx.lifecycle:lifecycle-livedata:2.0.0
     |    |    |    |         |    |    |    +--- androidx.arch.core:core-runtime:2.0.0
     |    |    |    |         |    |    |    |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    |    |    \--- androidx.arch.core:core-common:2.0.0 (*)
     |    |    |    |         |    |    |    +--- androidx.lifecycle:lifecycle-livedata-core:2.0.0
     |    |    |    |         |    |    |    |    +--- androidx.lifecycle:lifecycle-common:2.0.0 (*)
     |    |    |    |         |    |    |    |    +--- androidx.arch.core:core-common:2.0.0 (*)
     |    |    |    |         |    |    |    |    \--- androidx.arch.core:core-runtime:2.0.0 (*)
     |    |    |    |         |    |    |    \--- androidx.arch.core:core-common:2.0.0 (*)
     |    |    |    |         |    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0
     |    |    |    |         |    |         \--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    +--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
     |    |    |    |         |    |    \--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    \--- androidx.print:print:1.0.0
     |    |    |    |         |         \--- androidx.annotation:annotation:1.0.0
     |    |    |    |         +--- androidx.legacy:legacy-support-core-ui:1.0.0
     |    |    |    |         |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    +--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
     |    |    |    |         |    +--- androidx.customview:customview:1.0.0
     |    |    |    |         |    |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    \--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    +--- androidx.viewpager:viewpager:1.0.0
     |    |    |    |         |    |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    +--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    |    \--- androidx.customview:customview:1.0.0 (*)
     |    |    |    |         |    +--- androidx.coordinatorlayout:coordinatorlayout:1.0.0
     |    |    |    |         |    |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    +--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    |    \--- androidx.customview:customview:1.0.0 (*)
     |    |    |    |         |    +--- androidx.drawerlayout:drawerlayout:1.0.0
     |    |    |    |         |    |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    +--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    |    \--- androidx.customview:customview:1.0.0 (*)
     |    |    |    |         |    +--- androidx.slidingpanelayout:slidingpanelayout:1.0.0
     |    |    |    |         |    |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    +--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    |    \--- androidx.customview:customview:1.0.0 (*)
     |    |    |    |         |    +--- androidx.interpolator:interpolator:1.0.0
     |    |    |    |         |    |    \--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    +--- androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
     |    |    |    |         |    |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    +--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    |    \--- androidx.interpolator:interpolator:1.0.0 (*)
     |    |    |    |         |    +--- androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
     |    |    |    |         |    |    +--- androidx.annotation:annotation:1.0.0
     |    |    |    |         |    |    \--- androidx.core:core:1.0.0 (*)
     |    |    |    |         |    \--- androidx.cursoradapter:cursoradapter:1.0.0
     |    |    |    |         |         \--- androidx.annotation:annotation:1.0.0
     |    |    |    |         \--- androidx.fragment:fragment:1.0.0
     |    |    |    |              +--- androidx.core:core:1.0.0 (*)
     |    |    |    |              +--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
     |    |    |    |              +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
     |    |    |    |              +--- androidx.annotation:annotation:1.0.0
     |    |    |    |              +--- androidx.loader:loader:1.0.0 (*)
     |    |    |    |              \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0 (*)
     |    |    |    \--- com.google.android.gms:play-services-tasks:16.0.1
     |    |    |         \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
     |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
     |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
     |    +--- com.google.android.gms:play-services-vision:17.0.2
     |    |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
     |    |    +--- com.google.android.gms:play-services-basement:16.1.0 (*)
     |    |    \--- com.google.android.gms:play-services-vision-common:[17.0.2] -> 17.0.2
     |    |         +--- com.google.android.gms:play-services-base:16.0.1 (*)
     |    |         +--- com.google.android.gms:play-services-basement:16.1.0 (*)
     |    |         +--- com.google.android.gms:play-services-clearcut:16.0.0
     |    |         |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
     |    |         |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    |         |    +--- com.google.android.gms:play-services-phenotype:16.0.0
     |    |         |    |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
     |    |         |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    |         |    |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
     |    |         |    \--- com.google.android.gms:play-services-tasks:16.0.1 (*)
     |    |         +--- com.google.android.gms:play-services-flags:16.0.1
     |    |         |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
     |    |         |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    |         \--- com.google.android.gms:play-services-phenotype:16.0.0 (*)
     |    +--- com.google.android.gms:play-services-vision-common:17.0.2 (*)
     |    +--- com.google.android.gms:play-services-vision-image-label:17.0.2
     |    |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
     |    |    +--- com.google.android.gms:play-services-basement:16.1.0 (*)
     |    |    \--- com.google.android.gms:play-services-vision-common:[17.0.2] -> 17.0.2 (*)
     |    +--- com.google.firebase:firebase-common:17.0.0
     |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    |    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
     |    |    \--- com.google.auto.value:auto-value-annotations:1.6.3
     |    +--- com.google.firebase:firebase-ml-common:[19.0.0] -> 19.0.0
     |    |    +--- com.google.android.gms:play-services-base:16.0.1 (*)
     |    |    +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    |    +--- com.google.android.gms:play-services-clearcut:16.0.0 (*)
     |    |    +--- com.google.android.gms:play-services-phenotype:16.0.0 (*)
     |    |    +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
     |    |    +--- com.google.firebase:firebase-common:17.0.0 (*)
     |    |    \--- com.google.firebase:firebase-iid:18.0.0
     |    |         +--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    |         +--- com.google.android.gms:play-services-stats:16.0.1
     |    |         |    \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    |         +--- com.google.android.gms:play-services-tasks:16.0.1 (*)
     |    |         +--- com.google.firebase:firebase-common:17.0.0 (*)
     |    |         \--- com.google.firebase:firebase-iid-interop:16.0.1
     |    |              +--- com.google.android.gms:play-services-base:16.0.1 (*)
     |    |              \--- com.google.android.gms:play-services-basement:16.0.1 -> 16.1.0 (*)
     |    \--- androidx.exifinterface:exifinterface:1.0.0
     |         \--- androidx.annotation:annotation:1.0.0
     +--- androidx.appcompat:appcompat:1.0.0
     |    +--- androidx.annotation:annotation:1.0.0
     |    +--- androidx.core:core:1.0.0 (*)
     |    +--- androidx.collection:collection:1.0.0 (*)
     |    +--- androidx.cursoradapter:cursoradapter:1.0.0 (*)
     |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
     |    +--- androidx.fragment:fragment:1.0.0 (*)
     |    +--- androidx.vectordrawable:vectordrawable:1.0.0
     |    |    +--- androidx.annotation:annotation:1.0.0
     |    |    \--- androidx.core:core:1.0.0 (*)
     |    \--- androidx.vectordrawable:vectordrawable-animated:1.0.0
     |         +--- androidx.vectordrawable:vectordrawable:1.0.0 (*)
     |         \--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
     \--- com.google.android.material:material:1.0.0
          +--- androidx.annotation:annotation:1.0.0
          +--- androidx.core:core:1.0.0 (*)
          +--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
          +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
          +--- androidx.fragment:fragment:1.0.0 (*)
          +--- androidx.transition:transition:1.0.0
          |    +--- androidx.annotation:annotation:1.0.0
          |    \--- androidx.core:core:1.0.0 (*)
          +--- androidx.appcompat:appcompat:1.0.0 (*)
          +--- androidx.cardview:cardview:1.0.0
          |    \--- androidx.annotation:annotation:1.0.0
          \--- androidx.recyclerview:recyclerview:1.0.0
               +--- androidx.annotation:annotation:1.0.0
               +--- androidx.core:core:1.0.0 (*)
               \--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)

But now I have tried to download the new dependency and found that it taking appcompt libraries.
Still, wondering how this happened?

**Comment by nikhilk99** [comment]
@gokhanaliccii 

Also, I'm using Onfido 5.6.0 library in **Cordova** project.

My Cordova project detail:
1. Android platform version: 8.1.0
2. CompileSDK version: 28 

I'm getting following error:

**Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver**

As a solution, people suggesting for androidX migration but I don't wanna go fo that.

If you wanna reproduce the same issue then use the following step:
1. create cordova project 
2. add platform android@8.1.0
3. Add Onfido library in build.gradle
4. try to run the project

**Comment by gokhanaliccii** [comment]
@nikhilk99 Sorry for the delay in responding to your last message

I've re-checked your dependency graph and realized that androidx dependency comes from  **`play-services-base`** dependency 

```
implementation ('com.google.android.gms:play-services-base:17.1.0') {
    exclude group: 'com.android.support' // Add this line only
}
```

The `play-services-base` library has been migrated to androidx with [17.0.0 release ](https://developers.google.com/android/guides/releases#june_17_2019)

If you prefer not to migrate androidx, I'd suggest using a previous version of **play-services-base** like [16.1.0](https://mvnrepository.com/artifact/com.google.android.gms/play-services-base)

**Comment by nikhilk99** [comment]
@gokhanaliccii Yes. It worked. Thank you for the help.
