### ISSUE TITLE
 cannot access CountryCode

### ISSUE THREAD

**Issue by jamesjara** [onfido/onfido-android-sdk#107]
```

import com.onfido.android.sdk.capture.utils.CountryCode;

OnfidoModule.java:25: error: cannot access CountryCode
import com.onfido.android.sdk.capture.utils.CountryCode;
```
Where we can get the latest deps?

**Comment by gokhanaliccii** [comment]
@jamesjara Could you please provide more information to diagnose the problem

#### Version info:

- `onfido-capture-sdk` version:
- Android API version(s):

- `compileSdkVersion`:
- `targetSdkVersion`:
- `minSdkVersion`:
- Support library version (if applicable):

#### Onfido Flow initialization code:

**Comment by jamesjara** [comment]
Using the latest lib
We can access country code with 
```
import com.onfido.android.sdk.capture.utils.CountryCode;```
thanks @gokhanaliccii
