### ISSUE TITLE
Api v2

### ISSUE THREAD

**Issue by Bardiamist** [onfido/onfido-android-sdk#108]
It's possible to use api v2 with sdk 5.6.0? I see "Connection lost" on documents upload when use sdk token.

#### What was the expected behaviour?
Documents should be uploaded and next (face) step started.

#### What happened instead?
I see "Connection lost" on documents upload when use sdk token.

#### Version info:

- `onfido-capture-sdk` version: 5.6.0
- Android API version(s): 27

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 21

#### Steps to reproduce:
1. Generate SDK token [as described here ](https://github.com/onfido/onfido-sdk-ui#3-generating-an-sdk-token)
2. Pass this token to `withSDKToken` method.
3. Try to upload passport

#### Onfido Flow initialization code:
```
OnfidoConfig onfidoConfig = OnfidoConfig.builder(currentActivity)
                    .withSDKToken(token)
                    .build();
client.startActivityForResult(currentActivity, 1, onfidoConfig);
```

#### Issue severity information (number of users/crashes if applicable):
[Result screenshot](https://imgur.com/9FFKjmM)

#### Additional LogCat output:
```
D/OkHttp: --> POST https://api.onfido.com/v2/documents (159951-byte body)
D/OkHttp: <-- 401 https://api.onfido.com/v2/documents (1002ms, 133-byte body)
```

**Comment by Bardiamist** [comment]
Same result with:
```
OnfidoConfig onfidoConfig = OnfidoConfig.builder(currentActivity)
                    .withApplicant(applicantId)
                    .withToken(token)
                    .build();
client.startActivityForResult(currentActivity, 1, onfidoConfig);
```

**Comment by gokhanaliccii** [comment]
@Bardiamist It seems related to `sdkToken` creation problem, could you please check https://github.com/onfido/onfido-android-sdk/issues/87

**Comment by badikumar** [comment]
How do we tell the latest SDK to use the v2 routes and not the v3 routes? The 401 message seems to suggest it is hitting a v3 route. Our backend that returns the SDK token is using v2 API to Generate the token and send back to the mobile app.

Also FYI - we are using the same live/sandbox token to generate the SDK tokens for both mobile app and our website. (For the website, we use Onfido-SDK-UI which does not have the “applicationid “ Parma while generating the tokens.

**Comment by badikumar** [comment]
@gokhanaliccii - you said:

“To create sdkToken firstly you need to create applicantId then you need create sdkToken. You will also need your applicationId, which you can find your in your app/build.gradle file.”

But we create the SDK token on the backend server as documented in Onfido-SDK-UI for the web.

Are you suggesting that the SDK token for mobile app needs to be generated differently? How?

Lastly, we would like to stick to v2. Can you point to how the SDK token are created in v2 API? Can we send the “applicationid” field to it?

**Comment by Bardiamist** [comment]
Yes, reason in sdk token creation. Need to send `application_id` instead `referrer`.
