### ISSUE TITLE
.withApplicant(applicantId) is deprecated 

### ISSUE THREAD

**Issue by jamesjara** [onfido/onfido-android-sdk#111]
Hi guys, so if .withApplicant(applicantId) is deprecated how i will setup the applicant id? 

![image](https://user-images.githubusercontent.com/780219/77008451-cb16ca00-692b-11ea-8bf1-debe7fb8205f.png)

**Comment by burakeregar** [comment]
Hi @jamesjara, if you are using `SDKToken` you do not need to pass applicant id. Please refer to [README](https://github.com/onfido/onfido-android-sdk#4-configuring-sdk-with-tokens.) for the implementation guide. You can also check out our [sample app](https://github.com/onfido/onfido-android-sdk/blob/master/sample-app/app/src/main/java/com/onfido/android/app/sample/MainActivity.java) for more information.

**Comment by jamesjara** [comment]
I see, thanks
