### ISSUE TITLE
change android assets cdn

### ISSUE THREAD

**Issue by jamesjara** [onfido/onfido-android-sdk#112]
Hi guys, 

I believe it would be very awesome if we can set the the CDN server for the assets, so for example my client wants to change the mp4 source, so if you allow us to change the CDN we could upload the mp4's files for example

https://assets.onfido.com/mobile-sdk-assets/android/v2/index.json  
https://assets.onfido.com/mobile-sdk-assets/android/v2/liveness_intro_2.mp4 https://assets.onfido.com/mobile-sdk-assets/android/v2/liveness_intro_2.mp4

**Comment by seewah** [comment]
Sorry this is not possible at the moment, but we will add this idea to our backlog. thanks
