### ISSUE TITLE
NullPointerException in CameraSourcePreview.startVideo in v5.5.0

### ISSUE THREAD

**Issue by kzaikin** [onfido/onfido-android-sdk#113]
#### What was the expected behaviour?
No crashes from Onfido

#### What happened instead?
A crash
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void com.onfido.android.sdk.capture.ui.camera.face.CameraSource.startVideo(com.onfido.android.sdk.capture.ui.camera.face.MediaCaptureCallback)' on a null object reference
com.onfido.android.sdk.capture.ui.camera.face.CameraSourcePreview.startVideo (Unknown Source:2)
com.onfido.android.sdk.capture.ui.camera.CaptureActivity.startVideoCapture (Unknown Source:72)
com.onfido.android.sdk.capture.ui.camera.CaptureActivity.access$startVideoCapture
com.onfido.android.sdk.capture.ui.camera.CaptureActivity$onFaceDetected$$inlined$let$lambda$1.run (Unknown Source:16)
android.os.Handler.handleCallback (Handler.java:873)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)

#### Version info:

- `onfido-capture-sdk` version: 5.5.0
- Android API version(s):

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 23
- Support library version (if applicable):
- `androidxCore`                 : "1.1.0",
- `androidxAppcompat`            : "1.0.2",

#### Steps to reproduce:
Unknown - we've got a crash from production

#### Onfido Flow initialization code:
    val steps = arrayOf(
      CaptureScreenStep(documentType.toOnfidoDocumentType(), toOnfidoCountry(nationality)),
      FaceCaptureStep(FaceCaptureVariantVideo())
    )
    val config = OnfidoConfig.builder(context!!)
      .withToken(applicantConfig.mobileSdkToken)
      .withApplicant(applicantConfig.applicantId)
      .withCustomFlow(steps)
      .build()
    val intent = onfido.createIntent(config)
    startActivityForResult(intent, REQUEST_CODE_ONFIDO)

#### Issue severity information (number of users/crashes if applicable):
1 crash per ~1000 Onfido starts

#### Other useful info:
Device
Brand: samsung
Model: Galaxy A70
Orientation: Portrait
RAM free: 1.47 GB
Disk free: 71.8 GB

Operating System
Version: 9
Orientation: Portrait
Rooted: No

**Comment by burakeregar** [comment]
Hi @kzaikin 

Thanks for the reporting the issue. 

1. Are you able to reproduce the issue?
2. Can you please share more information around devices that crash?
3. Have you used other versions on productions before/after? If so, do you get the same crash on those versions?

**Comment by burakeregar** [comment]
Even though we are not able to reproduce the issue on our side, we have made some fixes and improvements which we expect it to fix this issue. We are planning to release the fix with the next version.

**Comment by gokhanaliccii** [comment]
Thanks for your patience, the [7.2.0](https://github.com/onfido/onfido-android-sdk/releases/tag/7.2.0) has been released please let us know if the issue still exists on 7.2.0
