### ISSUE TITLE
Singapore native country name incorrect

### ISSUE THREAD

**Issue by karunais13** [onfido/onfido-android-sdk#115]
#### What was the expected behavior?
Show the proper country name for Singapore at the header.
#### What happened instead?
Singapore country name at header show in chine character "新加坡".

#### Version info:

- `onfido-capture-sdk` version: 5.6.0
- Android API version(s): 28

- `compileSdkVersion`:5.6.0
- `targetSdkVersion`: 5.6.0
- `minSdkVersion`: 5.6.0
- Support library version (if applicable):

#### Steps to reproduce:
When user select country after choose document type.

#### Other useful info:
![image](https://user-images.githubusercontent.com/18754736/77387930-b45bf180-6dc9-11ea-8168-ebb4b357d602.png)

**Comment by seewah** [comment]
thanks for the feedback. As singapore has multi supported language, and english seems to be the one recognised by most people, we will just show "singapore" going forward. Does that make sense to you?

**Comment by karunais13** [comment]
Yes. It will better to show as 'Singapore'. Thank you. May I know when this fix will be released ?

**Comment by DennisLit** [comment]
Also interested in knowing when this is planned to be fixed.

**Comment by burakeregar** [comment]
Closing the issue as it has already been fixed as part of version 7.3.0
