### ISSUE TITLE
Onfido started to lose documents after update to 5.6.0 version

### ISSUE THREAD

**Issue by bracadabra** [onfido/onfido-android-sdk#120]
#### What was the expected behaviour?
Documents are uploaded to Onfido server and fetched back

#### What happened instead?
Onfido returned success status in sdk instead of 422 error on attempt to run check

#### Version info:

- `onfido-capture-sdk` version: 5.6.0
- Android API version(s):

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 21
- Support library version (if applicable): 1.1.0

#### Steps to reproduce:

1. Start to capture documents
2. In `userCompleted` make a request to our backend
3. Backend makes a request to Onfido to run a check:
```
POST - https://api.onfido.com/v2/applicants/95c5bb09-de51-43a3-986f-064e81a6a7e7/checks 
Response status 422, 
Body {"error":{"type":"validation_error","message":"There was a validation error on this request","fields":{"applicant":["You must provide the necessary documents to be able to proceed with this check. Please refer to our documentation for supported documents.","You must provide the necessary documents to be able to proceed with this check. Please refer to our documentation for supported documents."]}}}
```

The number of these errors started to grow after updating from 5.3.1 to 5.6.0 version.

#### Onfido Flow initialization code:
-
#### Issue severity information (number of users/crashes if applicable):
-
#### Additional LogCat output:
-
#### Other useful info:
-

**Comment by nuriking** [comment]
this error has in 5.4.0 version

**Comment by bracadabra** [comment]
@nuriking have you found any workaround except downgrading library version?

**Comment by nuriking** [comment]
@bracadabra no, i think is api bugs

**Comment by burakeregar** [comment]
This doesn't seem to be an SDK issue. I can see various failure reasons for applicantId`95c5bb09-de51-43a3-986f-064e81a6a7e7` due to different validation errors in the API request. Please refer to our [documentation](https://documentation.onfido.com/) for the required and expected fields in the API calls. Please make sure that you are referring to the correct API version.

**Comment by bracadabra** [comment]
Hi @burakeregar, thank you for the response, but could you clarify what errors and API requests you are talking about?

**Comment by bracadabra** [comment]
@burakeregar and we have such logs on the backend:

> Here is couple of RQ/RS to Onfid which hopefuly will give some light about the issue.
> Recently it looks like there was a change about how Onfido SDK or BE attached type for RESIDENCE_PERMIT docs.
> from:
>   "type": "unknown"
> to:
>   "type": "residence_permit"
> This change corelates with the time we started to observe HTTP 422 errors when creating checks for residence permit.
> ### Documents contain only "residence_permit"
> https://api.onfido.com/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/
> Authorization: Token
> ==>
> {
>   "documents": [
>     {
>       "id": "6a074723-0acd-4a87-a5a2-08480e8951f7",
>       "created_at": "2020-04-16T23:09:42Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 270702,
>       "type": "residence_permit",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/6a074723-0acd-4a87-a5a2-08480e8951f7",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/6a074723-0acd-4a87-a5a2-08480e8951f7/download"
>     },
>     {
>       "id": "cdbcac87-2147-46bb-a07f-8321dd9bd967",
>       "created_at": "2020-04-16T23:09:34Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 257494,
>       "type": "residence_permit",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/cdbcac87-2147-46bb-a07f-8321dd9bd967",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/cdbcac87-2147-46bb-a07f-8321dd9bd967/download"
>     },
>     {
>       "id": "0ff59e73-e2ed-4a2e-8796-152a06e00b04",
>       "created_at": "2020-04-16T23:08:09Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 708772,
>       "type": "residence_permit",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/0ff59e73-e2ed-4a2e-8796-152a06e00b04",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/0ff59e73-e2ed-4a2e-8796-152a06e00b04/download"
>     },
>     {
>       "id": "81b45027-a879-4cf9-bbf2-4737f246f5c4",
>       "created_at": "2020-04-16T23:07:42Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 740744,
>       "type": "residence_permit",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/81b45027-a879-4cf9-bbf2-4737f246f5c4",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/81b45027-a879-4cf9-bbf2-4737f246f5c4/download"
>     },
>     {
>       "id": "426e70b9-5bcf-4cce-83ed-72432fa0488f",
>       "created_at": "2020-04-16T23:05:42Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 241898,
>       "type": "residence_permit",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/426e70b9-5bcf-4cce-83ed-72432fa0488f",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/426e70b9-5bcf-4cce-83ed-72432fa0488f/download"
>     },
>     {
>       "id": "732a4045-c4a8-48d8-b0a8-515054aa1b32",
>       "created_at": "2020-04-16T23:05:32Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 231378,
>       "type": "residence_permit",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/732a4045-c4a8-48d8-b0a8-515054aa1b32",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/732a4045-c4a8-48d8-b0a8-515054aa1b32/download"
>     },
>     {
>       "id": "bc5063ed-a958-4c2b-9720-da3133c98631",
>       "created_at": "2020-04-16T22:28:14Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 235477,
>       "type": "residence_permit",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/bc5063ed-a958-4c2b-9720-da3133c98631",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/bc5063ed-a958-4c2b-9720-da3133c98631/download"
>     },
>     {
>       "id": "f4b9fc9f-2c95-4834-bb4a-12bad0abf74b",
>       "created_at": "2020-04-16T22:28:06Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 201882,
>       "type": "residence_permit",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/f4b9fc9f-2c95-4834-bb4a-12bad0abf74b",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/f4b9fc9f-2c95-4834-bb4a-12bad0abf74b/download"
>     }
>   ]
> }
> ### ==> Cannot create check for those documents. This is the issue we have.
> POST https://api.onfido.com/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/checks
> Authorization: Token
> Content-Type: application/json
> {
>   "type": "express",
>   "async": true,
>   "reports": [
>     {
>       "name": "facial_similarity"
>     },
>     {
>       "name": "document",
>       "options": [
>         {
>           "name": "document_address_information"
>         }
>       ]
>     }
>   ]
> }
> ==>
> {"error":{"type":"validation_error","message":"There was a validation error on this request","fields":{"applicant":["You must provide the necessary documents to be able to proceed with this check. Please refer to our documentation for supported documents.","You must provide the necessary documents to be able to proceed with this check. Please refer to our documentation for supported documents."]}}}
> ### For comparison a case when this works when documents contain an entry other the "residence_permit"
> https://api.onfido.com/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/
> Authorization: Token
> ==>
> {
>   "documents": [
>     {
>       "id": "2ccdf115-730c-4789-b95c-87bdd4abef2f",
>       "created_at": "2020-04-16T22:15:38Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 268771,
>       "type": "driving_licence",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/2ccdf115-730c-4789-b95c-87bdd4abef2f",
>       "download_href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/2ccdf115-730c-4789-b95c-87bdd4abef2f/download"
>     },
>     {
>       "id": "357abccf-7b5b-4f66-a04c-121516583536",
>       "created_at": "2020-04-16T22:15:29Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 287034,
>       "type": "driving_licence",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/357abccf-7b5b-4f66-a04c-121516583536",
>       "download_href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/357abccf-7b5b-4f66-a04c-121516583536/download"
>     },
>     {
>       "id": "a634a434-f3f6-4452-a2aa-039a0f21da07",
>       "created_at": "2020-04-16T21:41:12Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 351840,
>       "type": "residence_permit",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/a634a434-f3f6-4452-a2aa-039a0f21da07",
>       "download_href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/a634a434-f3f6-4452-a2aa-039a0f21da07/download"
>     },
>     {
>       "id": "5d1045b7-4510-4ea1-9002-563d91db381c",
>       "created_at": "2020-04-16T21:41:03Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 356761,
>       "type": "residence_permit",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/5d1045b7-4510-4ea1-9002-563d91db381c",
>       "download_href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/5d1045b7-4510-4ea1-9002-563d91db381c/download"
>     }
>   ]
> }
> ### Then check can be created - issue is not reproduced
> POST https://api.onfido.com/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/checks
> Authorization: Token
> Content-Type: application/json
> {
>   "type": "express",
>   "async": true,
>   "reports": [
>     {
>       "name": "facial_similarity"
>     },
>     {
>       "name": "document",
>       "options": [
>         {
>           "name": "document_address_information"
>         }
>       ]
>     }
>   ]
> }
> ==>
> {
>   "id": "c9b87da9-5404-424b-acf7-399f634363ab",
>   "created_at": "2020-04-17T07:40:04Z",
>   "status": "in_progress",
>   "redirect_uri": null,
>   "result": null,
>   "sandbox": true,
>   "tags": [],
>   "results_uri": "https://dashboard.onfido.com/checks/c9b87da9-5404-424b-acf7-399f634363ab",
>   "form_uri": null,
>   "paused": false,
>   "type": "express",
>   "report_type_groups": [
>     "4576"
>   ],
>   "download_uri": "https://onfido.com/dashboard/pdf/information_requests/64485103",
>   "href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/checks/c9b87da9-5404-424b-acf7-399f634363ab",
>   "reports": [
>     {
>       "created_at": "2020-04-17T07:40:04Z",
>       "documents": [
>         {
>           "id": "357abccf-7b5b-4f66-a04c-121516583536"
>         },
>         {
>           "id": "2ccdf115-730c-4789-b95c-87bdd4abef2f"
>         }
>       ],
>       "href": "/v2/checks/c9b87da9-5404-424b-acf7-399f634363ab/reports/0ed4f15b-0b85-4574-b0eb-a96d176b6b97",
>       "id": "0ed4f15b-0b85-4574-b0eb-a96d176b6b97",
>       "name": "document",
>       "properties": {},
>       "result": null,
>       "status": "awaiting_data",
>       "sub_result": null,
>       "variant": "standard",
>       "breakdown": {}
>     },
>     {
>       "created_at": "2020-04-17T07:40:04Z",
>       "documents": [],
>       "href": "/v2/checks/c9b87da9-5404-424b-acf7-399f634363ab/reports/55d977a9-5c37-4b04-b0b1-9879c3bf0c03",
>       "id": "55d977a9-5c37-4b04-b0b1-9879c3bf0c03",
>       "name": "facial_similarity",
>       "properties": {},
>       "result": null,
>       "status": "awaiting_data",
>       "sub_result": null,
>       "variant": "standard",
>       "breakdown": {}
>     }
>   ],
>   "version": "2.0"
> }

**Comment by bracadabra** [comment]
@burakeregar and we have such logs on the backend:

> Here is couple of RQ/RS to Onfid which hopefuly will give some light about the issue.
> Recently it looks like there was a change about how Onfido SDK or BE attached type for RESIDENCE_PERMIT docs.
> from:
>   "type": "unknown"
> to:
>   "type": "residence_permit"
> This change corelates with the time we started to observe HTTP 422 errors when creating checks for residence permit.
> ### Documents contain only "residence_permit"
> https://api.onfido.com/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/
> Authorization: Token
> ==>
> {
>   "documents": [
>     {
>       "id": "6a074723-0acd-4a87-a5a2-08480e8951f7",
>       "created_at": "2020-04-16T23:09:42Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 270702,
>       "type": "residence_permit",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/6a074723-0acd-4a87-a5a2-08480e8951f7",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/6a074723-0acd-4a87-a5a2-08480e8951f7/download"
>     },
>     {
>       "id": "cdbcac87-2147-46bb-a07f-8321dd9bd967",
>       "created_at": "2020-04-16T23:09:34Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 257494,
>       "type": "residence_permit",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/cdbcac87-2147-46bb-a07f-8321dd9bd967",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/cdbcac87-2147-46bb-a07f-8321dd9bd967/download"
>     },
>     {
>       "id": "0ff59e73-e2ed-4a2e-8796-152a06e00b04",
>       "created_at": "2020-04-16T23:08:09Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 708772,
>       "type": "residence_permit",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/0ff59e73-e2ed-4a2e-8796-152a06e00b04",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/0ff59e73-e2ed-4a2e-8796-152a06e00b04/download"
>     },
>     {
>       "id": "81b45027-a879-4cf9-bbf2-4737f246f5c4",
>       "created_at": "2020-04-16T23:07:42Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 740744,
>       "type": "residence_permit",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/81b45027-a879-4cf9-bbf2-4737f246f5c4",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/81b45027-a879-4cf9-bbf2-4737f246f5c4/download"
>     },
>     {
>       "id": "426e70b9-5bcf-4cce-83ed-72432fa0488f",
>       "created_at": "2020-04-16T23:05:42Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 241898,
>       "type": "residence_permit",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/426e70b9-5bcf-4cce-83ed-72432fa0488f",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/426e70b9-5bcf-4cce-83ed-72432fa0488f/download"
>     },
>     {
>       "id": "732a4045-c4a8-48d8-b0a8-515054aa1b32",
>       "created_at": "2020-04-16T23:05:32Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 231378,
>       "type": "residence_permit",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/732a4045-c4a8-48d8-b0a8-515054aa1b32",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/732a4045-c4a8-48d8-b0a8-515054aa1b32/download"
>     },
>     {
>       "id": "bc5063ed-a958-4c2b-9720-da3133c98631",
>       "created_at": "2020-04-16T22:28:14Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 235477,
>       "type": "residence_permit",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/bc5063ed-a958-4c2b-9720-da3133c98631",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/bc5063ed-a958-4c2b-9720-da3133c98631/download"
>     },
>     {
>       "id": "f4b9fc9f-2c95-4834-bb4a-12bad0abf74b",
>       "created_at": "2020-04-16T22:28:06Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 201882,
>       "type": "residence_permit",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/f4b9fc9f-2c95-4834-bb4a-12bad0abf74b",
>       "download_href": "/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/documents/f4b9fc9f-2c95-4834-bb4a-12bad0abf74b/download"
>     }
>   ]
> }
> ### ==> Cannot create check for those documents. This is the issue we have.
> POST https://api.onfido.com/v2/applicants/70f2e34f-7d50-4f45-8683-36f0dbca4ac8/checks
> Authorization: Token
> Content-Type: application/json
> {
>   "type": "express",
>   "async": true,
>   "reports": [
>     {
>       "name": "facial_similarity"
>     },
>     {
>       "name": "document",
>       "options": [
>         {
>           "name": "document_address_information"
>         }
>       ]
>     }
>   ]
> }
> ==>
> {"error":{"type":"validation_error","message":"There was a validation error on this request","fields":{"applicant":["You must provide the necessary documents to be able to proceed with this check. Please refer to our documentation for supported documents.","You must provide the necessary documents to be able to proceed with this check. Please refer to our documentation for supported documents."]}}}
> ### For comparison a case when this works when documents contain an entry other the "residence_permit"
> https://api.onfido.com/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/
> Authorization: Token
> ==>
> {
>   "documents": [
>     {
>       "id": "2ccdf115-730c-4789-b95c-87bdd4abef2f",
>       "created_at": "2020-04-16T22:15:38Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 268771,
>       "type": "driving_licence",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/2ccdf115-730c-4789-b95c-87bdd4abef2f",
>       "download_href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/2ccdf115-730c-4789-b95c-87bdd4abef2f/download"
>     },
>     {
>       "id": "357abccf-7b5b-4f66-a04c-121516583536",
>       "created_at": "2020-04-16T22:15:29Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 287034,
>       "type": "driving_licence",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/357abccf-7b5b-4f66-a04c-121516583536",
>       "download_href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/357abccf-7b5b-4f66-a04c-121516583536/download"
>     },
>     {
>       "id": "a634a434-f3f6-4452-a2aa-039a0f21da07",
>       "created_at": "2020-04-16T21:41:12Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 351840,
>       "type": "residence_permit",
>       "side": "back",
>       "issuing_country": null,
>       "href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/a634a434-f3f6-4452-a2aa-039a0f21da07",
>       "download_href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/a634a434-f3f6-4452-a2aa-039a0f21da07/download"
>     },
>     {
>       "id": "5d1045b7-4510-4ea1-9002-563d91db381c",
>       "created_at": "2020-04-16T21:41:03Z",
>       "file_name": "onfido_captured_image.jpg",
>       "file_type": "jpg",
>       "file_size": 356761,
>       "type": "residence_permit",
>       "side": "front",
>       "issuing_country": null,
>       "href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/5d1045b7-4510-4ea1-9002-563d91db381c",
>       "download_href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/documents/5d1045b7-4510-4ea1-9002-563d91db381c/download"
>     }
>   ]
> }
> ### Then check can be created - issue is not reproduced
> POST https://api.onfido.com/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/checks
> Authorization: Token
> Content-Type: application/json
> {
>   "type": "express",
>   "async": true,
>   "reports": [
>     {
>       "name": "facial_similarity"
>     },
>     {
>       "name": "document",
>       "options": [
>         {
>           "name": "document_address_information"
>         }
>       ]
>     }
>   ]
> }
> ==>
> {
>   "id": "c9b87da9-5404-424b-acf7-399f634363ab",
>   "created_at": "2020-04-17T07:40:04Z",
>   "status": "in_progress",
>   "redirect_uri": null,
>   "result": null,
>   "sandbox": true,
>   "tags": [],
>   "results_uri": "https://dashboard.onfido.com/checks/c9b87da9-5404-424b-acf7-399f634363ab",
>   "form_uri": null,
>   "paused": false,
>   "type": "express",
>   "report_type_groups": [
>     "4576"
>   ],
>   "download_uri": "https://onfido.com/dashboard/pdf/information_requests/64485103",
>   "href": "/v2/applicants/c6f4705d-fd9f-44e7-b38b-e86adcb238eb/checks/c9b87da9-5404-424b-acf7-399f634363ab",
>   "reports": [
>     {
>       "created_at": "2020-04-17T07:40:04Z",
>       "documents": [
>         {
>           "id": "357abccf-7b5b-4f66-a04c-121516583536"
>         },
>         {
>           "id": "2ccdf115-730c-4789-b95c-87bdd4abef2f"
>         }
>       ],
>       "href": "/v2/checks/c9b87da9-5404-424b-acf7-399f634363ab/reports/0ed4f15b-0b85-4574-b0eb-a96d176b6b97",
>       "id": "0ed4f15b-0b85-4574-b0eb-a96d176b6b97",
>       "name": "document",
>       "properties": {},
>       "result": null,
>       "status": "awaiting_data",
>       "sub_result": null,
>       "variant": "standard",
>       "breakdown": {}
>     },
>     {
>       "created_at": "2020-04-17T07:40:04Z",
>       "documents": [],
>       "href": "/v2/checks/c9b87da9-5404-424b-acf7-399f634363ab/reports/55d977a9-5c37-4b04-b0b1-9879c3bf0c03",
>       "id": "55d977a9-5c37-4b04-b0b1-9879c3bf0c03",
>       "name": "facial_similarity",
>       "properties": {},
>       "result": null,
>       "status": "awaiting_data",
>       "sub_result": null,
>       "variant": "standard",
>       "breakdown": {}
>     }
>   ],
>   "version": "2.0"
> }

**Comment by bracadabra** [comment]
@burakeregar and if there are no problems with onfido android sdk is it possible that the prblem with onfido backend?

**Comment by burakeregar** [comment]
@bracadabra Thanks for the further information. We are investigating the issue at the moment. Will let you know when we have more information.

**Comment by gokhanaliccii** [comment]
@bracadabra  `residence_permit` has not been supported by the Onfido [backend](https://documentation.onfido.com/#document-types) and when a check started for unsupported document types the Onfido returns a validation error. We fixed the problem internally, i hope you have no longer the problem. 

In the next week we're gonna release a new version that returns `DocumentType.UNKNOWN` for `DocumentType.RESIDENCE_PERMIT` and `GENERIC`

Can you please confirm you have no longer the problem?

**Comment by bracadabra** [comment]
@gokhanaliccii the problem is gone, thanks
