### ISSUE TITLE
Migration to AndroidX

### ISSUE THREAD

**Issue by androideveloper** [onfido/onfido-android-sdk#123]
Onfido Sdk still uses the old support library so it prevents us from disabling Jetifier which potentially increase compilation time required to process dependencies. Legacy support-library is not maintained anymore and essentially deprecated, the latest version is 28 (so no more support for newest API levels), no more bugfixes. Any plans on migrate to AndroidX?

**Comment by burakeregar** [comment]
Hi @androideveloper,

We are considering AndroidX migration at the moment. We will provide more updates about it soon.

Thanks

**Comment by burakeregar** [comment]
Version 7.0.0 has been released now. This release includes AndroidX migration. Please see https://github.com/onfido/onfido-android-sdk/releases/tag/7.0.0

**Comment by androideveloper** [comment]
@burakeregar Thanks!
