### ISSUE TITLE
Italian and German language support

### ISSUE THREAD

**Issue by ir2pid** [onfido/onfido-android-sdk#125]
#### What was the expected behaviour?
We would like Italian and German language support
#### What happened instead?
No support
#### Version info:

- `onfido-capture-sdk` version:17.0.0

**Comment by burakeregar** [comment]
Hi @ir2pid 

German language support has been added to the Android SDK as of [v6.0.0](https://github.com/onfido/onfido-android-sdk/releases/tag/6.0.0). 

For the languages that we don't support yet such as Italian, you can provide your translations. Please refer to the localisation part of the [README](https://github.com/onfido/onfido-android-sdk#4-localisation).
