### ISSUE TITLE
Failed to resolve SDK V7.2.0

### ISSUE THREAD

**Issue by MustafaDev-shaikh** [onfido/onfido-android-sdk#128]
#### What happened instead?

While implementing SDK into my Project It's give me error as "**Failed to resolve: com.onfido.sdk.capture:onfido-capture-sdk:7.2.0**"

#### Version info:

- `onfido-capture-sdk` version: 7.2.0
- Android API version(s): 9

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 21
![Onfido_error](https://user-images.githubusercontent.com/62279606/91005206-efba5080-e5f3-11ea-9726-64f41d5e0fa4.png)

- Support library version (if applicable):

#### Other useful info:
_screenshots, videos, etc._

**Comment by kushal-onfido** [comment]
Hi @MustafaDev-shaikh 

Could you please try the solution shared [here](https://github.com/onfido/onfido-android-sdk/issues/98#issuecomment-585761667) and confirm if that solves the issue for you?

Thanks!

**Comment by MustafaDev-shaikh** [comment]
The issue has been fixed after adding maven. Thanks @kushal-onfido
