### ISSUE TITLE
NoSuchFieldError: No field fl_content

### ISSUE THREAD

**Issue by apperside** [onfido/onfido-android-sdk#13]
Hi, using the following code 

```
final OnfidoConfig config = OnfidoConfig.builder()
                                        .withToken(BuildConfig.ONFIDO_KEY)
                                        .withApplicant(applicantId)
                                        .build();
        Onfido onfido = OnfidoFactory.create(getActivity()).getClient();
        onfido.startActivityForResult(getActivity(),1,config);
```

I get the following exception

```
FATAL EXCEPTION: main
java.lang.NoSuchFieldError: No field fl_content of type I in class Lcom/onfido/android/sdk/capture/R$id; or its superclasses (declaration of 'com.onfido.android.sdk.capture.R$id' appears in /data/app/com.conio.wallet.testnet-1/split_lib_slice_4_apk.apk)
at com.onfido.android.sdk.capture.ui.OnfidoActivity$c.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6121)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by sergiomarquesmoura** [comment]
Hi @apperside !
Have you tried to add any proguard rules in your rules file to overcome this? i.e.
-keep public class com.onfido.android.sdk.** { public protected *; }

**Comment by apperside** [comment]
Hi,
actually, on the build I trying to run, I am not using proguard at all


On 2 March 2018 at 13:44:47, Sérgio Marques Moura (notifications@github.com)
wrote:

Hi @apperside <https://github.com/apperside> !
Have you tried to add any proguard rules in your rules file to overcome
this? i.e.
-keep public class com.onfido.android.sdk.** { public protected *; }

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/onfido/onfido-android-sdk/issues/13#issuecomment-369911474>,
or mute the thread

**Comment by apperside** [comment]
I just tried to run a build configured with proguard, providing to it the following rule

-keep class com.onfido.android.** { *; }

But I still get the same error

**Comment by sergiomarquesmoura** [comment]
@apperside which SDK version are you testing against?

**Comment by apperside** [comment]
2.4.0


On 2 March 2018 at 15:27:03, Sérgio Marques Moura (notifications@github.com)
wrote:

@apperside <https://github.com/apperside> which SDK version are you testing
against?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/onfido/onfido-android-sdk/issues/13#issuecomment-369934775>,
or mute the thread

**Comment by sergiomarquesmoura** [comment]
Is there any possibility that you are overriding our `activity_onfido.xml` resource on your side?

**Comment by apperside** [comment]
That definitely was was the issue!! Thank you
