### ISSUE TITLE
Local identifier included in translatable strings

### ISSUE THREAD

**Issue by Ishmael-ZT** [onfido/onfido-android-sdk#131]
Is this accidental?... my translators do not know what to do with this. Shouldn't this be a non-translatable string?

https://github.com/onfido/onfido-android-sdk/blob/d43ef25229793494e2b32279d92eebe0dbf46af3/strings.xml#L21

**Comment by burakeregar** [comment]
> When adding custom translations, please make sure you add the whole set of keys we have on strings.xml. In particular, onfido_locale, which identifies the current locale being added, must be included. The value for this string should be the ISO 639-1 2-letter language code corresponding to the translation being added. Examples:
> When adding a translations file inside values-ru (russian translation), the onfido_locale key should have ru as its value.
> When adding a translations file inside values-en-rUS (american english translation), the onfido_locale key should have en as its value.

Please see the localisation part in the [README](https://github.com/onfido/onfido-android-sdk#4-localisation) file.
