### ISSUE TITLE
Small color customization issues

### ISSUE THREAD

**Issue by dave-mls** [onfido/onfido-android-sdk#133]
Hi there,
I found some points in which the customized colors are not applied.

#### What was the expected behaviour?

The BG of the Info icon to the left of the "Glare is detected" label (screenshot_1) and the progress wheel in the loading dialog (screenshot_2) should be customized like the other "colored" items in the flow (like for instance the ones in the below screenshot_3).

#### What happened instead?

Their color is not being customized, keeping the default one.

#### Version info:

- `onfido-capture-sdk` version: 7.3.0

#### Steps to reproduce:

Customize the colors overriding:
onfidoColorPrimary
onfidoColorPrimaryDark
onfidoTextColorPrimary
onfidoTextColorSecondary
onfidoColorAccent
onfidoPrimaryButtonColor
onfidoPrimaryButtonColorPressed
onfidoPrimaryButtonTextColor

None of them will customize that items (onfidoColorAccent should be the right one).

#### Onfido Flow initialization code:

```
OnfidoClient.startActivityForResult(fragment, 12345, OnfidoConfig.builder(fragment.requireContext()).apply {
    withSDKToken(token, ExpirationHandler(mCacheDir, apiToken, applicationId, applicantId))
    withLocale(if (user.platform == Platform.IT) Locale.ITALIAN else Locale.ENGLISH)
}.build())
```

#### Other useful info:

**- screenshot_1**
<img width="347" alt="Schermata 2020-10-12 alle 16 17 43" src="https://user-images.githubusercontent.com/72750738/95758677-10745d80-0ca9-11eb-800d-8b6e2423ef99.png">

**- screenshot_2**
<img width="433" alt="Schermata 2020-10-12 alle 16 18 01" src="https://user-images.githubusercontent.com/72750738/95758738-1ff3a680-0ca9-11eb-8aa3-259968558783.png">

**- screenshot_3**
<img width="479" alt="Schermata 2020-10-12 alle 16 18 59" src="https://user-images.githubusercontent.com/72750738/95759461-030ba300-0caa-11eb-9677-0d0fc10f8b42.png">

**Comment by gokhanaliccii** [comment]
Hi @dave-mls 

Sorry for the inconvenience, we have some tickets in our backlog to ease customization in the SDK

- To change the icon background color on the glare detected warning view, you can override the `onfido_post_capture_warning `

```
<color name="onfido_post_capture_warning">#353FF4</color>
```

- To change the progress wheel color, you could override `colorAccent` property at `OnfidoAlertDialogTheme`
```
    <style name="OnfidoAlertDialogTheme" parent="Theme.AppCompat.Light.Dialog.Alert">
        <item name="colorAccent">@color/onfido_brand_primary_500</item>
        <item name="android:textAppearanceSmall">@style/OnfidoTextStyle.Body.Regular</item>
    </style>  
```

I'm closing the issue, feel free to reopen it if not resolved
