### ISSUE TITLE
Typecastexception: CaptureActivity.getOnfidoConfig (CaptureActivity.java)

### ISSUE THREAD

**Issue by amit-affirm** [onfido/onfido-android-sdk#135]
#### What was the expected behaviour?
CaptureActivity should not be doing running without Config.

#### What happened instead?
Seems to run on it's own and then crashes due to no Config info

#### Version info:

- `onfido-capture-sdk` version:
- Android API version(s): onfido-capture-sdk-core:7.3.0

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: Marshmallow
- Support library version (if applicable): N/a

#### Steps to reproduce:
Not sure. We see 2 crashes in Crashlytics.

#### Onfido Flow initialization code:
We haven't even turned on Onfido so this appears to be happening on its own. 

#### Issue severity information (number of users/crashes if applicable):
2

#### Additional LogCat output:
```
Caused by kotlin.TypeCastException: null cannot be cast to non-null type com.onfido.android.sdk.capture.OnfidoConfig
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.getOnfidoConfig(CaptureActivity.java)
       at com.onfido.android.sdk.capture.ui.BaseActivity.onCreate(BaseActivity.java)
       at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCreate(CaptureActivity.java)

```
#### Other useful info:
_screenshots, videos, etc._

**Comment by gokhanaliccii** [comment]
Hi @amit-affirm 

> We haven't even turned on Onfido so this appears to be happening on its own
do you mean you don't call one of the `Onfido.startActivityForResult` functions to start Onfido SDK but somehow you get the TypeCastException ?

**Comment by amit-affirm** [comment]
That's right. I saw this error in our production logs and this feature is not visible yet to our users, so it appears it's running automatically. Even if somehow a user got to it, it should not crash because we're passing in a non-null Config always.

**Comment by gokhanaliccii** [comment]
can you please share your integration code?

**Comment by burakeregar** [comment]
Closing the issue due to inactivity. Please feel free to re-open if the issue persists.
