### ISSUE TITLE
"Powered by" logo is not localized

### ISSUE THREAD

**Issue by GaborPeto** [onfido/onfido-android-sdk#138]
#### What was the expected behaviour?

Powered by logo should be localized to French

#### What happened instead?

It is showing in English

#### Version info:

- `onfido-capture-sdk` version: 4.8.0

<img src="https://user-images.githubusercontent.com/8998342/97197851-06bd2080-17a6-11eb-955b-a7a1bed3e2cb.png" height="500" />

**Comment by burakeregar** [comment]
Hi @GaborPeto, 

Our logo has been changed to "Onfido | Real Identity" on v7.0.0. However, since this is part of our brand, it is still not translatable.
