### ISSUE TITLE
NoSuchMethodError: okhttp3.logging.HttpLoggingInterceptor$Logger$1.log (HttpLoggingInterceptor.java:114)

### ISSUE THREAD

**Issue by amit-affirm** [onfido/onfido-android-sdk#139]
#### What was the expected behaviour?
No crash

#### What happened instead?
We're seeing high-frequency crashes with this error. We've had to pause our rollout completely as the issue is serious enough.

#### Version info:

- `onfido-capture-sdk` version: com.onfido.sdk.capture:onfido-capture-sdk-core:7.3.0
- Android API version(s): 

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 23
- Support library version (if applicable):

#### Steps to reproduce:
Based on our logs, this is happening at app startup.
Mostly appears to be affecting Android 9, 10
Mostly affecting Samsung devices

#### Other useful info:
<img width="453" alt="Screen Shot 2020-11-07 at 11 24 17 AM" src="https://user-images.githubusercontent.com/56614068/98449820-1153b000-20ec-11eb-8353-41e3826f63d3.png">
<img width="451" alt="Screen Shot 2020-11-07 at 11 24 11 AM" src="https://user-images.githubusercontent.com/56614068/98449822-11ec4680-20ec-11eb-8feb-6dcffe4c21fa.png">
<img width="1042" alt="Screen Shot 2020-11-07 at 11 19 29 AM" src="https://user-images.githubusercontent.com/56614068/98449823-11ec4680-20ec-11eb-9bf2-e48b34c44c73.png">
<img width="1095" alt="Screen Shot 2020-11-07 at 10 57 16 AM" src="https://user-images.githubusercontent.com/56614068/98449824-1284dd00-20ec-11eb-9964-01fb3ff7a973.png">
<img width="444" alt="Screen Shot 2020-11-07 at 11 28 06 AM" src="https://user-images.githubusercontent.com/56614068/98449854-5bd52c80-20ec-11eb-8ac4-fe2d7551aeb5.png">

**Comment by gokhanaliccii** [comment]
Hi @amit-affirm, 
We’re sorry for you had to pause rollback. The error probably  occurs due to okhttp and okhttp-log-interceptor artifacts  version mismatch due to one of your dependencies uses a higher version of the okhttp

Would you mind sharing your app’s dependency graph with us? 
`./gradlew app:dependencies`

After you share the dependency graph, we’ll try to reproduce the issue on our end to diagnose whether the error occurs due to  okhttp and okhttp-log-interceptor version mismatch or not

**Comment by amit-affirm** [comment]
Yes I think so too. We're using okhttp 4.9.0 and I believe you are using okhttp-log-interceptor is version 3.12.12

**Comment by gokhanaliccii** [comment]
> I believe you are using okhttp-log-interceptor is version 3.12.12

Yes, we're using that version

The problem will be resolved when you add the `logging-interceptor:4.9.0` into your project, it makes sense to add `logging-
interceptor` in the constraints block as it's your transitive dependency

**Comment by amit-affirm** [comment]
Yes, we've confirmed that this works.

Separately, you may want to consider removing `logging-interceptor` from your prod/release build.

**Comment by gokhanaliccii** [comment]
Thanks for your suggestion we'll consider that
