### ISSUE TITLE
Identity and Face issue

### ISSUE THREAD

**Issue by rutul089** [onfido/onfido-android-sdk#14]
Hey,
I m using onfido for identity verification. I am from India and I want to identify user globally whenever I try to match user identify with document its show unparsable if I use check type to standard `Check.Type.STANDARD`
and when I use `Check.Type.EXPRESS` then its show considered in the wrong case to currently I am testing this on demo code

**Comment by sergiomarquesmoura** [comment]
Hello @rutul089 !
This seems to be more like an API integration/workflow issue. May I ask you to forward this to api@onfido.com ?

Thanks in advance

**Comment by rfreitas** [comment]
@rutul089 you should be using EXPRESS. Also, are you initiating the check on the client or server?

**Comment by rahulshah007** [comment]
@rfreitas  on client side
