### ISSUE TITLE
 New sdkToken does not use when restarting Onfido Activity

### ISSUE THREAD

**Issue by DmitriyG1** [onfido/onfido-android-sdk#140]
#### What was the expected behaviour?
Onfido works well
#### What happened instead?
An error is displayed on the screen
#### Version info:

- `onfido-capture-sdk` version: 7.4.0
- Android API version(s): 29

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 21
- Support library version (if applicable):

#### Steps to reproduce:

1. Create OnfidoConfig with invalid sdkToken
2. Start Onfido Activity
3. An error is displayed on the screen
4. After returning from the Onfido screen, сreate OnfidoConfig with valid sdkToken. And restart Onfido Activity.

#### Onfido Flow initialization code:
```kotlin
class MainActivity : AppCompatActivity() {
  private lateinit var client: Onfido

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    client = OnfidoFactory.create(this).client
  }

  private fun startOnfido(sdkToken: String) {
    val document = forNationalIdentity()
      .withCountry(CountryCode.BG)
      .build()

    val flowSteps = arrayOf(
      document
    )

    val onfidoConfig = OnfidoConfig.builder(this)
      .withSDKToken(sdkToken)
      .withCustomFlow(flowSteps)
      .build()

    startActivityForResult(client.createIntent(onfidoConfig), ONFIDO_REQUEST_CODE)
  }
}
```

**Comment by gokhanaliccii** [comment]
@DmitriyG1 

In the code snippet, I noticed you don't use the **client** object to invoke **startActivityForResult**

can you please change  
```
startActivityForResult(client.createIntent(onfidoConfig), ONFIDO_REQUEST_CODE)
```
to
```
client.startActivityForResult(this, ONFIDO_REQUEST_CODE, onfidoConfig)
```

PS:  [sample app](https://github.com/onfido/onfido-android-sdk/blob/master/sample-app/app/src/main/java/com/onfido/android/app/sample/MainActivity.java#L61) code snippet

Additionally, If my suggestion does not fix the problem, could you please add more detail about the problem such as screenshot, logcat output

**Comment by DmitriyG1** [comment]
@gokhanaliccii 

This change fixed the issue:

```
client.startActivityForResult(this, ONFIDO_REQUEST_CODE, onfidoConfig)
```

Thank you!
