### ISSUE TITLE
Failed to resolve: com.onfido.sdk.capture:onfido-capture-sdk:+

### ISSUE THREAD

**Issue by dev-horacebg** [onfido/onfido-android-sdk#141]
I realise there are variations of this issue that have been closed already but this happens with both a fresh and an existing project and I've followed the instructions for importing the onfido-capture-sdk _exactly_ as documented in the README:

```
repositories {
  jcenter()
}

dependencies {
  implementation 'com.onfido.sdk.capture:onfido-capture-sdk:+'
}
```

I've even tried a number of variations of this by using the bintray maven URL instead:

```
maven { url "https://dl.bintray.com/onfido/maven" }
```

or jcenter:
```
jcenter()
```

…or both. I've even tried all of the above with specific version numbers including the latest (7.4.0)

#### What was the expected behaviour?

Following the instructions provided in the README would successfully import the SDK to my Android project.

#### What happened instead?
Failed to resolve: com.onfido.sdk.capture:onfido-capture-sdk:+ error message
#### Version info:

- `onfido-capture-sdk` version:
- Android API version(s):

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 24
- Support library version (if applicable):

#### Steps to reproduce:
Start a new project, attempt to import project in gradle by following the steps outline in 2.1 of the README

Are there additional steps or prerequisites missing from the README that I'm not doing?

**Comment by gokhanaliccii** [comment]
Hi @dev-horacebg, 

Would you mind testing our [sampleapp](https://github.com/onfido/onfido-android-sdk/tree/master/sample-app)?

**Comment by dev-horacebg** [comment]
That also didn't work initially until Invalidating and Clearing caches from Android Studio. Now both work. Thank you.
