### ISSUE TITLE
Migration process gets killed

### ISSUE THREAD

**Issue by Ishmael-ZT** [onfido/onfido-android-sdk#142]
#### What was the expected behaviour?
I believe this is supposed to updated the translation string keys,
I ran the migration script as described here - https://github.com/onfido/onfido-android-sdk/blob/master/MIGRATION.md#730---740

#### What happened instead?

Process gets killed on my mac before in completes everytime

#### Version info: 7.4.0

- `onfido-capture-sdk` version: 7.4.0
- Android API version(s): 29.0.2

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 16
- Support library version (if applicable):

#### Steps to reproduce:

I run the migration script on my Macbook

#### Other useful info:

<img width="726" alt="Screenshot 2020-11-30 at 16 29 46" src="https://user-images.githubusercontent.com/72451080/100623590-0aa30c00-332b-11eb-90b8-e965d4e10644.png">

**Comment by gokhanaliccii** [comment]
Hi @Ishmael-ZT

Sorry for the inconvenience, it seems the migration script fails to replace a string that contains the escape character, I've created a bug ticket in our internal system in the meantime would you mind doing an additional step to make the script run?

- Remove all escape character in your strings.xml using replaceAll **\\'** to **'**
example:

before:
`<string name="onfido_message_capture_error_video">Video capture didn\'t work. Please try again.</string>`

after:
`<string name="onfido_message_capture_error_video">Video capture didn't work. Please try again.</string>`

- run the migration script as you did

- Put the escape character back to all string that contains **'**, using replaceAll  **'** to **\\'**

**Comment by Ishmael-ZT** [comment]
Thank you, removing the escape characters has worked.... 
<img width="574" alt="Screenshot 2020-12-02 at 13 07 33" src="https://user-images.githubusercontent.com/72451080/100864988-6ee6dc80-349f-11eb-8e5a-5488fe6bf88f.png">
