### ISSUE TITLE
Update library to Rxjava3

### ISSUE THREAD

**Issue by androideveloper** [onfido/onfido-android-sdk#145]
RxJava2 will be supported until Feb 28, 2021 https://github.com/ReactiveX/RxJava/wiki/What's-different-in-3.0#2x-now-in-maintenance-mode

We have migrated our project to RxJava3 and noticed that onfido still brings RxJava2 dependency.

Dependencies report:

![Screenshot 2021-01-15 at 16 44 57](https://user-images.githubusercontent.com/1249919/104754934-15d6bd80-575a-11eb-87c6-434e91d94230.png)

**Comment by gokhanaliccii** [comment]
@androideveloper sorry for the late reply, 

our team has decided to migrate RxJava3, we'll update this issue when we complete the migration

**Comment by androideveloper** [comment]
Hi @gokhanaliccii . Thanks for the update, looking forward to it 👍

**Comment by gokhanaliccii** [comment]
FYI, Our team completed the migration, hopefully, we'll release it in one of the next releases

**Comment by musagil** [comment]
hi @androideveloper 

We've published a new version that contains the migration. 

Please bump to the latest version, thanks

**Comment by androideveloper** [comment]
Thanks for the update!
