### ISSUE TITLE
No appropriate callback or error logs for document capture failure

### ISSUE THREAD

**Issue by jabitsis** [onfido/onfido-android-sdk#146]
#### What was the expected behaviour?
Display or return specific error when document does not upload.

#### What happened instead?
Connection lost error on sample app (provided in GitHub) as well as on example app with our sdkToken.

#### Version info:

- `onfido-capture-sdk` version: 8.0.0

- Android API version(s)
- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 21
- Support library version (if applicable):

#### Steps to reproduce:
Attempting to upload any document.

#### Onfido Flow initialization code:
`val onfido = OnfidoFactory.create(requireContext()).client`
`val flowSteps = arrayOf(FlowStep.WELCOME, FlowStep.CAPTURE_DOCUMENT, FlowStep.CAPTURE_FACE, FlowStep.FINAL)`
`val config = OnfidoConfig.builder(requireContext()).withCustomFlow(flowSteps).withSDKToken(sdkToken).build()`
`onfido.startActivityForResult(this, 1, config)`

#### Additional LogCat output:
`OkHttp: <-- 401 https://api.onfido.com/v3/documents`

#### Other useful info:
![onfido_upload_error](https://user-images.githubusercontent.com/73889127/104877750-f5824b00-5973-11eb-9344-cda049e6a542.png)

**Comment by burakeregar** [comment]
Hi @jabitsis 

The `application_id` you are using to create the sdkToken should match with your application's applicationId (context.packageName or app/build.gradle).

Could you please check that you use the same values?

**Comment by jabitsis** [comment]
Yes, this was the issue. The applicationId used to create sdkToken was different.

**Comment by jabitsis** [comment]
Yes, this was the issue. The applicationId used to create sdkToken was different. Thank you!
