### ISSUE TITLE
Not all Events are triggered for UserEventHandler

### ISSUE THREAD

**Issue by FabianSchmiedlechner** [onfido/onfido-android-sdk#148]
#### What was the expected behaviour?
That the UserEventHandler triggers all the mentioned Events as documented in [TrackedEvents.md](https://github.com/onfido/onfido-android-sdk/blob/master/TRACKED_EVENTS.md)

We need to track the two video_facial_capture steps.

#### What happened instead?
The following two steps do not get triggered since version 7.0.0. Neither with Version 8.0.0 nor 9.0.0 it works.

```
VIDEO_FACIAL_CAPTURE_STEP_1 - User reached the 1st challenge during “liveness video capture", challenge_type can be found in eventProperties 
 
VIDEO_FACIAL_CAPTURE_STEP_2 - User reached the 1st challenge during “liveness video capture", challenge_type can be found in eventProperties 
```

#### Version info:

- `onfido-capture-sdk` version: 9.0.0
- Android API version(s): 11

- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 23
- Support library version (if applicable):

#### Steps to reproduce:
Add the UserEventHandler. Not all the events get triggered as documented when you go through the screens.

#### Other useful info:
_screenshots, videos, etc._

**Comment by burakeregar** [comment]
Hi @FabianSchmiedlechner,

Thanks for reporting the issue and sorry for the inconvenience. I can reproduce the issue on my end and we will be keeping here posted once we have an update.

**Comment by gokhanaliccii** [comment]
Hi @FabianSchmiedlechner,

Thanks for your patience, this problem has been fixed with our [latest SDK version](https://github.com/onfido/onfido-android-sdk/releases/tag/10.0.0). Please, update your SDK version to the latest version (10.0.0)

I'm closing the issue, feel free to re-open it if you still experience the problem
