### ISSUE TITLE
Getting new versions post 31st March 2021 / Hosting post JCenter()

### ISSUE THREAD

**Issue by blundell** [onfido/onfido-android-sdk#149]
#### What was the expected behaviour?

Updates after 31st March 2021

#### What happened instead?

JCenter said no

#### Version info:

All new versions from 31st March 2021. 
All versions from February 2022.

#### Steps to reproduce:

1) Attempt to publish an OnFido updated after 31st March 2021.
2) It won't work

From the README.md:

![image](https://user-images.githubusercontent.com/655860/108721665-2bd65b80-751a-11eb-9405-ac805d5c8c5c.png)

#### Issue severity information (number of users/crashes if applicable):

All users

#### Other useful info:

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**What are you going to do about releasing newer versions after 31st March? (Aka 38 days away)**

![image](https://user-images.githubusercontent.com/655860/108721569-0b0e0600-751a-11eb-825c-24a4bda8c05a.png)

**Comment by burakeregar** [comment]
Hi @blundell,

This is being discussed and prioritised internally. We will be communicating about it soon.

**Comment by gokhanaliccii** [comment]
Hi @blundell,

Our team decided to use **maven central** and [completed](https://search.maven.org/search?q=g:com.onfido.sdk.capture) migration. You could start consuming artifacts from maven central, you just need to add `mavenCentral()` into the `repositories` block if it is not already added

Btw we'll update our documentation within a new release soon :)
