### ISSUE TITLE
Passport wrong analytic event

### ISSUE THREAD

**Issue by GMetaxakis** [onfido/onfido-android-sdk#151]
#### What was the expected behavior?
I would expect for Passport to get in `UserEventHandler()` the `DOCUMENT_CAPTURE` event

#### What happened instead?
I am getting  the `DOCUMENT_CAPTURE_FRONT` event

#### Version info:

- `com.onfido.sdk.capture:onfido-capture-sdk-core` version: `8.0.0` and `9.1.0`
- Android API version(s): 

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`:23

#### Steps to reproduce:
Try Onfido flow for Passport

#### Other useful info:
```
eventProperties = {Properties@21974}  size = 4
 "name" -> "DOCUMENT_CAPTURE_FRONT"
 "mode" -> "{"orientation":"PORTRAIT"}"
 "doc_type" -> "passport"
 "is_autocapture" -> {Boolean@21993} false
 ```
![Screenshot 2021-03-09 at 4 43 49 PM](https://user-images.githubusercontent.com/4234419/110488010-ca57e480-80f6-11eb-9137-97d0e57f2a0b.png)

**Comment by andra-radu** [comment]
Hi @GMetaxakis,

for passport capture SDK send DOCUMENT_CAPTURE_FRONT. There's a mistake in our documentation and we have created an internal ticket to modify the following "DOCUMENT_CAPTURE - User reached the "document capture" screen (for one-sided document)".

**Comment by GMetaxakis** [comment]
I believe the iOS SDK sends the `DOCUMENT_CAPTURE` for Passport

**Comment by GMetaxakis** [comment]
any update on this @andra-radu ?

**Comment by andra-radu** [comment]
@GMetaxakis I have reached our to our iOS SDK team but unfortunately I haven’t heard back from them yet. I will let you know as soon as I will receive an update from them.

**Comment by andra-radu** [comment]
@GMetaxakis Just wanted to let you know that on iOS it already uses DOCUMENT_CAPTURE.

**Comment by GMetaxakis** [comment]
> @GMetaxakis Just wanted to let you know that on iOS it already uses DOCUMENT_CAPTURE.

i know that, but in android you send for the same `DOCUMENT_CAPTURE_FRONT` this is "messes" with our analytics as it is different between 2 systems. is there something that you will do on the android SDK?

**Comment by andra-radu** [comment]
@GMetaxakis The SDK team decided to use “DOCUMENT_CAPTURE” event for passport capture. We will let you know as soon as the changes will be implemented.

**Comment by gokhanaliccii** [comment]
FYI, We've started to work on this issue, it will be fixed in the release :)

**Comment by gokhanaliccii** [comment]
hi @GMetaxakis,

We've published a new version that contains the "DOCUMENT_CAPTURE" analytic event update. 

Please bump to [the latest](https://github.com/onfido/onfido-android-sdk/releases/tag/10.1.0) version, thanks
