### ISSUE TITLE
Bogus JAR artifacts in MavenCentral

### ISSUE THREAD

**Issue by wiyarmir** [onfido/onfido-android-sdk#154]
#### What was the expected behaviour?

MavenCentral responds with valid artifacts when found, or 404 otherwise.

#### What happened instead?

There are files uploaded to MavenCentral with bogus content instead of the real artifacts.
e.g.
```
❯ curl -v https://repo.maven.apache.org/maven2/com/onfido/api/client/onfido-api-client/9.2.0/onfido-api-client-9.2.0.jar
*   Trying 151.101.12.215:443...
* TCP_NODELAY set
* Connected to repo.maven.apache.org (151.101.12.215) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=Maryland; L=Fulton; O=Sonatype, Inc; CN=repo.maven.apache.org
*  start date: Aug 18 00:00:00 2020 GMT
*  expire date: Sep 24 12:00:00 2021 GMT
*  subjectAltName: host "repo.maven.apache.org" matched cert's "repo.maven.apache.org"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5622e647e7c0)
> GET /maven2/com/onfido/api/client/onfido-api-client/9.2.0/onfido-api-client-9.2.0.jar HTTP/2
> Host: repo.maven.apache.org
> user-agent: curl/7.68.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200
< etag: "8cca5643ffb7182cca9c2e154b44cb5e"
< content-type: application/java-archive
< last-modified: Mon, 05 Apr 2021 19:28:31 GMT
< x-checksum-md5: 8cca5643ffb7182cca9c2e154b44cb5e
< x-checksum-sha1: 2b0f02371aa9be4644ebbf65186ab6b4956b498f
< via: 1.1 varnish, 1.1 varnish
< accept-ranges: bytes
< date: Tue, 06 Apr 2021 09:44:32 GMT
< age: 2839
< x-served-by: cache-bwi5147-BWI, cache-fra19181-FRA
< x-cache: HIT, HIT
< x-cache-hits: 1, 1
< x-timer: S1617702272.096465,VS0,VE0
< content-length: 33
<
* Connection #0 to host repo.maven.apache.org left intact
The requested path was not found.%
```
Note that this is a 200 response, serving a real file. Trying invalid filenames (e.g. versions not released) will yield 404 as expected.

#### Version info:

Tried for 7.2.0 and 9.2.0

#### Steps to reproduce:

Have MavenCentral in your dependency repositories.

#### Other useful info:
_screenshots, videos, etc._

**Comment by wiyarmir** [comment]
One way to temporarily fix this without removing `mavenCentral()` from your build is to have this block inside your dependencies declaration:

```
repositories {
    exclusiveContent {
        forRepository {
            maven {
                url "https://dl.bintray.com/onfido/maven"
            }
        }
        filter {
            includeGroupByRegex "com\\.onfido\\..*"
        }
    }
}
```

**Comment by burakeregar** [comment]
Thanks for reporting @wiyarmir. 

Apparently, the issue is related to our java library that the Onfido Android SDK uses and you get as a transitive dependency. We are working on a fix and will keep you posted here once it's resolved.

Sorry for any inconvenience this may cause.

**Comment by GMetaxakis** [comment]
So after hours of searching, why all our builds were failing from yesterday. How this "messed" up the old build like `8.0.0` and not only some new builds? We had hours of spending to understand what happened in our code because we couldn't expect an old version of a library to sudden fails our builds

for gradle kts
```kotlin
exclusiveContent {
    forRepository { maven { setUrl("https://dl.bintray.com/onfido/maven") } }
    filter { includeGroupByRegex("com\\.onfido\\..*") }
}
```

we had this exception
```
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform onfido-api-client-7.3.0.jar (com.onfido.api.client:onfido-api-client:7.3.0) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for EnumerateClassesTransform: /Users/george/.gradle/caches/transforms-3/f1bc0d2db8cdb288cd905529757770e6/transformed/jetified-onfido-api-client-7.3.0.jar.
         > zip END header not found
* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
```
For all versions from 7 -> 9.2

**Comment by burakeregar** [comment]
We are currently waiting for the `onfido-api-client` artifacts to be removed from Maven Central so that we can re-release them to fix the issue. 

In the meantime, as a workaround, you can also move `jcenter()` above `mavenCentral()` like below to avoid introducing extra rules to force the SDK to be fetched from `jcenter`

```
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
} 
```

**Comment by GMetaxakis** [comment]
> We are currently waiting for the `onfido-api-client` artifacts to be removed from Maven Central so that we can re-release them to fix the issue.
> 
> In the meantime, as a workaround, you can also move `jcenter()` above `mavenCentral()` like below to avoid introducing extra rules to force the SDK to be fetched from `jcenter`
> 
> ```
> allprojects {
>     repositories {
>         google()
>         jcenter()
>         mavenCentral()
>     }
> } 
> ```
> 
> Also, it's worth noting that if you force Onfido to be fetched from `jcenter`, you may face an issue in the future as we are migrating the artifacts from `jcenter` to `maven central`.

Update your documentation then to not suggest the usage of `"https://dl.bintray.com/onfido/maven"` but the example that you shared here

**Comment by blundell** [comment]
our poor CI has been red all day! :laughing:

**Comment by burakeregar** [comment]
Hi @blundell 

The issue is fixed. Are you still having issues?

**Comment by boskicaruso** [comment]
@burakeregar we still have that issue.

**Comment by burakeregar** [comment]
Might be related to caching either on your or Maven Central's side. It might be worth cleaning the project and deleting Gradle's cache.

**Comment by ViBiOh** [comment]
To avoid cache and re-download issue, you should make a patch version, to ensure that it's the correct version.

**Comment by blundell** [comment]
FWIW it's the CI so there aren't any caches we don't nuke on our side.
We went with the workaround of taking from bintray for now.

**Comment by burakeregar** [comment]
[Version 9.3.0](https://github.com/onfido/onfido-android-sdk/releases/tag/9.3.0) has been released to Maven Central.
