### ISSUE TITLE
overlayTextContainer is not visible for passport capture screen

### ISSUE THREAD

**Issue by iismagilov** [onfido/onfido-android-sdk#156]
#### What was the expected behaviour?
"Passport face page"/"Position the page with your photo in the frame" are visible for passport document

#### What happened instead?
overlayTextContainer is invisible

#### Version info:

- `onfido-capture-sdk` version: 8.1.0, 9.2.0
- Android API version(s): all versions

- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 21

#### Steps to reproduce:
Launch passport capture step

#### Onfido Flow initialization code:
OnfidoConfig.builder(context)
        .withToken("token")
        .withApplicant("applicantId")
        .withCustomFlow(arrayOf(DocumentCaptureStepBuilder.forPassport().build()))
        .build()

#### Other useful info:
Layout inspector snapshot
<img width="1648" alt="Screenshot 2021-04-23 at 22 03 30" src="https://user-images.githubusercontent.com/7924154/115930162-e6ce9700-a480-11eb-868d-3c39fe633c9a.png">

**Comment by gokhanaliccii** [comment]
@iismagilov  do you use `full` SDK? If so it's expected behaviour for passport capture

**Comment by iismagilov** [comment]
Hey @gokhanaliccii, thanks for reply! We have this in dependencies
- com.onfido.sdk.capture:onfido-capture-sdk
- com.onfido.sdk.capture:onfido-capture-sdk-core
So I assume we use full SDK.
On iOS those main and secondary texts are visible and we would like to show it on Android as well. Is there any option to enable that?

**Comment by gokhanaliccii** [comment]
Hi @iismagilov,

It seems you defined both [core](https://github.com/onfido/onfido-android-sdk#22-onfido-capture-sdk-core) and [full](https://github.com/onfido/onfido-android-sdk#21-onfido-capture-sdk) SDKs in your app/build.gradle but it could cause unpredictable SDK behavior so I would highly recommend only defining **full SDK** in your app/build.gradle file

```
implementation 'com.onfido.sdk.capture:onfido-capture-sdk: sdk_version'
```

Regarding the visibility of the main and secondary texts, on the latest iOS version text behavior similar to android SDK for passport capture and there is no option to enable that. But SDK team decided to show instruction text for passport capture flow. I'll let you know when we release this change in this issue
 
<img width="302" alt="passport_capture" src="https://user-images.githubusercontent.com/4950115/116679784-db103280-a9a2-11eb-99a3-32807b76a32f.png">
 
Also, I noticed that you use a [mobile token](https://github.com/onfido/onfido-android-sdk#42-mobile-token) to initialize SDK flow which is deprecated and will be **removed** in the near feature

```
OnfidoConfig.builder(context)
.withToken("token")
.withApplicant("applicantId")
.withCustomFlow(arrayOf(DocumentCaptureStepBuilder.forPassport().build()))
.build()
```

**Comment by iismagilov** [comment]
@gokhanaliccii thanks! We will address all your points. looking forward for updates regarding text visibility.

**Comment by gokhanaliccii** [comment]
@iismagilov we have updated the document capture screen design in our latest release [10.0.0](https://github.com/onfido/onfido-android-sdk/releases/tag/10.0.0), please bump to the latest version which includes lots of improvements 

I'm closing the issue feel free to open it, if you think the issue hasn't been resolved
