### ISSUE TITLE
handleActivityResult when permission denied returns USER_LEFT_ACTIVITY instead of USER_CONSENT_DENIED

### ISSUE THREAD

**Issue by brahyam** [onfido/onfido-android-sdk#157]
Context: [Handling SDK callbacks](https://github.com/onfido/onfido-android-sdk#handling-callbacks)

#### What was the expected behaviour?

Callback `handleActivityResult` / `userExited` when user denies camera/microphone permission returns `ExitCode` = `USER_CONSENT_DENIED`

#### What happened instead?

Callback `handleActivityResult` / `userExited` when user denies camera/microphone permission returns `ExitCode` = `USER_LEFT_ACTIVITY `

#### Version info:

- `onfido-capture-sdk` version:  9.2.0
- Android API version(s): 

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 21
- Support library version (if applicable): N/A

#### Steps to reproduce:

- Start SDK flow
- See "Allow Camera Access" screen
- Tap on "Enable Camera" button
- Tap on "Deny" button on Android system permission prompt

#### Onfido Flow initialization code:

```
val client = OnfidoFactory.create(this).client
val config = OnfidoConfig.builder(this)
                        .withSDKToken(it.token)
                        .withCustomFlow(
                            arrayOf(
                                DocumentCaptureStepBuilder.forNationalIdentity().withCountry(CountryCode.DE).build(),
                                FaceCaptureStepBuilder.forVideo().build()
                            )
                        )
                        .build()
                    client.startActivityForResult(this, 1, config)
```

#### Issue severity information (number of users/crashes if applicable):

No crashes but having the wrong exit code prevents us from showing the user the right error message as we cannot differentiate between the user denying permissions or clicking on back navigation

#### Other useful info:
Test Device: Samsung S10. Android ver. 11
| Allow Camera Screen | Android Permission Prompt |
|:---:|:---:|
| ![device-2021-04-29-140204](https://user-images.githubusercontent.com/2879534/116547851-b7da7a00-a8f3-11eb-95c2-c5208e70ad34.png)|![device-2021-04-29-140218](https://user-images.githubusercontent.com/2879534/116547857-b9a43d80-a8f3-11eb-853c-a69f38a43dc9.png)|

**Comment by andra-radu** [comment]
Hi @brahyam,

This is the expected behaviour. USER_CONSENT_DENIED is for the optional User Consent page, not for the camera/mic permissions

**Comment by gokhanaliccii** [comment]
@brahyam On android SDK permissions are handled inside the SDK, in case a user denies the required permissions, SDK shows a recovery screen. 

For error handling, you could use `userExited `  and `onError` [callbacks](https://github.com/onfido/onfido-android-sdk#handling-callbacks)

**Comment by seewah** [comment]
Closing it for now. Please reach out if you have further questions. Thanks.
