### ISSUE TITLE
alpha3 in CountryCode is null

### ISSUE THREAD

**Issue by peoxnen** [onfido/onfido-android-sdk#159]
#### What was the expected behaviour?

Field alpha3 is not null.

#### What happened instead?

Check implementation of CountryCode  in 9.3.0 and field alpha3. It is null.

#### Version info:

- `onfido-capture-sdk` version: 9.3.0

- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 23

#### Steps to reproduce:

Check implementation of CountryCode  in 9.3.0 and field alpha3. It is null.

#### Issue severity information (number of users/crashes if applicable):

all users

#### Other useful info:
CountryCode  class in 9.3.0:
public enum CountryCode {
    AD,
    AE,
...
CountryCode  class in 9.2.0:
public enum CountryCode {
    AD("Andorra", "AND", 16),
    AE("United Arab Emirates", "ARE",
...

**Comment by andra-radu** [comment]
Hi @peoxnen - I just wanted to let you know that you will have to supply your own 2-letter ISO string, without using the current publicly exposed alpha3 function. Please let us know if you have any questions.

**Comment by peoxnen** [comment]
I'm sorry I didn't reply. We migrated to from alpha3 to name (CountryCode). Thanks for help.
