### ISSUE TITLE
   java.lang.NoSuchFieldError: com.onfido.android.sdk.capture.R$id.titleTv

### ISSUE THREAD

**Issue by rutul089** [onfido/onfido-android-sdk#16]
After uploading a photo on next screen I m getting this error in every verification flow and scenario 

`   java.lang.NoSuchFieldError: com.onfido.android.sdk.capture.R$id.titleTv`

**Comment by sergiomarquesmoura** [comment]
Hey @rutul089 
Is there a possibility that you have any field in your project resources with the same `R.id.titleTv` name?

**Comment by rutul089** [comment]
yes

**Comment by rutul089** [comment]
Hey @sergiomarquesmoura 
In my case, I have id with 
`R.id.tv_tittle` and `tvTittle` so I don't think so that can be affected ??

**Comment by rutul089** [comment]
Hey @sergiomarquesmoura 
After changing id still, I m getting this error...

**Comment by sergiomarquesmoura** [comment]
@rutul089 what about any layout file named `fragment_message.xml`? If so, could you try to change this name and check if the problem persists? We have most of our XML resources namespaced, but some of them are still missing our prefix, and this resource name on your app might be conflicting with ours.

**Comment by rutul089** [comment]
@sergiomarquesmoura  yes its works thank you for help and I have one more question in the sandbox I m getting all check is considered and clear so it's by default that we are getting this result by default?

**Comment by sergiomarquesmoura** [comment]
Yes @rutul089 that's indeed the expected behaviour for sandbox checks
You can find more details about this here: https://documentation.onfido.com/#sandbox-responses

**Comment by rutul089** [comment]
Thank you for your support. I really appreciate @sergiomarquesmoura
