### ISSUE TITLE
Failed to resolve maven-metadata.xml - Forbidden

### ISSUE THREAD

**Issue by mdcuk34** [onfido/onfido-android-sdk#162]
#### What was the expected behaviour?
We can fetch the Onfido maven config and build our application.

#### What happened instead?
[https://dl.bintray.com/onfido/maven/io/intercom/android/intercom-sdk-base/maven-metadata.xml](https://dl.bintray.com/onfido/maven/io/intercom/android/intercom-sdk-base/maven-metadata.xml) resolves forbidden. 

#### Other useful info:
```
Could not GET 'https://dl.bintray.com/onfido/maven/io/intercom/android/intercom-sdk-base/maven-metadata.xml'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project
```

**Comment by burakeregar** [comment]
Hi @mdcuk34 

We used to use Bintray to publish our artifacts. However, [JFrog sunset Bintray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) recently, hence you are not able to resolve our artifacts using Bintray URLs. 

You need to remove `https://dl.bintray.com/onfido/...` URL from your Gradle and replace it with `mavenCentral()` to start resolving our artifacts from Maven Central instead.

**Comment by mdcuk34** [comment]
Hey @burakeregar, 

10/10 for the quick reply, sorry I must have missed some release notes somewhere. That fixed it, Thanks!
