### ISSUE TITLE
Driving License verification in Nigeria requires 2 sides instead of just 1

### ISSUE THREAD

**Issue by xrigau** [onfido/onfido-android-sdk#165]
#### What was the expected behaviour?

According to the Onfido documentation for supported documents, only 1 side of is required when verifying a Driving License in Nigeria:

![image](https://user-images.githubusercontent.com/1626673/130475456-21a51b51-ad41-4069-931d-4f9311cdaf98.png)

(from: https://onfido.com/supported-documents/)

The expectation here is that when starting an Identity check selecting Driving License as the document type and Nigeria as the country, the Onfido Android SDK would only ask the user to take 1 picture of the front of the Driving License.

#### What happened instead?

Instead of asking the user to take 1 picture, it asks for both a picture of the front and the back of the document.

#### Version info:

- `onfido-capture-sdk` version: Using `com.onfido.sdk.capture:onfido-capture-sdk-core:9.3.0`
- Android API version(s): Not relevant to this issue (but using API 29 in my case).

- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 29
- Support library version (if applicable): n/a

#### Steps to reproduce:

1. Start an Id verification
2. Select Driving License document type
3. Select Nigeria as the country
4. Capture document, observe pictures for both sides are required

#### Onfido Flow initialization code:

```kotlin
val tokenExpirationHandler = // ...
    val config = OnfidoConfig.builder(context)
        .withSDKToken("token", tokenExpirationHandler)
        .build()
    val intent = onfido.createIntent(config)
    startActivity(intent)
```

#### Issue severity information (number of users/crashes if applicable):

Not a major issue, it just seems like the SDK doesn't comply with the rules specified in the official documentation.

#### Additional LogCat output:

N/A

#### Other useful info:

N/A

**Comment by gokhanaliccii** [comment]
Hi @xrigau,

The side requirement is not so straightforward as we have a lot of customers needing both sides for their own audit trail requirements. This is why we are sticking with 2 sides for now regardless of whether we verify both. In the future, we can create more advanced customization logic to accommodate different use cases. So this is the expected behavior at the moment
