### ISSUE TITLE
SIGABRT Exception 

### ISSUE THREAD

**Issue by mpavlopoulou** [onfido/onfido-android-sdk#167]
#### Version info:

- `onfido-capture-sdk` version: 8.0.0
- Android API version(s): 11

- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 24

We have identified two crashes in native C code called from Onfido android SDK on a SM-T976B Samsung device. 
The stacktrace is shown below:
<img width="993" alt="Screenshot 2021-09-08 at 5 00 26 PM" src="https://user-images.githubusercontent.com/48999841/132523869-93d79cab-c08f-4ac7-aec2-0b3adbf8a2e1.png">

Could you please investigate the issue? Thank you in advance.

**Comment by gokhanaliccii** [comment]
@mpavlopoulou thanks for reporting the issue, I've created a ticket to follow this issue. The ticket is in our backlog once we have an update we will keep you updated
