### ISSUE TITLE
Stop Misleading Customers

### ISSUE THREAD

**Issue by mattsputnikdigital** [onfido/onfido-android-sdk#170]
> "The list of document types visible for the user to select can be filtered using this option. If only one document type is specified, users will not see the document selection screen or country selection screen and will be taken directly to the capture screen."

Just as with the iOS version, the documentation is written is such a was as it suggests you can specify what types of document you would like to capture ( like the JS version ). I would expect this to be the default behaviour of Onfido, given customers may not want to ask for certain types of document.

There is no filtering of lists, this is completely misleading.

**Comment by gokhanaliccii** [comment]
Hi @mattsputnikdigital,

We've updated "document type" [documentation](https://github.com/onfido/onfido-android-sdk#document-capture-step) to make it clear. It will be available in the next release

```
The list of document types visible for the user to select can be shown or hidden using this option. If only one document type is specified, users will not see the document selection screen or country selection screen and will be taken directly to the capture screen.

Each document type has its own configuration class.

Note: The specific document types included in the list cannot be customised
```

**Comment by david-liu-android** [comment]
Hey @gokhanaliccii, is this feature added already? I'm asking because I saw the `awaiting release` label has been removed and the text in read me is back to the original text.

```
The list of document types visible for the user to select can be filtered using this option. If only one document type is specified, users will not see the document selection screen or country selection screen and will be taken directly to the capture screen.

Each document type has its own configuration class.
```
