### ISSUE TITLE
Remove `Validator.validate` from the public API

### ISSUE THREAD

**Issue by lambda-tamer** [onfido/onfido-android-sdk#173]
#### What was the expected behavior?

Onfido internal classes and extensions do not pollute client's project namespace

#### What happened instead?

I can call `validate` extension on literally anything

#### Version info:

- `onfido-capture-sdk` version: 10.2.0

**Comment by R4md4c** [comment]
Hey @lambda-tamer, Thanks a lot for reporting this issue. It's indeed something we'd like to fix. 

I've created a ticket in our backlog, and will try to fix in our next release.

**Comment by R4md4c** [comment]
Thanks again @lambda-tamer for your reported issue, we've managed to push a fix, and will be available in the next release.

**Comment by musagil** [comment]
Hey, @lambda-tamer,
This issue is fixed in our new release 10.3.1, please update your dependency and let us know if you could reproduce this again.

I'm closing the issue feel free to open it if you think the issue hasn't been resolved

**Comment by lambda-tamer** [comment]
Good job guys! 👍
