### ISSUE TITLE
Duplicate classes found in modules

### ISSUE THREAD

**Issue by IMasuluke** [onfido/onfido-android-sdk#177]
#### What was the expected behaviour?
successful gradle build 

#### What happened instead?
Duplicate class a.a found in modules jetified-other-dependency-runtime (other-dependency) and jetified-onfido-capture-sdk-core-11.1.0-runtime (com.onfido.sdk.capture:onfido-capture-sdk-core:11.1.0)
#### Version info:
v11.1.0

- `onfido-capture-sdk` version:
- 11.1.0
- Android API version(s): 31

- `compileSdkVersion`: 31 
- `targetSdkVersion`: 31
- `minSdkVersion`: 21
- Support library version (if applicable):

#### Steps to reproduce:
upgrade gradle to 11.1.0 and run

#### Other useful info:
_screenshots, videos, etc._

**Comment by R4md4c** [comment]
Hey @IMasuluke, thanks for taking time to report the issue. 

I'm wondering, if possible, you can specify the actual name of `jetified-other-dependency-runtime` for investigation purposes?

**Comment by IMasuluke** [comment]
Sure here is an example of the first duplicate file`Duplicate class a.a found in modules jetified-android-core-5.33.2-runtime (com.mparticle:android-core:5.33.2) and jetified-onfido-capture-sdk-core-11.1.0-runtime (com.onfido.sdk.capture:onfido-capture-sdk-core:11.1.0)`. mparticle is the main issue

**Comment by Ishmael-ZT** [comment]
Hi @R4md4c, Any idea when this will be resolved? A similar issue fixed by using `flattenpackagehierarchy` in the proguard rules. See this issue here - https://github.com/helpcrunch/android-sdk-demo/issues/33

**Comment by R4md4c** [comment]
Hey @Ishmael-ZT, we've actually solved that using `repackageclasses`. which puts our obfuscated classes behind a common prefix package, so our a.a class, will be repackaged to be `com.onfido.android.sdk.a.a` instead, hence avoiding the conflict. 

It should be available in the next release soon.

**Comment by R4md4c** [comment]
Version 11.4.0 has been release, which should contain the fix. 

Please feel free to reopen the issue in case the issue resurface.
