### ISSUE TITLE
Provide better API for TokenExpirationHandler

### ISSUE THREAD

**Issue by WildOrangutan** [onfido/onfido-android-sdk#179]
#### Issue

Since `TokenExpirationHandler` needs to be `Serializable`, it limits what kind of dependencies you can have. Dependency injection is not possible because of it, which makes it hard to avoid non-testable code or code duplication.

#### Suggestion

Please provide better API, so we can do dependency injection. 

Maybe you could at least provide us with `context` reference, so we can obtain specific object instance by using entry points? For example:

```
class OnfidoExpirationHandler() : TokenExpirationHandler {
    override fun refreshToken(injectNewToken: (Context, String?) -> Unit) {
        injectNewToken( context, _ ->
            val api = EntryPoints.get(context, ApiEntryPoint.class).getApi()
            api.getOnfidoSdkToken()
        }
    }
}
```

#### Version
`onfido-capture-sdk` version: 11.3.0

**Comment by kushal-onfido** [comment]
Hi @WildOrangutan 

Could you please share some more details on how would you want to handle such errors, assuming we return an error instead of crashing?
Thanks!

**Comment by WildOrangutan** [comment]
Hey. I'm not talking about crashing. I'm just saying that there should be better API for token expiration handling, since we currently can't do dependency injection (e.g. Dagger).

**Comment by kushal-onfido** [comment]
Hey @WildOrangutan Thank you for confirming. Our team will do research on it as it needs to be properly revisited and redesigned again to tackle this issue. 
We thank you for sharing your valuable feedback.
