### ISSUE TITLE
Update Onfido SDK strings

### ISSUE THREAD

**Issue by nauman404** [onfido/onfido-android-sdk#184]
Just a simple question, Can we update strings like "Front of card"
"Back of card" on DocumentCapture screen?

**Comment by gurpreet-onfido** [comment]
Hello @nauman404 

I have checked the strings.xml file and could not find these strings. Could you please share the screenshot of the strings you are looking to update so that we can advise you accordingly. 

Kind regards,
Gurpreet

**Comment by nauman404** [comment]
Hey Gurpreet, Thanks for reply.
Please check the below screen and find the "Front of card" text that I want to change.
![image](https://user-images.githubusercontent.com/13114330/163806075-a27054bf-7ef3-4e06-9c8f-82c4fca50ea4.jpeg)

**Comment by nauman404** [comment]
10.1.0

**Comment by nauman404** [comment]
Any update on this
