### ISSUE TITLE
Duplicate class androidx.appcompat.app.BaseContextWrappingDelegate

### ISSUE THREAD

**Issue by shaubert** [onfido/onfido-android-sdk#185]
### Describe the bug
Duplicate class androidx.appcompat.app.BaseContextWrappingDelegate found in modules onfido-capture-sdk-core-10.3.5-runtime (com.onfido.sdk.capture:onfido-capture-sdk-core:10.3.5) and sdk-1.5.1-runtime (com.github.crowdin.mobile-sdk-android:sdk:1.5.1)

### Expected behavior
Maybe you should name it with "Onfido" prefix to avoid duplicates. Looks like other developers use the same technique and even the same naming. Probably all of you read the same StackOverflow question https://stackoverflow.com/questions/55265834/change-locale-not-work-after-migrate-to-androidx 🙂

**Comment by kushal-onfido** [comment]
Hey @shaubert 
This issue has been fixed in the latest Android SDK release 12.2.0. Please refer to the [release notes](https://github.com/onfido/onfido-android-sdk/releases/tag/12.2.0) for more information.

Thank you for reporting this issue to us!
