### ISSUE TITLE
Unable to access live photo data

### ISSUE THREAD

**Issue by tcpickard94** [onfido/onfido-android-sdk#2]
We are wanting to access the LivePhoto data returned from an identity check, but it appears there is no way to retrieve this currently on android.

**Comment by rfreitas** [comment]
not yet. it's possible to download it from the onfido api though, https://documentation.onfido.com/#retrieve-live-photo

**Comment by tcpickard94** [comment]
Thanks for the fast reply. How am I able to access the `live_photo_id` required for the download url?

**Comment by rfreitas** [comment]
by listing your photos: https://documentation.onfido.com/#list-live-photos

**Comment by tcpickard94** [comment]
Sorry for the late reply. I have tried making a request to `https://api.onfido.com/v2/live_photos` with my test api token and an applicant id but am getting `{"error":{"type":"validation_error","message":"There was a validation error on this request","fields":{"file_size":["must be between 1 KB and 4 MB"],"attachment":["can't be blank"]}}}`
I can view and download the photo from the dashboard so it is definitely getting uploaded

**Comment by rfreitas** [comment]
Hi @tcpickard94, this issue somehow slipped though the cracks. I'm guessing your issue has been resolved or is no longer relevant?
