### ISSUE TITLE
SDK Layout Issue

### ISSUE THREAD

**Issue by pouriabagheri** [onfido/onfido-android-sdk#20]
#### What was the expected behaviour?
display identity verification screen 
<img src="https://user-images.githubusercontent.com/5735478/39116999-6c2f7b90-4718-11e8-9f57-04b0c3ab46b9.png" width="200"  />

#### What happened instead?
UI Offset to far right showing only edge of the the button
<img src="https://user-images.githubusercontent.com/5735478/39117220-0cd89edc-4719-11e8-8690-3808e89e2304.png" width="200"  />
#### Version info:
- `onfido-capture-sdk` version: com.onfido.sdk.capture:onfido-capture-sdk:+ -> 3.0.0
- Android API version(s): 16 to 27
- `compileSdkVersion`: 27
- `targetSdkVersion`: 25
- `minSdkVersion`: 16
- Support library version (if applicable): 
#### Other useful info:
Note that this is happening when we integrate your SDK to our app. however it seams that the stand alone SDK functions as intended
 as shown in the gif below:
1) start onfido flow
2) take passport picture
3) expected to show liveliness test message but the screen not in right place ( by pressing on the edge of the button on right side of the screen goes to next step for video capture)
4) press back it goes back to the liveliness test message screen ( this time shows centered as expected ) press continue to video capture
5) compelte video challenge
6) similar issue on upload screen
7) press edge of the button on the right side of the screen and uploads the video.
<img src="https://user-images.githubusercontent.com/5735478/39119564-bf7feea0-471e-11e8-9702-36a8cf082de8.gif" width="300"  />

**Comment by sergiomarquesmoura** [comment]
Hello @pouriabagheri 
Is there any chance that you have some of the following files in your resources?
`slide_in_left.xml`
`slide_in_right.xml`
`slide_out_left.xml`
`slide_out_right.xml`

It might be that you are overriding one of our animation resources. We are actively working on prefixing all our resources to avoid such conflicts, but that's an ongoing work that we expect to finish in the next few days.

**Comment by pouriabagheri** [comment]
Hi @sergiomarquesmoura 
Yes you are right. I have renamed my animation files for time being
Thanks

**Comment by sergiomarquesmoura** [comment]
As I said, we will soon prefix all our resources so this won't happen anymore. Will update you once we release it
