### ISSUE TITLE
Onfido Logo

### ISSUE THREAD

**Issue by ahmednawaz22** [onfido/onfido-android-sdk#202]
Hi,
 Can we hide/remove Onfido logo in Screens or Is there any support to do this?

Thanks & Regards

**Comment by andra-radu** [comment]
Hi @ahmednawaz22 - Hide Onfido logo is an enterprise feature which can be enabled on your account. In order to do that, please get in contact with your customer success manager at client-support@onfido.com

**Comment by ahmednawaz22** [comment]
@andra-radu, thank you for prompt response.
