### ISSUE TITLE
Unable to select National Identity Card in Zambia

### ISSUE THREAD

**Issue by xrigau** [onfido/onfido-android-sdk#204]
#### What was the expected behaviour?
According to the [Onfido Supported Documents](https://onfido.com/supported-documents/) portal, the National Identity Card document type is one of the supported documents in Zambia:

![image](https://user-images.githubusercontent.com/1626673/171818274-f3a7e4d6-75fd-4a81-9e7e-c597545233d6.png)

This means that the user should be able to select that they're in Zambia and then they should be able to select the National Identity Card as their document for the ID verification.

#### What happened instead?

After selecting Zambia as the country, the user is only able to select Passport or Driver's license, but not the National Identity Card.

#### Version info:

- `onfido-capture-sdk` version: `com.onfido.sdk.capture:onfido-capture-sdk-core:12.2.0`
- Android API version(s): Any

- `compileSdkVersion`: 31
- `targetSdkVersion`: 31
- `minSdkVersion`: 27
- Support library version (if applicable): N/A

#### Steps to reproduce:

1. Start Onfido flow.
2. Select country: Zambia.
3. Observe 'National Identity Card' is not an option in the available document types.

#### Onfido Flow initialization code:

```kotlin
val tokenExpirationHandler = // ...
    val config = OnfidoConfig.builder(context)
        .withSDKToken("token", tokenExpirationHandler)
        .build()
    val intent = onfido.createIntent(config)
    startActivity(intent)
```

#### Issue severity information (number of users/crashes if applicable):

This will lead to a bad UX. Users won't understand why they can't use their National identity Card.
The SDK should comply with the rules specified in the official Onfido documentation.

#### Additional LogCat output:

N/A

#### Other useful info:

(Ignore the overridden string for Driver's license).

<img alt="zambia" src="https://user-images.githubusercontent.com/1626673/171821249-4bb555cf-58b9-470c-8b1e-feb877702da9.png" width="320px" />

**Comment by andra-radu** [comment]
Hi @xrigau - I was able to reproduce the issue reported by you and I have raised this with our SDK team to add Zambia - NIC in the list. I will let you know once this is done.

**Comment by xrigau** [comment]
Thank you @andra-radu

**Comment by gurpreet-onfido** [comment]
Hello Xavi,

Greetings for the day!

Please be informed that we will be releasing the SDK version 12.3.0 in which you will be able to find National ID Card for Zambia.

Please let us know if there is anything else we can help you with.

Kind regards
Gurpreet Singh

**Comment by xrigau** [comment]
Great, thank you @gurpreet-onfido !
