### ISSUE TITLE
Document Capture step missing from Welcome Screen step summary

### ISSUE THREAD

**Issue by sachin4203** [onfido/onfido-android-sdk#205]
#### What was the expected behaviour?
The document capture step must be shown in the step summary on Welcome step screen.

#### What happened instead?
In case of custom document capture step, step summary does not include Document Capture Step on Welcome step screen (Check screenshots attached below).

#### Version info:

- `onfido-capture-sdk` version: 12.2.0
- Android API version(s):

- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 23
- Support library version (if applicable):

#### Steps to reproduce:

- Start the Onfido verification flow
- Welcome Step screen is shown
- Document capture step is missing from steps summary

I was also able to replicate this issue on the Onfido Sample App.

#### Onfido Flow initialization code:

```
       FlowStep faceCaptureStep = getFaceCaptureStep(onfidoProviderConfig.getSelfieConfig());
       FlowStep[] customSteps =  new FlowStep[] {
                    FlowStep.WELCOME,
                    getDocumentCaptureStep(documentType, countryCode),
                    faceCaptureStep
            };
        }
        final OnfidoConfig config = OnfidoConfig.builder(activity)
                .withCustomFlow(customSteps)
                .withSDKToken(sdkToken, new OnfidoTokenExpirationHandler())
                .exitWhenSentToBackground()
                .build();

        mOnfidoClient.startActivityForResult(activity, ONFIDO_REQUEST_CODE, config);
```

```
private FlowStep getFaceCaptureStep(String selfieConfig) {
        switch (selfieConfig.toLowerCase()) {
            case SELFIE_CONFIG_PHOTO:
                return FaceCaptureStepBuilder.forPhoto().withIntro(false).build();
            case SELFIE_CONFIG_VIDEO:
                return FaceCaptureStepBuilder.forVideo().withIntro(false).build();
            default:
                return null;
        }
    }
```

```
fun getDocumentCaptureStep(documentType: DocumentType, countryCode: CountryCode): FlowStep {
    if (documentType == DocumentType.PASSPORT) {
        return forPassport().build()
    }
    return when (documentType) {
        DocumentType.VISA -> forVisa()
        DocumentType.RESIDENCE_PERMIT -> forResidencePermit()
        DocumentType.NATIONAL_IDENTITY_CARD -> forNationalIdentity()
        DocumentType.DRIVING_LICENCE -> forDrivingLicence()
        DocumentType.WORK_PERMIT -> forWorkPermit()
        else -> throw IllegalStateException("Unsupported document type")
    }.withCountry(countryCode).build()
}
```

#### Other useful info:

Expected Welcome Step Summary

<img width="250"  height="500" alt="Screenshot 2022-06-22 at 13 47 30" src="https://user-images.githubusercontent.com/9072850/175021877-0509dbbb-8c67-437c-9e4a-11ae80c38c9d.png">

Actual Welcome Step Summary (with Document Capture step missing)

<img width="250"  height="500" alt="Screenshot 2022-06-22 at 13 46 46" src="https://user-images.githubusercontent.com/9072850/175022229-9b9a1412-3948-4e25-9726-b5d2aec12f92.png">

**Comment by limnash-onfido** [comment]
Hi @sachin4203 We have a fix for the issue and it will be included in the next release. Thank you!
