### ISSUE TITLE
Proof of Address info not available in OnfidoResultListener

### ISSUE THREAD

**Issue by 39otrebla** [onfido/onfido-android-sdk#208]
#### What was the expected behaviour?

The `userCompleted` callback of the `OnfidoResultListener` should provide information about the document uploaded for Proof of Address, as the iOS SDK does.

In particular, the iOS SDK provides the following information about the document uploaded for PoA:
```swift
@objc(ONProofOfAddressResult) final public class ProofOfAddressResult : NSObject {
    @objc(id) final public let id: String
    @objc(type) final public let type: String
    @objc(issuingCountry) final public let issuingCountry: String?
    override final public var description: String { get }
}
```

#### What happened instead?

The `captures` result of `userCompleted` callback contains only information related to Identity Document upload.

#### Version info:

- `onfido-capture-sdk` version: 12.2.0
- Android API version(s): any

- `compileSdkVersion`: any
- `targetSdkVersion`: any
- `minSdkVersion`: any
- Support library version (if applicable): any

**Comment by 39otrebla** [comment]
Any feedback?

**Comment by gurpreet-onfido** [comment]
Hello @39otrebla 

Thank you for reporting this up. We will look into this and get back to you on this.

Kind regards
Gurpreet Singh

**Comment by gurpreet-onfido** [comment]
Hello @39otrebla 

Greetings for the day!

I have confirmed with our engineering team that they are working on this now. 

I will keep you posted with our progress. 

Kind regards
Gurpreet Singh

**Comment by 39otrebla** [comment]
@gurpreet-onfido thank you, keep us posted!

**Comment by gurpreet-onfido** [comment]
Hello @39otrebla Greetings for the day!

This is fixed in the SDK release https://github.com/onfido/onfido-android-sdk/releases/tag/13.1.0. 

Kind regards
Gurpreet Singh
