### ISSUE TITLE
Nested Transitive Dependencies

### ISSUE THREAD

**Issue by pouriabagheri** [onfido/onfido-android-sdk#21]
#### What was the expected behaviour? 
resolve the conflict automatically 
#### What happened instead?
Build Failed
#### Version info:

- `onfido-capture-sdk` version:
- Android API version(s):
com.onfido.sdk.capture:onfido-capture-sdk:+ -> 3.0.0
- `compileSdkVersion`:  27
- `targetSdkVersion`: 25
- `minSdkVersion`: 16
- Support library version (if applicable):

#### Steps to reproduce:
add implementation 'org.jetbrains:annotations-java5:15.0' to gradle

#### Additional LogCat output:
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForBetaDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
C:\Users\abc\Documents\app\build\intermediates\transforms\dexBuilder\beta\debug\0.jar, 
C:\Users\abc\Documents\app\build\intermediates\transforms\dexBuilder\beta\debug\1.jar, 
....
....
C:\Users\abc\Documents\app\build\intermediates\transforms\dexBuilder\beta\debug\117.jar
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 5s

```
#### Other useful info:
```
+--- org.jetbrains:annotations-java5:15.0 

+--- com.onfido.sdk.capture:onfido-capture-sdk:+ -> 3.0.0
|    +--- com.onfido.api.client:onfido-api-client:1.1.1
|    |    +--- com.squareup.okhttp3:okhttp:3.3.0 -> 3.9.0 (*)
|    |    +--- com.squareup.okhttp3:logging-interceptor:3.3.0 -> 3.9.0 (*)
|    |    +--- com.squareup.retrofit2:retrofit:2.1.0 -> 2.3.0 (*)
|    |    +--- com.squareup.retrofit2:converter-gson:2.1.0 -> 2.3.0 (*)
|    |    +--- com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0
|    |    |    +--- com.squareup.retrofit2:retrofit:2.1.0 -> 2.3.0 (*)
|    |    |    \--- io.reactivex.rxjava2:rxjava:2.0.0 -> 2.1.3 (*)
|    |    \--- com.google.code.gson:gson:2.6.2 -> 2.8.0
|    +--- com.android.support:appcompat-v7:23.4.0 -> 27.1.1 (*)
|    +--- com.android.support:design:23.4.0 -> 27.1.1 (*)
|    +--- com.mixpanel.android:mixpanel-android:5.0.0
|    +--- io.reactivex.rxjava2:rxandroid:2.0.1 (*)
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.1.1 -> 1.2.10
|         \--- org.jetbrains:annotations:13.0 
```

#### work around:
exclude org.jetbrains:annotations

**Comment by sergiomarquesmoura** [comment]
Hello @pouriabagheri 

The cause for this is that we are using 2 different dependencies (`annotations` vs `annotations-java5`) which have common classes (same package and name), causing a conflict detected at build time

I could successful overcome this by excluding the annotations package from our SDK, in case you really need the `annotations-java5`, i.e.:

```
implementation ("com.onfido.sdk.capture:onfido-capture-sdk:$sdkVersion") {
        exclude group: 'org.jetbrains', module: 'annotations'
    }
```

Is this what you did as well?

**Comment by pouriabagheri** [comment]
Hi @sergiomarquesmoura 
I have tried 
```
implementation ("com.onfido.sdk.capture:onfido-capture-sdk:$sdkVersion") {
        exclude group: 'org.jetbrains', module: 'annotations'
}
```
but it was still getting build error 
> program type already present org.intellij.lang.annotations.Flow
which lead me to exuding it in configurations
```
configurations {
        cleanedAnnotations
        compile.exclude group: 'org.jetbrains' , module:'annotations'
    }
```

**Comment by sergiomarquesmoura** [comment]
This is something I think we won't be able to exclude on our side soon, because it comes as part of one of our core dependencies, so for now I think the best is that we stick with this workaround
