### ISSUE TITLE
exclude group: not working on onfido android sdk

### ISSUE THREAD

**Issue by sghosh-91** [onfido/onfido-android-sdk#210]
#### What was the expected behaviour?
 implementation ('com.onfido.sdk.capture:onfido-capture-sdk-core:12.2.0'){
        exclude group: 'androidx.constraintlayout'
    }
It should exclude the constraitlayout version and pick from app version
#### What happened instead?
It is still using the constraint layout version 2.0.1 and not using the app constraint layout version 1.1.2
#### Version info:
12.2.0
- `onfido-capture-sdk` version:
capture-sdk-core:12.2.0
- Android API version(s):
- `compileSdkVersion`: 30
- `targetSdkVersion`: 30
- `minSdkVersion`: 21
- Support library version (if applicable): 28.0.0
 
#### Other useful info:
_screenshots, videos, etc._

**Comment by gurpreet-onfido** [comment]
Hello there!

Greetings for the day!

This issue was addressed in the Product support ticket. Hence, we are closing this issue here. 

Please feel free to reach out to us if you need any help.

Kind regards
Gurpreet Singh
