### ISSUE TITLE
Is something wrong with the latest release version name?

### ISSUE THREAD

**Issue by rygelouv** [onfido/onfido-android-sdk#219]
Not a technical issue but how come the version released 2 days ago is `13.0.1` while the latest before that was `13.2.0`?
https://github.com/onfido/onfido-android-sdk/releases

**Comment by shaubert** [comment]
![Screenshot 2022-11-02 at 18 33 50](https://user-images.githubusercontent.com/1733477/199561303-5a4c880d-5d0b-42bd-8acf-81d2223c5bf6.png)

**Comment by shaubert** [comment]
![Screenshot 2022-11-02 at 18 32 28](https://user-images.githubusercontent.com/1733477/199561608-dd4d7d40-20ef-4342-bac3-cec9c4f01634.png)

**Comment by shaubert** [comment]
Onfido team please share any updates regarding this issue

**Comment by gurpreet-onfido** [comment]
Hello there!

Greetings for the day!

13.2.0 is a minor release, while 13.0.1 is a patch. Depending on the bugs/issues we identify we can oblige to patch LTS versions even from 30 months ago. It is not uncommon to make a patch to older versions even after minor/major releases.

For the specific release here, we identified some customer crashes which we were asked by key customers to also patch in older versions and hence we released the version 13.0.1.

I hope this information helps!

Please let us know if there is anything else we can help you with.

Kind regards
Gurpreet Singh

**Comment by shaubert** [comment]
Hello. It's great that you release patches for the old versions. But you rewrote history with this patch. Please open https://github.com/onfido/onfido-android-sdk/blob/master/CHANGELOG.MD and try to find the 13.2.0 version.

![Screenshot 2022-11-11 at 11 17 43](https://user-images.githubusercontent.com/1733477/201319666-f22241c1-706c-4338-a555-b8571abe7e45.png)

**Comment by gurpreet-onfido** [comment]
Hello @shaubert 

Thank you for writing in.

I am checking this with our SDK engineering team will get back to you on this as soon as possible. 

Stay tuned!

Kind regards
Gurpreet Singh
