### ISSUE TITLE
Changelog no longer mentions version 15.x

### ISSUE THREAD

**Issue by denis-colliot** [onfido/onfido-android-sdk#231]
Latest version (15.x) has been completely removed from the `CHANGELOG.md` documentation (see [corresponding commit](https://github.com/onfido/onfido-android-sdk/commit/e9471f26e992ddaa69c4bb1907183701fda0e355)).

Is this normal? I was about to migrate to this version, should I migrate to version `14.x` instead?

**Comment by denis-colliot** [comment]
Any news on this topic?

**Comment by denis-colliot** [comment]
I see that the commit has eventually been reverted:

![image](https://user-images.githubusercontent.com/7382968/213655221-2fa0451c-c28b-4e7b-9133-943cf69a3e04.png)

**Comment by gurpreet-onfido** [comment]
Hello @denis-colliot 

This was an accidental auto update due an issue in one of our patch release scripts. It is reverted now as you mentioned. 15.x.x releases are our latest releases.
