### ISSUE TITLE
Programmatically Close Window

### ISSUE THREAD

**Issue by mattsputnikdigital** [onfido/onfido-android-sdk#232]
Can we get a function to close the Onfido window.

I am launching it from Capacitor and I need to be able to close the Onfido window if the user is logged out in Capacitor.

**Comment by andra-radu** [comment]
Hi @mattsputnikdigital - You can call the tearDown function to remove the SDK completely from the current webpage. You can find this in our documentation here:
https://documentation.onfido.com/sdk/web/#removing-the-sdk

**Comment by mattsputnikdigital** [comment]
Im using the Android SDK and launching it natively. I just need a way to close the Android activity.

I am not using the web sdk.

**Comment by andra-radu** [comment]
@mattsputnikdigital - I have double checked with our Android SDK team and they've mentioned that unfortunately the window it's not closable from outside of the SDK.
I apologise for the inconvenience. If you have any questions or concerns please let us know. I would be more than glad to assist you.
