### ISSUE TITLE
Crash on upload of invalid document

### ISSUE THREAD

**Issue by shaubert** [onfido/onfido-android-sdk#24]
#### What was the expected behaviour?
Error displayed to user

#### What happened instead?
Crash

#### Version info:
- `onfido-capture-sdk` version: 4.1.0
- Android API version(s): 27

- `compileSdkVersion`: 27
- `targetSdkVersion`: 27
- `minSdkVersion`: 19
- Support library version (if applicable): 27.1.1

#### Steps to reproduce:
1. Start identity verification
2. Pick passport type
3. On camera screen take a photo of wrong document (business card for example)
4. Click "my passport is readable" 

#### Onfido Flow initialization code:
OnfidoConfig.builder()
                    .withToken(apiKey)
                    .withApplicant(applicantId)
                    .withCustomFlow(arrayOf(FlowStep.CAPTURE_DOCUMENT))
                    .build()

#### Additional LogCat output:
java.lang.NullPointerException: Attempt to invoke virtual method 'com.onfido.api.client.data.ErrorData$Error com.onfido.api.client.data.ErrorData.getError()' on a null object reference
        at com.onfido.android.sdk.capture.ui.camera.a$a.onError(Unknown Source:3)
        at com.onfido.api.client.OnfidoAPI$Callback.onResponse(OnfidoAPI.java:123)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

#### Other useful info:
--

**Comment by sergiomarquesmoura** [comment]
Hi @shaubert , thanks for reporting this and sorry for the inconvenience.
Could you tell us how many crashes/users experienced this? Anyway we will start looking into it

**Comment by shaubert** [comment]
Hey @sergiomarquesmoura , there are few. Hopefully almost all users uploads real documents.

**Comment by sergiomarquesmoura** [comment]
@shaubert could you replicate it? Is it happening every time an invalid document is uploaded?

**Comment by shaubert** [comment]
yes I can, it happens every time.

**Comment by sergiomarquesmoura** [comment]
Are you running proguard on your build? It could be due to missing proguard rules. If so, could you try again with the following rule regarding Onfido classes?

```
-keep class com.onfido.** { *; }

**Comment by shaubert** [comment]
It's a debug build without proguard.

**Comment by cpetzel** [comment]
This is happening to us on our production app as well. Please fix.

**Comment by BelooS** [comment]
We have faced with the same issue. Waiting for a fix

**Comment by sergiomarquesmoura** [comment]
@BelooS just to confirm, are you seeing this on every invalid document upload or is it inconsistent, meaning that sometimes you just see the error for invalid document?

**Comment by shaubert** [comment]
I've got an update, it happen even on upload of valid docs. Please provide ETA for the fix.

**Comment by shaubert** [comment]
OK, so the original cause was the missing applicant id in OnfidoConfig. But anyway onfido sdk should not crash while parsing error from server. Also there is a small amount of crashes in our old version of the app where applicant id successfully passed to onfido. Looks like you always try to parse error from response even when body is empty.

**Comment by sergiomarquesmoura** [comment]
Hi @shaubert . Thanks for the update. 
The error handling issues were already fixed on our side and will be released soon. I will update you here once this is out

**Comment by sergiomarquesmoura** [comment]
Our latest version `4.2.0`, solving this issue (crash on an unexpected/malformed response) was just released.
Closing this
