### ISSUE TITLE
[18.0.0] OnfidoAnalyticsEventListener extends Parcelable

### ISSUE THREAD

**Issue by Bardiamist** [onfido/onfido-android-sdk#250]
I need to log analytic events.

I use this in React native so on event I need to call `mReactContext`.
```
    OnfidoEventListener(ReactApplicationContext reactContext) {
        this.mReactContext = reactContext;
    }
```

Looks `Context` can't be used when `OnfidoAnalyticsEventListener` extends from `Parcelable` (it introduced in onfido-android-sdk@18.0.0).

How to log analytic events now? I need to call method of context on event.

**Comment by onfido-seyedjafari** [comment]
The `OnfidoAnalyticsEventListener` was serializable before this version and now a Parcelable.
In none of the above cases you can not hold Context as a parameter in your class extending from `OnfidoAnalyticsEventListener`.

The signature of the `onEvent` function of the `OnfidoAnalyticsEventListener` has changed to: 
`applicationContext: Context, event: OnfidoAnalyticsEvent` 

Using the context provided you can access all the resources you require.
However starting from version 17 our SDK runs in a separate process which blocks direct communication using the callback interfaces.

If you need to call any of the React components you need a IPC mechanism.

Our suggestion is to go with [ResultReceiver](https://developer.android.com/reference/android/os/ResultReceiver)

PS: I suggest you to have a look at ReactNative SDK which in the coming release will add support for analytics callback

**Comment by Bardiamist** [comment]
>However starting from version 17 our SDK runs in a separate process which blocks direct communication using the callback interfaces.

Yea, I nooticed that my communication broken and in 17 so reverted to 16.3.2

>I suggest you to have a look at ReactNative SDK which in the coming release will add support for analytics callback

I use Onfido before ReactNative SDK was existed. I need analytics events year ago. If it implemented in ReactNative SDK I'd look at this but now looks it still not implemented.

**Comment by Bardiamist** [comment]
Even in this repository no `withAnalyticsEventListener` example in the `sample-app` and the documentation the README.md about `withAnalyticsEventListener` is wrong.

**Comment by Bardiamist** [comment]
Thanks, it's good that you removed the Parcelable.
And thanks that you mentioned about `onCreate` but:
1. Why a note about `onCreate` not added into release description as breaking change?
2. Why it not added into `CHANGELOG.MD`?
3. Why it even not added into `MIGRATION.md`?
4. Why it even not added into https://github.com/onfido/react-native-sdk#getting-started ?
5. Where to get `isOnfidoProcess()` on `Java`?
