### ISSUE TITLE
Infinite loop on national ID capture with Redmi Note 9

### ISSUE THREAD

**Issue by rocklass** [onfido/onfido-android-sdk#264]
#### What was the expected behaviour?
User can submit his ID without any issue

#### What happened instead?
At the end of the flow, the ID check is restarted from the beginning so we didn't receive the activity result

#### Version info:

- `onfido-capture-sdk` version: 19.0.0
- Android API version(s): 29

- `compileSdkVersion`: 33
- `targetSdkVersion`: 33
- `minSdkVersion`: 23
- Support library version (if applicable): N/A

#### Steps to reproduce:
- Start Onfido flow with capture National ID step
- Capture the front
- Submit
- Capture the back
- Submit

#### Onfido Flow initialization code:
```
val configuration = with(OnfidoConfig.builder(activity)) {
    val captureScreenStep = when (documentType) {
        DocumentTypeNav.PASSPORT -> DocumentCaptureStepBuilder.forPassport()
        DocumentTypeNav.NATIONAL_ID -> DocumentCaptureStepBuilder.forNationalIdentity()
        DocumentTypeNav.DRIVING_LICENSE -> {
            val countryCode = runCatching {
                CountryCode.valueOf(localeProvider.getCountryKey())
            }.getOrNull()
            DocumentCaptureStepBuilder.forDrivingLicence().apply {
                countryCode?.let {
                    withCountry(countryCode)
                }
            }
        }
        else -> DocumentCaptureStepBuilder.forGenericDocument()
    }.build()
    val steps: Array<FlowStep> = when (selfieType) {
        PICTURE -> arrayOf(captureScreenStep, FaceCaptureStepBuilder.forPhoto().build())
        VIDEO -> arrayOf(captureScreenStep, FaceCaptureStepBuilder.forVideo().build())
        else -> arrayOf(captureScreenStep)
    }
    withCustomFlow(steps)
    withSDKToken(token)
    withLocale(localeProvider.getConfiguredLocale())
    withAnalyticsEventListener(object : OnfidoAnalyticsEventListener {
        override fun onEvent(event: OnfidoAnalyticsEvent) {
            when(event.type) {
                OnfidoAnalyticsEventType.SCREEN -> {
                    Timber.i("Onfido screen: ${event.properties}")
                }
                OnfidoAnalyticsEventType.ERROR -> {
                    Timber.e("Onfido error: ${event.properties}")
                }
                else -> {}
            }
        }
    })
    build()
}

onfido.startActivityForResult(activity, captureRequestCode, configuration)
```

#### Other useful info:
Issue found on Redmi Note 9 (M2004J19C) on Android 10
No issue on the same device with version 13.3.1 of the SDK.
Not reproduced on other devices.

We didn't receive any error event with the `OnfidoAnalyticsEventListener` nor activity result.

https://github.com/onfido/onfido-android-sdk/assets/7993662/6da4b034-180b-4bab-b9b6-ed84fb4d0feb

**Comment by yhoffses** [comment]
Hello, could you please have a look to that issue?

**Comment by rocklass** [comment]
Hey @onfido-android-ci 👋 
I tested version 19.1.0 but the issue is still there 😢

**Comment by rocklass** [comment]
> Dear @rocklass , Do you only reproduce it when National ID is selected?

Yes only with National ID, no issue with passport capture on the same device.
