### ISSUE TITLE
19.x : Cannot resolve symbol

### ISSUE THREAD

**Issue by romainguefveneu** [onfido/onfido-android-sdk#268]
#### What was the expected behaviour?
We should be able to follow your [readme](https://github.com/onfido/onfido-android-sdk#typography).

#### What happened instead?

Cannot resolve symbol 'onfidoFontFamilyTitle' 
Cannot resolve symbol 'onfidoFontFamilyBody' 
Cannot resolve symbol 'onfidoFontFamilyDialogButton' 
Cannot resolve symbol 'onfidoFontFamilyToolbarTitle' 
Cannot resolve symbol 'onfidoFontFamilyButton' 

#### Version info:

- `onfido-capture-sdk` version: 19.1.0

#### Steps to reproduce:

- Follow your [readme](https://github.com/onfido/onfido-android-sdk#typography)
- It doesn't compile

After https://github.com/onfido/onfido-android-sdk/issues/238, please don't break style on each version.

**Comment by anshulkhattar** [comment]
Facing the same issue.
