### ISSUE TITLE
404 bitrise link

### ISSUE THREAD

**Issue by emartynov** [onfido/onfido-android-sdk#27]
Hi guys,

You have bitrise badge on this project that leads to 404 page. Is it because I don't have rights to see specific build or there is another issue?

**Comment by rfreitas** [comment]
Hi @emartynov ,

Yes, the bitrise has close permissions only to our team. However, it's still a good catch because we can remove the link.

**Comment by rfreitas** [comment]
Yes, our bitrise account is locked. And good spot on it pointing to a locked account.

**Comment by sergiomarquesmoura** [comment]
Solved it by removing the URL and keeping the badge
