### ISSUE TITLE
Cannot change text color for toolbar title and other text

### ISSUE THREAD

**Issue by fazal88** [onfido/onfido-android-sdk#273]
Need to keep Toolbar title text color as white and other text color.

Cannot keep different text color for body and title if toolbar is dark colored.

#### Version info:

- `onfido-capture-sdk` version: 19.1.0

<img width="399" alt="Screenshot 2023-08-11 at 10 55 25 PM" src="https://github.com/onfido/onfido-android-sdk/assets/21053367/10b0d73e-914e-4ba5-b8b8-5bb75730fce6">

**Comment by anshulkhattar** [comment]
Facing the same issue. Using - 

    `<style name="OnfidoActivityTheme" parent="OnfidoBaseActivityTheme">
        <item name="onfidoFontFamilyTitleAttr">@font/lettera_text_bold</item>
        <item name="onfidoFontFamilyBodyAttr">@font/lettera_text_medium</item>

        <item name="onfidoFontFamilySubtitleAttr">@font/lettera_text_regular</item>
        <item name="onfidoFontFamilyButtonAttr">@font/lettera_text_medium</item>
        <item name="onfidoFontFamilyToolbarTitleAttr">@font/lettera_text_medium</item>
    </style>`

**Comment by fazal88** [comment]
Any update on this
