### ISSUE TITLE
Status Bar Color Issue

### ISSUE THREAD

**Issue by romainguefveneu** [onfido/onfido-android-sdk#274]
#### What was the expected behaviour?

Correct Status Bar Color

#### What happened instead?

Incorrect Status Bar Color

#### Version info:

- `onfido-capture-sdk` version: 19.2.0
- Android API version(s): 34

#### Steps to reproduce:

Start OnfidoActivity

#### Other useful info:

<img src=https://github.com/onfido/onfido-android-sdk/assets/1233069/7767f206-d9a0-4a59-8182-f7437c0aebc4 width=300/>

**Comment by skaengus2012** [comment]
@romainguefveneu

You can modify your statusbar using style. 
```xml
<style name="OnfidoActivityTheme" parent="OnfidoBaseActivityTheme">
              <item name="colorPrimaryDark">#ff0000</item>
             <item name="android:windowLightStatusBar">true</item>
</style>
<style name="OnfidoDarkTheme" parent="OnfidoBaseDarkTheme">
              <item name="colorPrimaryDark">#ff0000</item>
             <item name="android:windowLightStatusBar">false</item>
</style>
```

**Comment by romainguefveneu** [comment]
@skaengus2012 Of course, but it's not up to us to fix the problems.

**Comment by mostafazakaria** [comment]
Dear @romainguefveneu,

The issue is happening because in your app you are setting `android:windowLightStatusBar` to true which makes the statusBar text color black and not visible on a dark background. We can fix this issue but setting this attribute to false in Onfido sdk themes like the following:

```xml
<style name="OnfidoActivityTheme" parent="OnfidoBaseActivityTheme">
    <item name="android:windowLightStatusBar">false</item>
</style>
<style name="OnfidoDarkTheme" parent="OnfidoBaseDarkTheme">
    <item name="android:windowLightStatusBar">false</item>
</style>
```

Best Regards,
Mostafa
