### ISSUE TITLE
Failed to resolve onfido sdk

### ISSUE THREAD

**Issue by Grzegorz-l90** [onfido/onfido-android-sdk#28]
Hi, I'm trying to implement onfido sdk in my app, but repository seems to by unreachable. 
I added `jcenter()` to repositories list but getting following error

`Failed to resolve: com.onfido.sdk.capture:onfido-capture-sdk:4.3.0`

**Comment by Gorbyy** [comment]
Hi,
Have you added `implementation 'com.onfido.sdk.capture:onfido-capture-sdk:+'` or `implementation 'com.onfido.sdk.capture:onfido-capture-sdk-core:+'` to your list of dependencies as well?

**Comment by Grzegorz-l90** [comment]
Adding maven url fixed the problem, thanks

**Comment by edenman** [comment]
Might be worth adding this to the README, it seems like the package still hasn't been approved by jcenter?

**Comment by sergiomarquesmoura** [comment]
Hi @edenman 
It's actually part of the README:

```
Notes:
Until these packages get approved to be included in JCenter, the following snippet must be used to instruct gradle to search for them on Bintray:

repositories {
  maven {
    url  "https://dl.bintray.com/onfido/maven"
  }
}
```
Anyway, we're looking forward to get it accepted soon

**Comment by edenman** [comment]
@sergiomarquesmoura gotcha.  I would've assumed you'd put it at the top of the "Adding the SDK dependency" section with the `jcenter()` part

**Comment by andreluizreis** [comment]
Hello, I would like to suggest an improvement. 

I try to import an old library and I always receive an error: 
```
Failed to resolve: com.onfido.sdk.capture:onfido-capture-sdk:4.6.0
```

Without this maven import, it never works: 
```
maven { url 'https://dl.bintray.com/onfido/maven' }
```
If I try to import an old library and it didn't work too. 

So, your statement is not true:
```
Please note that until these packages get approved to be included in JCenter, the following snippet must be used to instruct gradle to search for them on Bintray
``` 
I always need to add this line in my repository. So, my suggestion is to add this snippet code on your instructions over the `2. Adding the SDK dependency` or find another way to deliver the new release version to the public. 
Thanks.
