### ISSUE TITLE
SDK Crash on Android 5.1.1

### ISSUE THREAD

**Issue by cpetzel** [onfido/onfido-android-sdk#31]
#### What was the expected behaviour?
SDK doesn't crash

#### What happened instead?
RuntimeException

```
java.lang.RuntimeException View is not initialized, height:0 
    Unknown:-1 com.onfido.android.sdk.capture.ui.camera.OverlayView.getVerticalWeight
    Unknown:-1 com.onfido.android.sdk.capture.ui.camera.CaptureActivity$11.run
    Handler.java:739 android.os.Handler.handleCallback
    Handler.java:95 android.os.Handler.dispatchMessage
    Looper.java:135 android.os.Looper.loop
    ActivityThread.java:5254 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    Method.java:372 java.lang.reflect.Method.invoke
    ZygoteInit.java:903 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:698 com.android.internal.os.ZygoteInit.main
```
#### Version info:

- `onfido-capture-sdk` version:
    compile "com.onfido.sdk.capture:onfido-capture-sdk:4.3.0"

- Android API version(s):
Asus Nexus 7 5.1.1

- `compileSdkVersion`: 27
- `targetSdkVersion`: 27
- `minSdkVersion`: 18
- Support library version (if applicable):

#### Steps to reproduce:
backgrounding and foregrounding app during capture phase.

#### Other useful info:
_screenshots, videos, etc._

**Comment by sergiomarquesmoura** [comment]
Hi @cpetzel . Thanks for flagging this, we will try to replicate it with a similar device and we will get back to you ASAP

**Comment by sergiomarquesmoura** [comment]
@cpetzel is this happening everytime? We couldn't replicate it yet, since we don't have that device. Tried with the Nexus 7 emulator and cannot make it crash. Also, did you have "Don't keep activities" enabled? Or did you restrict the amount of background processes of your device?

**Comment by cpetzel** [comment]
Thanks for the quick reply. The recent issues I have opened originated from crashes our user's are having on production. That's why I have very limited reproduction steps.

It could be that the user foregrounded the app after a long time?

**Comment by sergiomarquesmoura** [comment]
@cpetzel we found the issue and we're launching a fix for it early next week. I'll update you here once it's live

**Comment by sergiomarquesmoura** [comment]
This issue is duplicated, see #10 . Closing and continuing the thread on the other one
