### ISSUE TITLE
Support compile & target SDK 28 and androidX

### ISSUE THREAD

**Issue by BelooS** [onfido/onfido-android-sdk#36]
#### What was the expected behaviour?
Apk compiles

#### What happened instead?
I have strange issue in `kaptGenerateStubsDebugKotlin` task that kotlin runtime can't find `DocumentType` class which is used in our code

```
error: cannot access DocumentType
    private final com.onfido.android.sdk.capture.DocumentType documentType = null;
                                                ^
  bad class file: /Users/olegbeloy/.gradle/caches/transforms-1/files-1.1/jetified-onfido-capture-sdk-core-4.2.0.aar/d3b8dc2c31bfb2c04419fed077ab8451/jars/classes.jar(com/onfido/android/sdk/capture/DocumentType.class)
    bad RuntimeInvisibleParameterAnnotations attribute: DocumentType(String,int,int,int,int)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
e: java.lang.IllegalStateException: failed to analyze: com.sun.tools.javac.util.Abort
    at org.jetbrains.kotlin.analyzer.AnalysisResult.throwIfError(AnalysisResult.kt:56)
    at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:131)
    at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:154)
    at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:51)
    at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:94)
          
Caused by: com.sun.tools.javac.util.Abort
	at com.sun.tools.javac.comp.Check.completionError(Check.java:287)
	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:584)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:638)
	at com.sun.tools.javac.comp.Attr.attribType(Attr.java:631)
```

#### Version info:
- `onfido-capture-sdk` version: 4.2.0

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 19
- `kotlin plugin version` : 1.2.71
- `androidX  version` : 1.0.0

I have integrated `AndroidX` to the project. Seems that it is a compatibility issue, because androidX namespace requires `compileSdk 28`, but the `OnfidoSdk` supports only `api 27`. 

Please provide support for 28 api (android Pie) & migrate to androidX instead of support library since them have been released.

**Comment by sergiomarquesmoura** [comment]
Hi @BelooS ! Thanks for pointing this. Indeed we don't support API 28 yet, but we'll look into it in the upcoming weeks. I'll update you later

**Comment by sergiomarquesmoura** [comment]
Hi again @BelooS . I was trying to replicate your issue, by creating a sample app with those specific dependencies and I couldn't replicate the issue, the app built fine. By adding 
```
android.enableJetifier=true
```

to your `gradle.properties` file you should be able to "jetify" our SDK and integrate without any problem. I see the error refers your caches. Can you check if invalidating your cache and performing a clean build helps in any way?

**Comment by pouriabagheri** [comment]
Having similar issue. which stopping us from upgrading to latest Onfido SDK as our other dependencies support androidX. it seems that jar file in Onfido SDK is not supporting the AndroidX even with `android.enableJetifier=true`

Here is the error Log:
`error: cannot access DocumentType
import com.onfido.android.sdk.capture.DocumentType;
                                     ^
  bad class file: C:\Users\PooryaBagheriFaez\.gradle\caches\transforms-1\files-1.1\jetified-onfido-capture-sdk-core-4.4.0.aar\dce609c395d91ca8d3c5cc86682b19e2\jars\classes.jar(com/onfido/android/sdk/capture/DocumentType.class)
    bad RuntimeInvisibleParameterAnnotations attribute: DocumentType(String,int,int,int,int)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
:app:compileBetaDebugJavaWithJavac FAILED
`

**Comment by sergiomarquesmoura** [comment]
Hi @BelooS @pouriabagheri @artemdrd We added support for AndroidX on our latest version `4.5.0`. Try it out when you have the chance please, closing this one.

**Comment by luis-cortes** [comment]
@sergiomarquesmoura Mind sharing what the fix that you applied to the enum was? I am running into a similar issue in our library and this is the only thread/page that I've found with a similar problem.

**Comment by jakubjerabek** [comment]
@luis-cortes Hi Luis, did you find any solution for this problem? Any help would be appreciated. Thank you.

**Comment by sergiomarquesmoura** [comment]
Hi @luis-cortes @jakubjerabek . For us, removing parameters from the enum constructor (placing them as abstract vals and overriding in each enum value instead) solved the issue

**Comment by jakubjerabek** [comment]
Thank you Sergio!
