### ISSUE TITLE
Error updating to latest version

### ISSUE THREAD

**Issue by gabrielamartinezu** [onfido/onfido-android-sdk#38]
I've been having this issue when attempting to update to latest version, any insights are appreciated, please let me know if you need more info

#### What was the expected behaviour?
Updating to latest version and build the project
#### What happened instead?
The project won't build
#### Version info:

- `onfido-capture-sdk` version: 4.5.0 (Although this error is reproducible from 4.1.0 with a larger stack trace but the main error is the same)
- Android API version(s):

- `compileSdkVersion`: 28
- `targetSdkVersion`: 27
- `minSdkVersion`: 19
- Support library version (if applicable):
28.0.0

We haven't migrated to androidX yet 

#### Steps to reproduce:
Attempting to update to any version above 4.0.0 and building

#### Onfido Flow initialization code:
n/a
#### Other useful info:

here is the xml extract 

```
 <Spinner
            android:id="@+id/inbox_menu"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            app:popupTheme="@style/AppTheme.PopupOverlay"
            />
```
Here is the stacktrace
```
Android resource linking failed
Output:  /Users/gabriela/Documents/couchsurfing-android/app/src/main/res/layout/screen_hosting.xml:69: error: resource style/AppTheme.PopupOverlay (aka com.couchsurfing.mobile.debug:style/AppTheme.PopupOverlay) not found.
/Users/gabriela/Documents/couchsurfing-android/app/src/main/res/layout/screen_inbox.xml:58: error: resource style/AppTheme.PopupOverlay (aka com.couchsurfing.mobile.debug:style/AppTheme.PopupOverlay) not found.
error: failed linking file resources.

Command: /Users/gabriela/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/e856a9d98584f6a34ddef3d327988c84/aapt2-3.2.1-4818971-osx/aapt2 link -I\
        /Users/gabriela/Library/Android/sdk/platforms/android-28/android.jar\
        --manifest\
        /Users/gabriela/Documents/couchsurfing-android/app/build/intermediates/merged_manifests/playDevDebug/processPlayDevDebugManifest/merged/x86_64/AndroidManifest.xml\
        -o\
        /Users/gabriela/Documents/couchsurfing-android/app/build/intermediates/processed_res/playDevDebug/processPlayDevDebugResources/out/resources-playDevX86_64Debug.ap_\
        -R\
        @/Users/gabriela/Documents/couchsurfing-android/app/build/intermediates/incremental/processPlayDevDebugResources/resources-list-for-resources-playDevX86_64Debug.ap_.txt\
        --auto-add-overlay\
        --java\
        /Users/gabriela/Documents/couchsurfing-android/app/build/generated/not_namespaced_r_class_sources/playDevDebug/processPlayDevDebugResources/r\
        --custom-package\
        com.couchsurfing.mobile\
        -0\
        apk\
        -c\
        zh-rCN,de,ar,ru,pt,en,it,fr,pl,es\
        --output-text-symbols\
        /Users/gabriela/Documents/couchsurfing-android/app/build/intermediates/symbols/playDev/debug/R.txt\
        --no-version-vectors
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0
 
```

**Comment by ramprasad-parajuli** [comment]
Hi Gabriela,



Thank you for reaching out. I am sorry to hear that you are not able to upgrade to the latest version of Onfido Android SDK, but I will be more than happy to assist you further.

As the error shows:
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0

It means you must have some error in your XML files (layout files or drawable files). Please check the recent history of your XML files.
right click on XML file-> Local history-> show History
or look for any error that XML file is showing.

screen_inbox.xml:58: error: resource style/AppTheme.PopupOverlay (aka com.couchsurfing.mobile.debug:style/AppTheme.PopupOverlay) not found.
And also refer to this error above in the screen_inbox.xml file.

Also, for future references, the best way to identify a problem is to Analyze -> Inspect code -> search for clues in the "Syntax error" and find the XML with an error.

I hope this helps.

Regards,
Ramprasad Parajuli
Technical Support Engineer

**Comment by gabrielamartinezu** [comment]
Thanks for your response, In the end it wasn't an issue with the XML syntax but a naming conflict with that particular style, this issue can be closed
