### ISSUE TITLE
Crashes when requesting user permissions for the camera

### ISSUE THREAD

**Issue by timt** [onfido/onfido-android-sdk#39]
#### What was the expected behaviour?
A dialog box should appear asking user for camera permissions

#### What happened instead?
The app crashed

#### Version info:
- `onfido-capture-sdk` version:
   4.5.0
- Android API version(s):
        buildToolsVersion = "28.0.3"
- `compileSdkVersion`: 28
- `targetSdkVersion`:28
- `minSdkVersion`: 19
- Support library version (if applicable): 27.1.1

#### Steps to reproduce:
- Start onfido process
- Choose passport
- Touch 'Enable Camera' button
- Bang

#### Onfido Flow initialization code:
        Onfido onfido = OnfidoFactory.create(reactContext).getClient();
        OnfidoConfig config = OnfidoConfig.builder()
                .withToken(ONFIDO_API_TOKEN)
                .withApplicant(applicantId)
                .withCustomFlow(new FlowStep[]{
                        FlowStep.WELCOME,                       //Welcome step with a step summary, Optional
                        FlowStep.CAPTURE_DOCUMENT,              //Document Capture Step
                        new FaceCaptureStep(FaceCaptureVariant.VIDEO),                  //Face Capture Step
                        FlowStep.FINAL                          //Final Screen Step, Optional
                })
                .build();
        onfido.startActivityForResult(this.getCurrentActivity(), 1, config);

#### Issue severity information (number of users/crashes if applicable):
     100% of users

#### Additional LogCat output:
12-17 12:27:23.476  5761  5761 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nivohub.nivo/com.onfido.android.sdk.capture.ui.camera.CaptureActivity}: java.lang.IllegalArgumentException: Given String is empty or null
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at android.app.ActivityThread.-wrap11(Unknown Source:0)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:105)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:164)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6541)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
12-17 12:27:23.476  5761  5761 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Given String is empty or null
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:5)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.auth.api.internal.zzcr.<init>(Unknown Source:2)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.auth.FirebaseAuth.<init>(Unknown Source:7)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.auth.internal.zzj.<init>(Unknown Source:1)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.auth.zzp.create(Unknown Source:3)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.components.Lazy.lambda$new$0(com.google.firebase:firebase-common@@16.0.4:43)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.components.Lazy$$Lambda$1.get(Unknown Source:4)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.components.Lazy.get(com.google.firebase:firebase-common@@16.0.4:54)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.components.AbstractComponentContainer.get(com.google.firebase:firebase-common@@16.0.4:26)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.components.ComponentRuntime.get(com.google.firebase:firebase-common@@16.0.4:34)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(com.google.firebase:firebase-common@@16.0.4:82)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.FirebaseApp.initializeAllApis(com.google.firebase:firebase-common@@16.0.4:761)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@16.0.4:359)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.face.FaceDetector.<init>(Unknown Source:25)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.common.di.SdkModule.provideFaceDetector(Unknown Source:7)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideFaceDetectorFactory.get(Unknown Source:10)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideFaceDetectorFactory.get(Unknown Source:0)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.dagger.internal.a.get(Unknown Source:15)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideCapturePresenterFactory.get(Unknown Source:52)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.common.di.SdkModule_ProvideCapturePresenterFactory.get(Unknown Source:0)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity_MembersInjector.injectMembers(Unknown Source:4)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity_MembersInjector.injectMembers(Unknown Source:2)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.common.di.DaggerSdkComponent.inject(Unknown Source:2)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.setupPresenter(Unknown Source:18)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at com.onfido.android.sdk.capture.ui.camera.CaptureActivity.onCreate(Unknown Source:134)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at android.app.Activity.performCreate(Activity.java:6975)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
12-17 12:27:23.476  5761  5761 E AndroidRuntime:    ... 9 more
12-17 12:27:23.612  1673  1998 W ActivityManager:   Force finishing activity com.nivohub.nivo/com.onfido.android.sdk.capture.ui.camera.CaptureActivity
#### Other useful info:
_screenshots, videos, etc._
![image](https://user-images.githubusercontent.com/506870/50087708-d7781880-01f8-11e9-9444-5fa7148a6195.png)

**Comment by justincrow** [comment]
This also happens if you have already granted camera permissions, so when you press one of the buttons in the image eg Passport
![image](https://user-images.githubusercontent.com/10811733/50094170-70fbf600-020a-11e9-9d11-713444537159.png)

**Comment by timt** [comment]
We have managed to resolve this by removing the following dependency from our build.gradle file:
             implementation 'com.google.firebase:firebase-auth:16.0.4'
Fortunately, we no longer depend on firebase-auth ourselves so do not need to provide it, but this may be an issue for any users of the Onfido sdk that do depend on it.

**Comment by seewah** [comment]
Thanks @timt for the update! We will be looking at a more comprehensive solution in the mean time.

**Comment by sergiomarquesmoura** [comment]
Hi @timt ! Many thanks for the message, it gave us good pointers on where to look at. We found the issue and a fix will be released in early January

**Comment by timt** [comment]
Great, thanks 👍

**Comment by sergiomarquesmoura** [comment]
Hi @timt  . Thanks for flagging this! 
We just released `4.5.1` which addresses this issue. Please try it out when you have a chance.
