### ISSUE TITLE
StrictMode error - resource not released. Application crash

### ISSUE THREAD

**Issue by paulkizdew** [onfido/onfido-android-sdk#42]
#### What was the expected behaviour?
Application doesn't crash

#### What happened instead?
Application crash

#### Version info:

- `onfido-capture-sdk` version: 4.5.0
- Android API version(s): 27

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 21
- Support library version (if applicable): 28.0.0

#### Steps to reproduce:
1. Start Onfido activity for result with these flow steps, CAPTURE_DOCUMENT and CAPTURE_FACE
2. On Onfido Activity select Passport.
3. Short after camera view is displayed, application crashes
#### Onfido Flow initialization code:
        val flowStepsWithOptions = arrayOf(
                FlowStep.CAPTURE_DOCUMENT,
                FlowStep.CAPTURE_FACE)
        val onfidoConfig = OnfidoConfig.builder()
                .withApplicant(applicantId)
                .withCustomFlow(flowStepsWithOptions)
                .withToken(BuildConfig.ONFIDO_TOKEN)
                .build()
        onfidoClient.startActivityForResult(activity, 1, onfidoConfig)
#### Additional LogCat output:
[onfido_crash.txt](https://github.com/onfido/onfido-android-sdk/files/2759801/onfido_crash.txt)

#### Other useful info:
_screenshots, videos, etc._

**Comment by burakeregar** [comment]
We have fixed some rare crashes related to CameraAPI as part of version [7.2.0](https://github.com/onfido/onfido-android-sdk/releases/tag/7.2.0. Please let us know if you can reproduce the issue on the latest version.
