### ISSUE TITLE
How to show only certain documents select option? Need to show only Passport and voter Id in the document list

### ISSUE THREAD

**Issue by ShrawanLakhe** [onfido/onfido-android-sdk#44]
This is not a bug but a query on onfido document list. Right now, in the documents list, all of the available supported documents are shown . I want to show only passport and voter id in the documents list and rest should not be available in the screen. 

How can i do that? In the documentation ,there is not anything related to that configurations?

Also, i want to show the specific country at the top of the countries list? Is that possible and if yes, can you point to the specific resources that i can reference to solve the above points

**Comment by sergiomarquesmoura** [comment]
Hi @ShrawanLakhe . This feature is in our mid-term roadmap, but not available yet. If you really want to restrict the document type, right now we suggest that you implement your own UI and then use our document preselection feature, through the `CaptureScreenStep` class.

**Comment by mattsputnikdigital** [comment]
Was this feature ever added?
