### ISSUE TITLE
Onfido 4.5.0 and up is not compatible with Play Services 16.+

### ISSUE THREAD

**Issue by SemenovAlexander** [onfido/onfido-android-sdk#45]
#### What was the expected behaviour?
Our app uses various Play services dependencies with version 16.0.0. The issue is Onfido SDK adds hard dependency to Play Services v.15.0

#### What happened instead?
After update onfido SDK to v.4.6.0 gradle sync fails with following message:
`The library com.google.android.gms:play-services-base is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
`
Same applies to 4.5.0 and 4.5.1

#### Version info:

- `onfido-capture-sdk` version: 4.6.0
- Android API version(s): any

- `compileSdkVersion`: 28
- `targetSdkVersion`: 26
- `minSdkVersion`: 19
- Support library version (if applicable):

#### Other useful info:
_screenshots, videos, etc._

**Comment by sergiomarquesmoura** [comment]
Hi @SemenovAlexander . Can you give me a list of the play services dependencies you're using at the 16+ version?

**Comment by SemenovAlexander** [comment]
Hi @sergiomarquesmoura thanks for quick response. Sure, we use following play dependencies: 
maps (16.0.0), tagManager(16.0.4), location (16.0.0), analytics (16.0.4), nearby (16.0.0).
We also use firebase core (16.0.4) and messaging (17.3.3), which adds dependency to play-services-base 16.0.1.

Locking dependency causes same error to be rised by play services gradle plugin.

**Comment by SemenovAlexander** [comment]
It appears the issue is related to AndroidX. 
We've recently migrated (using androidX dependencies 1.0.0), and I've tried to revert back before migration - sync and compile passes fine.

**Comment by sergiomarquesmoura** [comment]
Alright, I could replicate your issue with your set of dependencies.
I got the following error when using the version `4.2.0` of the `google-services` plugin:

```
Dependency failing: com.google.android.gms:play-services-flags:15.0.1 -> com.google.android.gms:play-services-basement@[
15.0.1], but play-services-basement version was 16.0.1.
```

I could fix it by explicitly setting the following dependency:
`implementation 'com.google.android.gms:play-services-flags:16.0.1'`

Could you tell me if it helps in your case?

**Comment by SemenovAlexander** [comment]
Yes, that fixed the issue, thanks a lot!
We used play services plugin `4.1.0` and that's why error message was different.
