### ISSUE TITLE
Can't start OnfidoActivity (on Xamarin)

### ISSUE THREAD

**Issue by ignasbagdonas** [onfido/onfido-android-sdk#5]
Hello, 

I tried to setup your sdk into our application. I everything setup by example, but when I try to start activity (onfido.startActivityForResult(..)) ran into following error:
`Unable to start activity ComponentInfo{com.cbs.citybee/com.onfido.android.sdk.capture.ui.OnfidoActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.ContentFrameLayout.setId(int)' on a null object reference`

**Comment by rfreitas** [comment]
Hello,

It's possibly a dependency version conflict.
Can you tells us your host app dependencies, namely if you have android support or play services (and their versions as well).

Ricardo

**Comment by ignasbagdonas** [comment]
First of all, I should tell that we are working on Xamarin platform. So we're created Xamarin Android Library binding to your aar and jar archyves. So there could be more problems than dependency version conflict, but we want to try.

Okay. Yes, you're right. I created new empty sample app and added up to date Android.Support libs. Anyway, now on the same step (onfido.startActivityForResult(..)) ran into:
`Java.Lang.ClassNotFoundException: Didn't find class "dagger.internal.Preconditions"`

**Comment by rfreitas** [comment]
I see. We were able to create a xamarin project a while a go for our sdk, but it was for a previous version.

Some tips from what I can recall. Try to miminise the number of jars you include and instead use the equivalent dependency from nuget. We hit a bug where the nuget dependencies has to be included both in the library, the sdk wrapper, and the sample app.

For dependencies where are not on nuget, the best is to exclude them from the automatic c# bridge.

Is dagger on nuget?

**Comment by ignasbagdonas** [comment]
In our binding project we're included only your libs: 
onfido-api-client-0.3.jar and onfido-capture-sdk-2.0.0.aar

After success binding project compilation first runtime error was ClassNotFoundException for kotlin standart library. We're added it from nugget in main app project, and error go away. But dagger isn't exist on nugget. I tried include dagger-compiler-2.0.jar into main app project with AndroidJavaLibrary build action, but then I got compilation error:

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error: java.lang.NoClassDefFoundError :  com/google/common/collect/SetMultimap (SampleApp)`

So here looks like we should collect all dependencies which you use in your libs.
Can you provide all dependencies list?

**Comment by rfreitas** [comment]
from our POM file
```
  <dependencies>
    <dependency>
      <groupId>com.onfido.api.client</groupId>
      <artifactId>onfido-api-client</artifactId>
      <version>0.8.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.google.android.gms</groupId>
      <artifactId>play-services-vision</artifactId>
      <version>8.4.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>appcompat-v7</artifactId>
      <version>23.4.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>design</artifactId>
      <version>23.4.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.mixpanel.android</groupId>
      <artifactId>mixpanel-android</artifactId>
      <version>5.0.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.reactivex.rxjava2</groupId>
      <artifactId>rxandroid</artifactId>
      <version>2.0.1</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <version>1.1.1</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.google.dagger</groupId>
      <artifactId>dagger</artifactId>
      <version>2.10</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

Some of these dependencies might in turn have their own dependencies, but if you get it from nuget, it will be taken care of automatically. Dagger is a standalone dependency, so it shouldn't case you problems on that front.

**Comment by ignasbagdonas** [comment]
Thanks. There is one more dependency: JetBrains.Annotations
I have added all of them. dagger as jar and other else from nugget.

So problem with dagger solved, but now I have another issue. 
`Java.Lang.ClassNotFoundException: Didn't find class "com.onfido.android.sdk.capture.common.di.SdkModule_ProvideSdkContextFactory"`

I looked into my bindings generated src and I have no idea why BindingsGenerator does not created all `SdkModule_...` classes. I see only classes without `_` in name.

**Comment by rfreitas** [comment]
that is weird. what warnings does xamarin give you?
It also looks like code that you don't need to interact with, so it doesn't need the bridge.

This is our `Transforms / Metadata.xml` for and older version of the sdk:
```
<metadata>
  <!--
  This sample removes the class: android.support.v4.content.AsyncTaskLoader.LoadTask:
  <remove-node path="/api/package[@name='android.support.v4.content']/class[@name='AsyncTaskLoader.LoadTask']" />
  
  This sample removes the method: android.support.v4.content.CursorLoader.loadInBackground:
  <remove-node path="/api/package[@name='android.support.v4.content']/class[@name='CursorLoader']/method[@name='loadInBackground']" />
  -->
  <remove-node path="/api/package[@name='com.monadtek.mvp']" />
  <!--remove-node path="/api/package[@name='com.onfido.android.sdk.capture']/class[@name='OnfidoImpl']" /-->
  <remove-node path="/api/package[@name='com.onfido.android.sdk.capture.ui.applicant']" />
  <remove-node path="/api/package[@name='com.onfido.android.sdk.capture.ui.camera']" />
  <remove-node path="/api/package[@name='com.onfido.android.sdk.capture.ui.camera.face']" />
  <remove-node path="/api/package[@name='com.onfido.android.sdk.capture.ui.docselection']" />
  <remove-node path="/api/package[@name='com.onfido.android.sdk.capture.ui']" />
  <remove-node path="/api/package[@name='com.onfido.android.sdk.capture.validation']" />
  <remove-node path="/api/package[@name='com.onfido.android.sdk.capture.repository']" />
  <remove-node path="/api/package[@name='com.onfido.android.sdk.capture.utils']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='ApplicantAPI']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='CheckAPI']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='ErrorParserImpl']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='MultipartDocumentRequestCreator']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='MultipartLivePhotoRequestCreator']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='MultiPartRequestCreator']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='OnfidoAPIImpl']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='OnfidoFetcher']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='UploadDocumentAPI']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='UploadLivePhotoAPI']" />
  <remove-node path="/api/package[@name='com.onfido.api.client']/class[@name='Url']" />
  <remove-node path="/api/package[@name='com.onfido.api.client.adapters']" />
</metadata>
```

**Comment by ignasbagdonas** [comment]
After Metadata.xml update error is different, but still relate with dagger.
`Java.Lang.ClassNotFoundException: dagger.internal.Factory ---> Java.Lang.NoClassDefFoundError: Failed resolution of: Ljavax/inject/Provider; ---> Java.Lang.ClassNotFoundException: Didn't find class "javax.inject.Provider" on path: DexPathList[[zip file "/data/app/com.onfido.xamarin.SampleApp-1`

Here is my clean binding project and sample app solution. Could you take a look and try to start app? Maybe you will succeed.
[https://drive.google.com/open?id=166BwG6daQsruBg-fYOZfzpkPblNBiFGN](https://drive.google.com/open?id=166BwG6daQsruBg-fYOZfzpkPblNBiFGN)

**Comment by rfreitas** [comment]
@ignasbagdonas I will get my windows VM spinning tomorrow and take a look at this!

**Comment by ignasbagdonas** [comment]
@rfreitas Thank you very much!

**Comment by rfreitas** [comment]
Hey @ignasbagdonas I took look, but I haven't been able to get it to run yet.
Some issues I spotted, dagger should be in the binding and there are some nuget references missing.

However, where I got is still not working, I'll make more time this week to look into it.

**Comment by rfreitas** [comment]
Hey @ignasbagdonas, an update. Unfortunately Xamarin does not do automatic bindings of the JVM language, this is key because we are using kotlin for some of our files which means those files cannot be bridged into C#.
However there are ways, possibly: in the meantime we can produce a sample app of the sdk version 0.6.0 (no kotlin back then) and later convert the public classes to java so that hopefully if not other problem comes up, we can create the bindings.

**Comment by rfreitas** [comment]
Hey Ignas, so we got the bindings work. However, mixpanel is blocking the build due to a duplicate resource it has. Without that app the app builds, but crashes as expected.

Tomorrow, we might have a better idea of the next steps.

Current progress here: https://github.com/onfido/onfido-android-sample-app

**Comment by ignasbagdonas** [comment]
Hey, very thanks for it. We really hope, that we'll can use your sdk into our app. We're waiting good news!

**Comment by rfreitas** [comment]
I sent you the wrong link! here: https://github.com/onfido/onfido-xamarin-sample-app

**Comment by sergiomarquesmoura** [comment]
@ignasbagdonas we made some more fixes regarding those dependency conflicts and could get the sample app running fine on our side. Could you take a look?
https://github.com/onfido/onfido-xamarin-sample-app

**Comment by ignasbagdonas** [comment]
@sergiomarquesmoura Hi, thanks, I will check it now.

**Comment by ignasbagdonas** [comment]
Hi, @sergiomarquesmoura . I tried xamarin sample app. It's ok and scan document flow works.
Anyway, I am trying to implement result handler as your android sample app.

`[Activity(Label = "OnfidoSDKSampleApp", MainLauncher = true)]
    public class MainActivity : Activity
    {
        IOnfido client;

        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            FlowStep[] steps = { FlowStep.CaptureDocument, FlowStep.CaptureFace };

            // Set our view from the "main" layout resource
            SetContentView(Resource.Layout.Main);
            client = OnfidoFactory.Create(this).Client;

            Applicant applicant = Applicant.InvokeBuilder().WithFirstName("Dummy").WithLastName("Dummy").Build();
            OnfidoConfig config = OnfidoConfig.InvokeBuilder()
                .WithApplicant(applicant)
                .WithToken("TOKEN")
                .WithCustomFlow(steps)
                .Build();
            client.StartActivityForResult(this, 1, config);
        }

        protected override void OnActivityResult(int requestCode, Android.App.Result resultCode, Android.Content.Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            client.HandleActivityResult(requestCode, data, new OnfidoResultListener());
        }
    }

    public class OnfidoResultListener : Java.Lang.Object, IOnfidoOnfidoResultListener
    {
        public void UserCompleted(Applicant p0, Captures p1)
        {
           //Not invoked
        }

        public void UserExited(ExitCode p0, Applicant p1)
        {
            //Not invoked
        }
    }`

UserCompleted and UserExited methods are never invoked. Do you have any ideas what's here wrong?

**Comment by sergiomarquesmoura** [comment]
Hey @ignasbagdonas so the error is:
you are currently calling `client.handleActivityResultCode(requestCode, ...)` but the argument must be the result code. Since the `OnActivityResult()` of Xamarin does not provide an integer for the result code, but instead an instance of `Result`, you should use `resultCode.getHashCode()`

**Comment by ignasbagdonas** [comment]
Thanks! Now everything works.
