### ISSUE TITLE
Theme customisation doesn't work on buttons

### ISSUE THREAD

**Issue by alextoudic** [onfido/onfido-android-sdk#50]
#### What was the expected behaviour?

Quoting from `README.md`:
```
onfidoPrimaryButtonColor: Defines the background color of the primary action buttons (e.g. proceed to the next flow step, confirm picture/video, etc), the color of the text on the secondary action buttons (e.g. retake picture/video) and the background color of some icons and markers during the flow

onfidoPrimaryButtonColorPressed: Defines the background color of the primary action buttons when pressed

onfidoPrimaryButtonTextColor: Defines the color of the text inside the primary action buttons
```

#### What happened instead?

Button's related colors don't apply, others work fine.

#### Version info:

- `onfido-capture-sdk-core` version: 4.2.0
- Android API version(s):

- `compileSdkVersion`: 28
- `targetSdkVersion`: 27
- `minSdkVersion`: 21
- Support library version (if applicable): 28.0.0

#### Steps to reproduce:

`colors.xml` file:
```
<resources>
  <color name="onfidoColorPrimary">#0000ff</color>
  <color name="onfidoColorPrimaryDark">#0000ff</color>
  <color name="onfidoTextColorPrimary">#ffffff</color>
  <color name="onfidoTextColorSecondary">#ffffff</color>
  <color name="onfidoColorAccent">#0000ff</color>
  <color name="onfidoPrimaryButtonColor">#0000ff</color>
  <color name="onfidoPrimaryButtonColorPressed">#2437dc</color>
  <color name="onfidoPrimaryButtonTextColor">#ffffff</color>
</resources>
```

#### Other useful info:

Rendering:
![image](https://user-images.githubusercontent.com/2766268/54273081-62ad4400-4585-11e9-86e9-391577575cc6.png)

I'm using `react-native@0.58.3` and the SDK is wrapped in an external native module

**Comment by sergiomarquesmoura** [comment]
Hi @alextoudic . This feature was added on version `4.4.0`, as our changelog states [here](https://github.com/onfido/onfido-android-sdk/blob/master/CHANGELOG.MD#440)
