### ISSUE TITLE
Expose selfie in callback

### ISSUE THREAD

**Issue by fphilipe** [onfido/onfido-android-sdk#59]
Currently (version 4.8.0), only the scanned document is available in the callback `OnfidoResultListener`. But we also need to get the selfie that the user took.

For context, we extract the image IDs of the document's front and back and the image ID of the selfie and post those to our backend, which then initiates the check and downloads these images for our own UI.

The fact that this is not available took us a bit by surprise. We first implemented this on iOS, where it is available:

```
public enum OnfidoResponse {
    case success([OnfidoResult])
    case cancel()
    case error(Error)
}

public enum OnfidoResult {
    case document(DocumentResult)
    case applicant(ApplicantResult)
    case face(FaceResult)
}
```

Either I'm missing something obvious here or the SDKs do not have feature parity.

If the latter is the case, is there any chance that you could expose the selfie in `OnfidoResultListener`?

Thanks.

**Comment by seewah** [comment]
Hi sorry this is a bug, which we will fix in upcoming releases. For now, I would recommend you just download the last selfie using https://documentation.onfido.com/#list-live-photos, which is what most of customers do when they need copies of the images. Apologies for the inconvenience

**Comment by fphilipe** [comment]
Thanks @seewah for the quick response. Do you have an ETA for the next release? That would help us in deciding whether a workaround is needed for the time being.

**Comment by fphilipe** [comment]
@seewah sorry to bother you, but an ETA would help us immensely.

**Comment by seewah** [comment]
At this stage, given the current backlog for our upcoming sprints, an ETA would be early-mid June. Does that work with your timeline?

**Comment by fphilipe** [comment]
@seewah, thanks! We'll have to introduce a workaround in the backend to fetch the image ID from your API then for the time being.

**Comment by AlexWink** [comment]
Hello, I'm using your SDK and we would like to use this feature as we already use it in the iOS implementation. Any news on the development of this feature?
Thanks

**Comment by burakeregar** [comment]
Hi,

`Face` object has been added into the `Captures` class as part of [v5.4.0](https://github.com/onfido/onfido-android-sdk/releases/tag/5.4.0). 

I am closing the issue, but feel free to re-open it if you have any further questions.

**Comment by AlexWink** [comment]
Hi,

I'm sorry but I can't find the image in the Face object I got in the callback. All I have is the id of the image and its variant (PHOTO or VIDEO). FYI, I'm running on the version 7.2.0 of the SDK.

**Comment by burakeregar** [comment]
Hi @AlexWink,

Sorry for the confusion, we do not return the image binary in the iOS SDK as well. We only return the id so that you can fetch the image through our endpoints. Unfortunately, there is no plan for returning the binary in the result object in the near future.
