### ISSUE TITLE
onfidoPrimaryButtonTextColor doesn't change text color on primary buttons

### ISSUE THREAD

**Issue by freszu** [onfido/onfido-android-sdk#60]
#### What was the expected behaviour?
onfidoPrimaryButtonTextColor - changes the text color on button
#### What happened instead?
text stays white - only the steps numbers color changed.
Looking into code this value is used only on onfido_liveness_control_button and onfido_bullet_step_view.
#### Version info:

- `onfido-capture-sdk` version: 4.8.0
- Android API version(s): 9.0

#### Steps to reproduce:
<details>
<summary>Screenshots</summary>

![Screenshot_20190510-165833](https://user-images.githubusercontent.com/12448300/57543541-f2d4f300-7354-11e9-8623-0531bc1826cd.jpg)
![Screenshot_20190510-165802](https://user-images.githubusercontent.com/12448300/57543542-f36d8980-7354-11e9-9c82-90d87c6ab1a2.jpg)

</details>
#### Other useful info:
_screenshots, videos, etc._

**Comment by sergiomarquesmoura** [comment]
Hi @freszu . Thanks for reporting this. This was a bug introduced in the latest version, 4.8.0. A fix is already being reviewed and we should launch a patch version at the beginning of next week. Apologies for the inconvenience, I will comment in this issue once the new version is out.

**Comment by sergiomarquesmoura** [comment]
Hi @freszu . We released the version `4.8.1` of our SDK, which solves this issue. Please try it out once you have the chance
