### ISSUE TITLE
Where i create new account to get token and other details. I couldn't find it in onfido. Help me!!

### ISSUE THREAD

**Issue by ajaycseng** [onfido/onfido-android-sdk#62]
#### Version info:

- `onfido-capture-sdk` version:
- Android API version(s):

- `compileSdkVersion`:
- `targetSdkVersion`:
- `minSdkVersion`:
- Support library version (if applicable):

#### Other useful info:
_screenshots, videos, etc._

**Comment by Gorbyy** [comment]
Hi @ajaycseng,

Please contact client-support@onfido.com for any questions related with your account.

Thanks in advance
