### ISSUE TITLE
Right-to-left support

### ISSUE THREAD

**Issue by mattmook** [onfido/onfido-android-sdk#63]
#### What was the expected behaviour?
When using the library with a right-to-left language, such as Arabic, we expect the layouts to appear mirrored.

#### What happened instead?
Layouts appear corrupted. Indeed looking at the source for the various layouts it can be seen that the code uses marginLeft/Right, paddingLeft/Right etc rather than declaring marginStart/End, paddingLeft/Right etc as would be expected to correctly support RTL.

#### Version info:

- `onfido-capture-sdk` version: 4.8.0
- Android API version(s): 25

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 19

#### Steps to reproduce:
Setup Onfido with translations in a right-to-left language and navigate through a flow.

#### Issue severity information (number of users/crashes if applicable):
All users of right-to-left languages.

#### Other useful info:
DocumentSelectionFragment
![DocumentSelectionFragment](https://user-images.githubusercontent.com/182422/58540720-e1636600-81f1-11e9-8a6a-8238b274d7c1.png)

FaceIntroFragment
![FaceIntroFragment](https://user-images.githubusercontent.com/182422/58540754-ec1dfb00-81f1-11e9-9543-3e1b89cebf03.png)

CaptureActivity
![CaptureActivity](https://user-images.githubusercontent.com/182422/58540777-f4763600-81f1-11e9-9fa7-7209770f3b48.png)

**Comment by seewah** [comment]
Unfortunately, the current SDK does not support RTL layout. It is in our backlog but it is not something we are likely to address in the near future, according to our current roadmap. However, please do discuss with your Onfido account manager if it is business priority for you.

See Wah

**Comment by sergiomarquesmoura** [comment]
Hi @mattmook . Just to add to the above, we indeed have the `android:supportsRtl` flag as `true` in our manifest. However, the SDK was not fully tested with RTL languages so it's indeed a feature request.

**Comment by mattmook** [comment]
Have temporarily copied the layouts to our project and fixed the offending layouts locally. Mainly changing `marginLeft` to `marginStart` etc with a couple of layouts needing a little more TLC.

I've attached the layout changes I've made. Obviously this does nothing regarding iconography, for example the chevrons on the document selection fragment point in the wrong direction, or any styles that need fixing. Changing the layouts at least makes the majority of the UI functional that I could easily test.

[onfido_rtl_layouts.zip](https://github.com/onfido/onfido-android-sdk/files/3234044/onfido_rtl_layouts.zip)

Anyway we will be following up with our account manager shortly.

**Comment by athkalia** [comment]
Hi @sergiomarquesmoura Any update on the above by any chance?

**Comment by RoyRewire** [comment]
@sergiomarqmoura It might be a good idea to change android:supportsRtl to false until you will support it

**Comment by MatthewPringle** [comment]
If the Onfido doesn't support RTL, why have it as part of the module?

It means everybody has to set their app to support RTL in order to compile. Which is not how it should be done.
