### ISSUE TITLE
XK country code not supported in com.onfido.android.sdk.capture.utils.CountryCode

### ISSUE THREAD

**Issue by renaudboulard** [onfido/onfido-android-sdk#68]
#### What was the expected behaviour?
`XK` Kosovo country code is no supported in `com.onfido.android.sdk.capture.utils.CountryCode`
#### What happened instead?
Crash when we call CountryCode.valueOf("XK")
```
Fatal Exception: java.lang.IllegalArgumentException
No enum constant com.onfido.android.sdk.capture.utils.CountryCode.XK
com.onfido.android.sdk.capture.utils.CountryCode.valueOf
```
#### Version info:

- `onfido-capture-sdk` version: 4.10.0
- Android API version(s): All

- `compileSdkVersion`: All
- `targetSdkVersion`: All
- `minSdkVersion`: All

#### Steps to reproduce:
call `CountryCode.valueOf("XK")`

The country code is for example  required for `CaptureScreenStep` 
```
CaptureScreenStep public constructor(documentType: com.onfido.android.sdk.capture.DocumentType, country: com.onfido.android.sdk.capture.utils.CountryCode) : com.onfido.android.sdk.capture.ui.options.FlowStep {
}
```

**Comment by ramprasad-parajuli** [comment]
Hi @renaudboulard, Thank you for reaching out to us.
The reason your application crashed is that we do not support any Documents from Kosovo country.
Please refer to this list where you can find out about the countries we support ID Documents from:
https://onfido.com/supported-documents/

**Comment by renaudboulard** [comment]
Hi @ramprasad-parajuli  thanks for your answer, unfortunately I don't think this is the issue, because in the list https://onfido.com/supported-documents/ there is 208 countries but in `com.onfido.android.sdk.capture.utils.CountryCode` classe there is 250 countries code

For example the country code `SJ` in`CountryCode` for Svalbard and Jan Mayen is in `CountryCode.class` but it's not in the list https://onfido.com/supported-documents/

**com.onfido.android.sdk.capture.utils.CountryCode list:**
```
    AD,
    AE,
    AF,
    AG,
    AI,
    AL,
    AM,
    AN,
    AO,
    AQ,
    AR,
    AS,
    AT,
    AU,
    AW,
    AX,
    AZ,
    BA
    BB,
    BD,
    BE,
    BF,
    BG,
    BH,
    BI,
    BJ,
    BL,
    BM,
    BN,
    BO,
    BQ,
    BR,
    BS,
    BT,
    BV,
    BW,
    BY,
    BZ,
    CA,
    CC,
    CD,
    CF,
    CG,
    CH,
    CI,
    CK,
    CL,
    CM,
    CN,
    CO,
    CR,
    CU,
    CV,
    CW,
    CX,
    CY,
    CZ,
    DE,
    DJ,
    DK,
    DM,
    DO,
    DZ,
    EC,
    EE,
    EG,
    EH,
    ER,
    ES,
    ET,
    FI,
    FJ,
    FK,
    FM,
    FO,
    FR,
    GA,
    GB,
    GD,
    GE,
    GF,
    GG,
    GH,
    GI,
    GL,
    GM,
    GN,
    GP,
    GQ,
    GR,
    GS,
    GT,
    GU,
    GW,
    GY,
    HK,
    HM,
    HN,
    HR,
    HT,
    HU,
    ID,
    IE,
    IL,
    IM,
    IN,
    IO,
    IQ,
    IR,
    IS,
    IT,
    JE,
    JM,
    JO,
    JP,
    KE,
    KG,
    KH,
    KI,
    KM,
    KN,
    KP,
    KR,
    KW,
    KY,
    KZ,
    LA,
    LB,
    LC,
    LI,
    LK,
    LR,
    LS,
    LT,
    LU,
    LV,
    LY,
    MA,
    MC,
    MD,
    ME,
    MF,
    MG,
    MH,
    MK,
    ML,
    MM,
    MN,
    MO,
    MP,
    MQ,
    MR,
    MS,
    MT,
    MU,
    MV,
    MW,
    MX,
    MY,
    MZ,
    NA,
    NC,
    NE,
    NF,
    NG,
    NI,
    NL,
    NO,
    NP,
    NR,
    NU,
    NZ,
    OM,
    PA,
    PE,
    PF,
    PG,
    PH,
    PK,
    PL,
    PM,
    PN,
    PR,
    PS,
    PT,
    PW,
    PY,
    QA,
    RE,
    RO,
    RS,
    RU,
    RW,
    SA,
    SB,
    SC,
    SD,
    SE,
    SG,
    SH,
    SI,
    SJ,
    SK,
    SL,
    SM,
    SN,
    SO,
    SR,
    SS,
    ST,
    SV,
    SX,
    SY,
    SZ,
    TC,
    TD,
    TF,
    TG,
    TH,
    TJ,
    TK,
    TL,
    TM,
    TN,
    TO,
    TR,
    TT,
    TV,
    TW,
    TZ,
    UA,
    UG,
    UM,
    US,
    UY,
    UZ,
    VA,
    VC,
    VE,
    VG,
    VI,
    VN,
    VU,
    WF,
    WS,
    YE,
    YT,
    ZA,
    ZM,
    ZW;
```

**Comment by renaudboulard** [comment]
@ramprasad-parajuli any news regarding this issue ?

**Comment by ramprasad-parajuli** [comment]
Hi @renaudboulard , I apologize for the delay in my response. 
You are correct. I confused the supported countries list with the com.onfido.android.sdk.capture.utils.CountryCode list. As the list was prepared a long time ago, initially we added a certain amount of countries. Our team is aware of the fact that some countries are missing from the list, and we will update the country list soon to include as many countries as possible.

**Comment by renaudboulard** [comment]
Hi @ramprasad-parajuli  thanks for your feedback! Any ETA for this fix ?

**Comment by gokhanaliccii** [comment]
@renaudboulard  Sorry for the late response, we're planning to fix the issue in Q3

**Comment by renaudboulard** [comment]
@gokhanaliccii Was the issue fixed in Q3?

**Comment by burakeregar** [comment]
The country list has been updated with [version 9.3.0](https://github.com/onfido/onfido-android-sdk/releases/tag/9.3.0). I can confirm that Kosovo has been added to the CountryCode enum class.
