### ISSUE TITLE
Instrumentation tests

### ISSUE THREAD

**Issue by nthieu90** [onfido/onfido-android-sdk#69]
hi all,
Is there any way to do Espresso Test with this SDK after we integrated to project?
Thanks

**Comment by bartzet** [comment]
Hi @nthieu90,

Could you please explain a bit more about what you would like to achieve? 

Are you asking whether it is possible to write your own E2E/UI tests with Espresso that would go through the SDK flow after integrating with your app?

Thanks,
Bart

**Comment by nthieu90** [comment]
Hi @bartzet,
Yes, that is what I want to do. I want to run a UI test on AWS device farm. How to test with CAPTURE_DOCUMENT and FaceCaptureVariantVideo, because we need documents and face to detect?
Thanks,
Hieu

**Comment by bartzet** [comment]
You don't need real document or video with face to go through the flow. 

For the document capture, we only run the checks that block the document upload on the first try. So if your test will take a picture for anything that is not a real document you will need to retry to take a picture again and on the second try with the upload you will not be blocked with going through the flow. 

Similar for video, if the face of the user or the head turn won't be detected, we show the button on the screen that allows the user to continue with the flow. 

Hope that helps.

**Comment by bartzet** [comment]
Yes, for passport we use auto-capture implementation so to ease the testing on your side will probably be better to go through the flow of other documents.

**Comment by nthieu90** [comment]
Thanks @bartzet
