### ISSUE TITLE
SSL handshake error on Android 4.4

### ISSUE THREAD

**Issue by shaubert** [onfido/onfido-android-sdk#7]
On Android 4.4 onfido SDK (2.3.0) failed to establish https connection with following error:

POST https://api.onfido.com/v2/applicants/6d1222a7-b5a5-465a-a878-7c825417ab89/documents http/1.1 (197384-byte body)
HTTP FAILED: javax.net.ssl.SSLException: SSL handshake aborted: ssl=0x7c27c5b0: I/O error during system call, Connection reset by peer
OnfidoAPI.Callback/onFailure:javax.net.ssl.SSLException: SSL handshake aborted: ssl=0x7c27c5b0: I/O error during system call, Connection reset by peer

**Comment by sergiomarquesmoura** [comment]
Fixed
