### ISSUE TITLE
Project depends on Jake Wharton's retrofit2-rxjava2-adapter, which was deprecated three years ago in favour of Retrofit's own RxJava2 adapter

### ISSUE THREAD

**Issue by fgsguedes** [onfido/onfido-android-sdk#70]
#### What was the expected behaviour?
When declaring a dependency for Retrofit `CallAdapter.Factory` for RxJava2, Onfido API Client should use library provided by Retrofit.

Expected adapter source and documentation: https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava2
Expected dependency declaration: `implementation "com.squareup.retrofit2:adapter-rxjava2:2.6.1"`

#### What happened instead?
Onfido API Client declares deprecated RxJava2 adapter created by Jake Wharton before official support from Retrofit was released.

Deprecated declared dependency documentation: https://github.com/JakeWharton/retrofit2-rxjava2-adapter

#### Version info:

- `onfido-capture-sdk` version: 5.0.0

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 21

#### Other useful info:
Change is relevant to ensure proper compatibility with latest Retrofit version.

Relevant snippet from gradle dependencies task output:
```
$ ./gradlew app:dependencies

+--- com.onfido.sdk.capture:onfido-capture-sdk:5.0.0
|    \--- com.onfido.sdk.capture:onfido-capture-sdk-core:5.0.0
|         +--- com.onfido.api.client:onfido-api-client:4.0.3
|         |    +--- com.squareup.okhttp3:okhttp:3.3.0 -> 4.1.0 (*)
|         |    +--- com.squareup.okhttp3:logging-interceptor:3.3.0 -> 4.1.0 (*)
|         |    +--- com.squareup.retrofit2:retrofit:2.1.0 -> 2.6.1 (*)
|         |    +--- com.squareup.retrofit2:converter-gson:2.1.0 -> 2.6.1 (*)
|         |    +--- com.jakewharton.retrofit:retrofit2-rxjava2-adapter:1.0.0
|         |    |    +--- com.squareup.retrofit2:retrofit:2.1.0 -> 2.6.1 (*)
|         |    |    \--- io.reactivex.rxjava2:rxjava:2.0.0 -> 2.2.10 (*)
|         |    \--- com.google.code.gson:gson:2.6.2 -> 2.8.5
|         +--- org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.31 -> 1.3.41 (*)
|         +--- io.reactivex.rxjava2:rxandroid:2.1.1 (*)
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.31 -> 1.3.41 (*)
|         +--- com.google.firebase:firebase-ml-vision:20.0.0 -> 23.0.0 (*)
|         +--- androidx.appcompat:appcompat:1.0.0 -> 1.0.2 (*)
|         \--- com.google.android.material:material:1.0.0 (*)
```

**Comment by sergiomarqmoura** [comment]
Hi @fgsguedes . We have this planned, I will update you here as soon as we release a version which addresses this issue

**Comment by gokhanaliccii** [comment]
Hi @fgsguedes, The RxJava2 adapter library has been updated, once we released a new version we will update the issue

**Comment by burakeregar** [comment]
@fgsguedes Version 5.6.0 has been released now. This release includes this library update as well. Please see https://github.com/onfido/onfido-android-sdk/releases/tag/5.6.0

**Comment by AhmedShabanElhdad** [comment]
```
Caused by java.lang.IllegalStateException
Single return type must be parameterized as Single<Foo> or Single<? extends Foo>
retrofit2.adapter.rxjava3.RxJava3CallAdapterFactory.get (RxJava3CallAdapterFactory.java:123)
```

i have this error when use onfido is that related to your upgrade from rxjava2 to rxjava3
