### ISSUE TITLE
Support for Dark theme

### ISSUE THREAD

**Issue by magnusvs** [onfido/onfido-android-sdk#73]
Is there any plans to implement support for Dark theme in the SDK? Either during config/start of the SDK or listening to the app theme.

#### What was the expected behaviour?
Dark theme support on Android 10. 

#### What happened instead?
The SDK runs in regular light mode.

#### Version info:

- `onfido-capture-sdk` version: 5.0.0
- Android API version(s): 29

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 21
- Support library version (if applicable):

**Comment by ramprasad-parajuli** [comment]
Hi @magnusvs , 
Unfortunately, the background color of the Onfido Android SDK is not customizable with the SDK functionality at the moment. We will be adding different background color/mode option in the future depending on the number of requests we receive from our clients. 
Let me know if you have additional questions or concerns.

**Comment by nikoker** [comment]
We are also in need of having the dark theme supported. It's only reasonable to request this. Why did you add this feature on iOS and not on Android? Our customers get a bad experience by seeing a light theme while the rest of the app is using the dark theme.
I will be awaiting your response.

**Comment by dtropanets** [comment]
Any update on this? Even giving us an ability to change the background color is better than nothing.

**Comment by JuzTosS** [comment]
Having dark theme support would be great!

**Comment by shaubert** [comment]
Plus one. It's really strange that dark theme is supported on iOS but not on Android, Both OS have dark mode toggles.

**Comment by burakeregar** [comment]
Hi,

Dark theme support is in our backlog at the moment. We'll update here once it's released.

**Comment by pmukerji** [comment]
Hi @burakeregar, are there any updates on a timeline to support dark theme on Android?

**Comment by BuddhikaAmila** [comment]
Hi @burakeregar any update on the dark theme ?

**Comment by buddhika886** [comment]
@musagil is this being added to the SDK now ?

**Comment by khiawyen** [comment]
hi @musagil is dark mode already supported?

**Comment by Celliusx3** [comment]
Hi @musagil is there any update on dark mode? Thanks!
