### ISSUE TITLE
Starting the SDK from a fragment

### ISSUE THREAD

**Issue by magnusvs** [onfido/onfido-android-sdk#74]
#### What was the expected behaviour?
A method like `fun startActivityForResult(fragment: Fragment, requestCode: Int, onfidoConfig: OnfidoConfig)`
to be able to receive the result in the fragment, instead of being forced to pass data from the activity to the current fragment.
Any plans on implementing this?

#### What happened instead?
There's only a `fun startActivityForResult(activity: Activity, requestCode: Int, onfidoConfig: OnfidoConfig)` available.

#### Version info:

- `onfido-capture-sdk` version: 5.0.0
- Android API version(s): 29

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 21
- Support library version (if applicable):

**Comment by rfreitas** [comment]
@magnusvs are you able to start it from the fragment just with the intent?

**Comment by freszu** [comment]
For future reference it's possible.
```kotlin
val onfidoIntent = onfidoClient.createIntent(onfidoConfig)
// this has to be invoked as createIntent doesn't setup SdkController resulting in crash
// usually this is called in Onfido.startActivityFromResult(...)
SdkController.Companion.instance.init(requireContext().applicationContext, onfidoConfig)
startActivityForResult(onfidoIntent, ONFIDO_ACTIVITY_REQUEST_CODE)
```

The requirement to have to launch this from activity is nonsense and should never been there. Consider the fact that many of the apps are going now to the single activity approach.

**Comment by magnusvs** [comment]
@freszu Thank you, this seems to be the way currently to start and get the result in a fragment. 

So yes @rfreitas I'm able to start it with the intent, but I agree that the requirement to launch this from an activity should not be there if not absolutely necessary. Can the documentation be updated if this is a supported way of starting the sdk?

**Comment by burakeregar** [comment]
Fragment support has been added. We are planning to include it to our next release. We'll update the issues once it's released. Thanks.

**Comment by burakeregar** [comment]
Version 5.6.0 has been released now. This release includes the fragment support. Please see https://github.com/onfido/onfido-android-sdk/releases/tag/5.6.0
