### ISSUE TITLE
Support for using custom fonts

### ISSUE THREAD

**Issue by louy** [onfido/onfido-android-sdk#75]
Hi guys,

#### What was the expected behaviour?
I want to be able to use a custom font in the SDK [similar to how I can do it in iOS](https://github.com/onfido/onfido-ios-sdk#ui-customisation)

#### What happened instead?
I can't use a custom font in the SDK

#### Version info:

- `onfido-capture-sdk` version: 4.10.0
- Android API version(s):
  - `compileSdkVersion`: 28
  - `targetSdkVersion`: 28
  - `minSdkVersion`: 19
- Support library version (if applicable): 28.0.0

**Comment by ramprasad-parajuli** [comment]
@louy Unfortunately it is not possible to define a custom font in the Android SDK at the moment. We are aiming to implement this feature in the future.

**Comment by gunhansancar** [comment]
Is there any timeline for supporting custom Fonts?

**Comment by gokhanaliccii** [comment]
We don't officially support font customization on android SDK yet but there is a way to customize texts on the SDK.

You need to override OnfidoTextStyle and OnfidoTextStyle.Title styles on your application to change fonts

**To change titles:**
```
 <style name="OnfidoTextStyle.Title">
        <item name="android:fontFamily">new_font</item>
 </style>
```

**To change all texts:**
```
 <style name="OnfidoTextStyle" parent="TextAppearance.AppCompat">
        <item name="android:textColor">@color/onfido_medium_500</item>
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="android:fontFamily">new_font</item>
 </style>
```

**Comment by gokhanaliccii** [comment]
🎉  Now the latest SDK version ([10.0.0](https://github.com/onfido/onfido-android-sdk/releases/tag/10.0.0)) supports [font customization](https://github.com/onfido/onfido-android-sdk#ui-customization) out of the box. 

Please try the latest version share your font customization experience with us 🙏
