### ISSUE TITLE
Does not upload document picture

### ISSUE THREAD

**Issue by pedrommmadeira** [onfido/onfido-android-sdk#76]
#### What was the expected behaviour?

Upload the document picture and proceed to the next step.

#### What happened instead?

An error shows up while uploading saying "Connection lost / Document capture failed. Please try again".

#### Version info:

- `onfido-capture-sdk` version: 5.0.1
- Android API version(s):

- `compileSdkVersion`: 29
- `targetSdkVersion`: 29
- `minSdkVersion`: 21
- Support library version (if applicable):

#### Steps to reproduce:

This happens while doing sandbox testing. Tokens are correctly generated and configured.
On a OnePlus 6 device, start the flow with default steps, proceed until after taking the first picture of a document.

#### Additional LogCat output:

It just shows a 401 HTTP response.

D/OkHttp: --> POST https://api.onfido.com/v2/documents http/1.1 (250202-byte body)
D/OkHttp: <-- 401  https://api.onfido.com/v2/documents (1308ms, 175-byte body)

**Comment by Gorbyy** [comment]
Hi @pedrommmadeira 

Which token mechanism are you using (SDK token or Mobile token)?
Please notice that the SDK token is restricted to an individual applicant and expires after 90 minutes. If you are using this token mechanism, can you please confirm that the token was not expired and that it was created with applicant uuid to which you were trying to upload a document?

Thanks in advance

**Comment by pedrommmadeira** [comment]
I'm using the SDK token mechanism. Immediately after creating an applicant I attach its id to the request to generate the SDK token, just as indicated in the documentation.

**Comment by Gorbyy** [comment]
Hi @pedrommmadeira,

Sorry for the delay in getting back to you. Can you please send us an email to api@onfido.com with the exact HTTP request you are making to our API to create the SDK token?

Thanks in advance

**Comment by Gorbyy** [comment]
After further discussion via email, we concluded that unfortunately @pedrommmadeira was not passing the right application_id when doing the Create SDK token request.
