### ISSUE TITLE
React-native Onfido sdk

### ISSUE THREAD

**Issue by chukhlov** [onfido/onfido-android-sdk#79]
Hello dear support. I need to use onfido on react-native.
I found https://github.com/MCROEngineering/react-native-onfido-sdk/
But this sdk does not work.
Could you help me to rewrite this module or write from scratch?

**Comment by rfreitas** [comment]
Hello @chukhlov , 

Unfortunately we don't have an official react native module yet. The repo you linked is not ours, although it's easy to think it is.
The best official reference we have is a react native sample app, which you can find here: https://github.com/onfido/onfido-sdk-react-native-sample-app

**Comment by chukhlov** [comment]
Thank you. I used this reference and it's working great!

**Comment by chukhlov** [comment]
I have an issue. I did build and install my APK to android device. I tried to take a passport and sent to server, but  got an error.

<img width="350" alt="Снимок экрана 2019-09-20 в 12 45 03" src="https://user-images.githubusercontent.com/49238231/65317419-7bd22580-dba4-11e9-8968-c8ca7c61faa1.png">

**Comment by sergiomarqmoura** [comment]
Hi @chukhlov . Could you check what the logs/network interceptor tells you about the response?

**Comment by chukhlov** [comment]
Hi @sergiomarqmoura 
Please look into screen

<img width="1601" alt="Снимок экрана 2019-09-20 в 12 59 00" src="https://user-images.githubusercontent.com/49238231/65318559-8392c980-dba6-11e9-9f02-7b61b85e9ae3.png">

**Comment by chukhlov** [comment]
I installed version com.onfido.sdk.capture:onfido-capture-sdk:4.11.0 and problem was solved

**Comment by sergiomarqmoura** [comment]
Ok, I guess you are using a new token format with an old version of the SDK. The react-native wrapper is a bit outdated and the new token format requires at least the version 4.10.0

**Comment by sergiomarqmoura** [comment]
@chukhlov exactly, a version newer than 4.11.0 is needed for this to work
