### ISSUE TITLE
Access value in applicant

### ISSUE THREAD

**Issue by nthieu90** [onfido/onfido-android-sdk#85]
Hi all,
When I finished the uploaded document I receive 'userCompleted' call back from Onfido.OnfidoResultListener but all properties in applicant are null, excepted 'id'.
How to get those properties?
Thanks,
Hieu

**Comment by ramprasad-parajuli** [comment]
@nthieu90 The Captures object contains information about the document and face captures made during the flow, while the Applicant object contains information about the newly created applicant object, **or will be null in case an applicantId was used to initialize the flow through withApplicant(String id)**.
If you want to view the applicant details, you could make use of the [Retreive Applicant](https://documentation.onfido.com/?shell#retrieve-applicant) Endpoint.

**Comment by nthieu90** [comment]
Hi @ramprasad-parajuli 
Yes, Captures object are what I need, but I don't why do they contain:  id, side, and type only? I have checked on iOS SDK, they return more info in Document Result, like href, name, filesize...
How can we get them on Android SDK?
Thanks

**Comment by rfreitas** [comment]
hi @nthieu90 , we don't plan to return these extra attributes on Android. And iOS we will make it consistent with Android. Can you elaborate a bit on your use and why you require other attributes on the client side?

**Comment by nthieu90** [comment]
hi @rfreitas 
Thanks for your info,
My team wants to use some attributes like the result on iOS. I just want to check may I did the right way because I got fewer data than iOS.
Thanks
