### ISSUE TITLE
 Not connected to internet even though it is an 401 - Unauthorized

### ISSUE THREAD

**Issue by kuzdu** [onfido/onfido-android-sdk#87]
#### What was the expected behaviour?
After the first taken picture I should receive an not authorized message/alert.  

#### What happened instead?
Connection lost message.
"Connection lost - Document capture did't work. Please try again."

#### Version info:
- `onfido-capture-sdk` version: tried 5.0.1 and 5.1.0
- Android API version(s): 9
- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 21
- Support library version (if applicable): androidX 

#### Steps to reproduce:
Use Pixel 2 API 28 Simulator

#### Issue severity information (number of users/crashes if applicable): 
No crashes. 

#### Additional LogCat output:
The error message is misleading. My internet connection works. I receive an 401 status code.
`D/OkHttp: <-- 401 https://api.onfido.com/v2/documents (490ms, 118-byte body)`  

#### Other useful info:
I used an SDKToken which is just valid for another application_id/package/bundle_id. But it is very misleading to get an "not connected" message

**Comment by gokhanaliccii** [comment]
@kuzdu  Thanks for reporting to the issue, we will improve our warning messages.

To create `sdkToken` firstly you need to create [applicantId](https://github.com/onfido/onfido-android-sdk#3-creating-an-applicant)  then you need create [sdkToken](https://github.com/onfido/onfido-android-sdk#41-sdk-token), you can find your **applicationId** from app/build.gradle file. 

```
android {
    ...

    defaultConfig {
        applicationId "your_application_id"

    ...
```


Please report us you'll have any problem
