### ISSUE TITLE
Overriding `refreshToken` method in TokenExpirationHandler

### ISSUE THREAD

**Issue by tombarton** [onfido/onfido-android-sdk#91]
#### What was the expected behaviour?

Attempting to implement an expiration handler via a new class, as described in the documentation:

```
import com.onfido.android.sdk.capture.token.TokenExpirationHandler;
...

class ExpirationHandler implements TokenExpirationHandler {
	@Override
	public void refreshToken(@NotNull Function1<? super String, Unit> tokenRefreshedWith) {
             ...
	}
}

```

I should be able to override the `refreshToken` method.

#### What happened instead?

I'm not able to override the `refreshToken` method; I get the following warning:

```Method does not override method from its superclass```

#### Version info:

- `onfido-capture-sdk` version: 5.3.0
- Android API version(s): 20

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 19
- Support library version (if applicable): 28.0.0

#### Steps to reproduce:

1. Attempt to implement TokenExpirationHandler as a new class in Java.

#### Onfido Flow initialization code:

```
flowSteps = new FlowStep[]{
		new CaptureScreenStep(documentType, CountryCode.GB),
		new FaceCaptureStep(captureVariant),
		FlowStep.FINAL
};

OnfidoConfig onfidoConfig = OnfidoConfig.builder(getReactApplicationContext())
		.withSDKToken(sdkToken, new ExpirationHandler())
		.withCustomFlow(flowSteps)
		.build();
```

#### Other useful info:
_screenshots, videos, etc._

**Comment by gokhanaliccii** [comment]
@tombarton Thanks for reporting to issue, sorry for inconvenience. 

The error occurs due to Function1 and Unit class which come from kotlin packages. 

We'll fix the problem incoming releases, during to this period do you mind to add kotlin-stdlib in your project ?

**Comment by tombarton** [comment]
Thanks @gokhanaliccii. You might also want to update the example in the documentation:

```
class ExpirationHandler implements TokenExpirationHandler {

    @Override
    public void refreshToken(@NotNull Function1<? super String, Unit> tokenRefreshedWith) {
        //Your network request logic to retrieve SDK token goes here
        injectNewToken.invoke("NEW_SDK_TOKEN"); // if you pass `null`  sdk exit with token expired error
    }
}
```

I'm guessing `injectNewToken` should be`tokenRefreshedWith`.

**Comment by burakeregar** [comment]
Version 5.6.0 has been released now. This release includes a fix for this issue. Please see https://github.com/onfido/onfido-android-sdk/releases/tag/5.6.0
