### ISSUE TITLE
userExited callback with USER_LEFT_ACTIVITY after successfuly finishing single CaptureScreenStep

### ISSUE THREAD

**Issue by dtropanets** [onfido/onfido-android-sdk#94]
I'm integrating a custom flow, which includes a single `CaptureScreenStep`. After I capture the document, I expect to see `userCompleted` callback, but I receive `userExited` callback with `USER_LEFT_ACTIVITY` exit code instead. 

I'm using the latest version of the SDK: `onfido-capture-sdk:5.3.0`

Initialization code:
``` Kotlin
val onfidoConfig = OnfidoConfig.builder(requireContext())
    .withSDKToken(token)
    .withCustomFlow(
        arrayOf(CaptureScreenStep(DocumentType.DRIVING_LICENCE, CountryCode.GB))
    )
    .build()

val onfidoIntent = onfido.createIntent(onfidoConfig)

// this has to be invoked as createIntent doesn't setup SdkController resulting in crash
// usually this is called in Onfido.startActivityFromResult(...)
SdkController.Companion.instance.init(requireContext().applicationContext, onfidoConfig)
startActivityForResult(onfidoIntent, ONFIDO_ACTIVITY_REQUEST_CODE)
```

Callback code:
``` Kotlin
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
    super.onActivityResult(requestCode, resultCode, data)

    if (requestCode == ONFIDO_ACTIVITY_REQUEST_CODE) {
        onfido.handleActivityResult(resultCode, data, object : OnfidoResultListener {
            override fun onError(exception: OnfidoException) {
                Timber.e(exception, "onError")
            }

            override fun userCompleted(captures: Captures) {
                Timber.d("userCompleted")
                check()
            }

            override fun userExited(exitCode: ExitCode) {
                Timber.d("userExited code-$exitCode")
            }
        })
    }
}
```

Is this an expected behavior and we have to do another check() on `userExited` callback or is this an issue, which can be resolved?

Thanks

**Comment by gokhanaliccii** [comment]
@dtropanets  you have to call startActivityResult from `onfido` object 

`onfido. startActivityForResult(activity, requestCode, onfidoIntent)` 

Could you me a feedback after you made change ?

**Comment by dtropanets** [comment]
@gokhanaliccii moving the code to activity and calling `onfido.startActivityForResult(this, ONFIDO_ACTIVITY_REQUEST_CODE, onfidoConfig)` with the config from above doesn't seem to change anything. I still get `userExited(USER_LEFT_ACTIVITY)` response.

**Comment by gokhanaliccii** [comment]
@dtropanets  I tried to reproduce the error but unfortunately i couldn't.  

Could you please try to replicate on [our sample app](https://github.com/onfido/onfido-android-sample-app) ?

**Comment by dtropanets** [comment]
@gokhanaliccii sample app is working fine, thank you. 

Seems like, there is some dependencies conflict, thus the process is crashing when sdk tries to do the internal network request.
