### ISSUE TITLE
Back button behaviour on confirmation screen

### ISSUE THREAD

**Issue by tombarton** [onfido/onfido-android-sdk#95]
#### What was the expected behaviour?

When I reach the final step in the flow (`FlowStep.FINAL`) and press the 'back' button, I expect to be taken to the previous step in the flow.

#### What happened instead?

The `userExited` callback is triggered instead.

#### Version info:

- `onfido-capture-sdk` version: 5.3.0
- Android API version(s): 29

- `compileSdkVersion`: 28
- `targetSdkVersion`: 28
- `minSdkVersion`: 19
- Support library version (if applicable): 28.0.0

#### Steps to reproduce:

1. Create a basic flow using the initialization code below. 
2. Navigate through the flow until you reach the final step.
3. Press the back button.

#### Onfido Flow initialization code:

```
flowSteps = new FlowStep[]{
		new CaptureScreenStep(documentType, CountryCode.GB),
		new FaceCaptureStep(captureVariant),
		FlowStep.FINAL
};
```

#### Issue severity information (number of users/crashes if applicable):

N/A

#### Additional LogCat output:

N/A

#### Other useful info:

N/A

**Comment by ramprasad-parajuli** [comment]
@tombarton Thank you for flagging the issue you experienced.
It is the intended behavior of the SDK as at this stage of the user journey after the user has carried out the required uploads, our hypothesis is that the user's intention is to abandon when they click "back". Of course, this may not be true for all scenarios and our team is already aware of the behavior.
As a workaround to the issue, I wanted to inform you that the final screen is entirely optional. If you remove it from the flow definition, you will receive the `userCompleted` event after all the required uploads. This way you could immediately forward the user to the next step in the onboarding journey, and there should be no confusion.

**Comment by tombarton** [comment]
Perfect, thanks for letting me know @raemarielee.
