### ISSUE TITLE
NullPointerException Attempt to invoke virtual method 'com.onfido.segment.analytics.ba com.onfido.segment.analytics.ba.a(java.lang.Object)' on a null object reference com.onfido.segment.analytics.Analytics.a

### ISSUE THREAD

**Issue by shaubert** [onfido/onfido-android-sdk#99]
#### What was the expected behaviour?
No crash

#### What happened instead?
Crash

#### Version info:
- `onfido-capture-sdk` version: 5.0.1
- Android API version(s): Android 9 and 10

- `compileSdkVersion`: 29
- `targetSdkVersion`:29
- `minSdkVersion`:21

#### Other useful info:
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'com.onfido.segment.analytics.ba com.onfido.segment.analytics.ba.a(java.lang.Object)' on a null object reference
com.onfido.segment.analytics.Analytics.a (Unknown Source:39)
com.onfido.segment.analytics.e.run (Unknown Source:6)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7397)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:935)

```

![Screenshot from 2020-02-18 18-25-00](https://user-images.githubusercontent.com/1733477/74761309-1af66880-527c-11ea-8e18-4f754cdc69a7.png)
![Screenshot from 2020-02-18 18-25-15](https://user-images.githubusercontent.com/1733477/74761306-1a5dd200-527c-11ea-91b5-95ea56c1e982.png)

**Comment by seewah** [comment]
Apologies. it was a backend hiccup. it should be fixed now.

**Comment by seewah** [comment]
status report here: https://status.onfido.com/incidents/m5py2jsgzw25
